import Link from "next/link";
import { notFound } from "next/navigation";
import { DomainError } from "@/domain/errors";
import type { ReviewReportContributorSelector, ReviewReportMetric, ReviewReportMetricKey } from "@/domain/review-report";
import { reviewServices } from "@/app/server";

const metricKeys = new Set<ReviewReportMetricKey>([
  "distinctSearchRuns", "reportedResultsTotal", "retrievedRecords", "distinctSources", "currentlyResolvedRecords", "unresolvedRecords", "unresolvedDuplicatePairs", "sameWorkDecisionPairs", "differentWorkDecisionPairs", "acquisitionDerivedPapers", "duplicateRecordsCollapsed", "papersInScreeningPopulation", "unscreened", "included", "excluded", "maybe", "fullTextEligible", "fullTextRetrievalEligible", "fullTextAwaiting", "fullTextAssessed", "fullTextIncluded", "fullTextExcluded", "fullTextMaybe", "fullTextConflicts", "fullTextNotSought", "fullTextRetrievalPending", "fullTextRetrieved", "fullTextUnavailable", "fullTextSought", "fullTextEverSought", "fullTextEverRetrieved", "legacyFullTextWithoutRetrieval", "fullTextRetrievalConflicts", "finallyIncluded", "legacyAnalysisAwaitingFullText", "historicalAcquisitionOnlyPapers", "manualPapers",
]);
const sourceMetricKeys = new Set(["runs", "reportedResults", "retrievedRecords", "resolvedRecords", "acquisitionPapers"] as const);

function metricLink(projectId: string, metric: ReviewReportMetric) {
  return metric.support === "unsupported" ? undefined : `/projects/${projectId}/review-report?metric=${encodeURIComponent(metric.key)}`;
}

function Metric({ projectId, item }: { projectId: string; item: ReviewReportMetric }) {
  const href = metricLink(projectId, item);
  const content = <><span>{item.label}</span><strong>{item.value}</strong></>;
  return href ? <Link className="item-row" href={href} title={item.explanation}>{content}</Link> : <div className="item-row" title={item.explanation}><span>{item.label}</span><strong>Unsupported</strong></div>;
}

export default async function ReviewReportPage({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams?: Promise<{ metric?: string; sourceId?: string; sourceMetric?: string; criterionId?: string; fullTextCriterionId?: string; overlap?: string }> }) {
  const { projectId } = await params;
  const query = searchParams ? await searchParams : {};
  let report;
  try { report = await reviewServices.getReviewReport(projectId); } catch (error) { if (error instanceof DomainError && ["PROJECT_NOT_FOUND", "VALIDATION_ERROR"].includes(error.code)) notFound(); throw error; }
  let selector: ReviewReportContributorSelector | null = null;
  if (query.metric && metricKeys.has(query.metric as ReviewReportMetricKey)) selector = { scope: "metric", metric: query.metric as ReviewReportMetricKey };
  else if (query.sourceId && query.sourceMetric && sourceMetricKeys.has(query.sourceMetric as never)) selector = { scope: "source", sourceId: query.sourceId, metric: query.sourceMetric as "runs" | "reportedResults" | "retrievedRecords" | "resolvedRecords" | "acquisitionPapers" };
  else if (query.criterionId) selector = { scope: "exclusionReason", criterionId: query.criterionId };
  else if (query.fullTextCriterionId) selector = { scope: "fullTextExclusionReason", criterionId: query.fullTextCriterionId };
  else if (query.overlap === "1") selector = { scope: "overlap" };
  const contributors = selector ? await reviewServices.listReviewReportContributors(projectId, selector) : null;

  return <main className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">T</span> Tracework</Link><span className="top-note">Evidence-first literature reviews</span></header>
    <div className="container workspace"><Link className="back-link" href={`/projects/${projectId}`}>← Back to workspace</Link>
      <div className="workspace-header"><div><p className="eyebrow">Derived reporting projection · {report.project.title}</p><h1>Review Flow Report</h1><p>PRISMA-oriented reporting over recorded acquisition, resolution, and title/abstract screening facts.</p></div><a className="button secondary" href={`/projects/${projectId}/review-report/export`}>Download Markdown</a></div>
      <section className="card section-card full"><div className="section-heading"><h2>Research Questions</h2><span className="count">active context</span></div>{report.activeResearchQuestions.length === 0 ? <div className="empty">No active research questions recorded.</div> : <div className="item-list">{report.activeResearchQuestions.map((question) => <div className="item" key={question.id}><div className="item-title">{question.identifier}: {question.label}</div></div>)}</div>}</section>
      <section className="card section-card full"><div className="section-heading"><h2>Current Screening Criteria</h2><span className="count">active protocol context</span></div>{report.activeCriteria.length === 0 ? <div className="empty">No active screening criteria recorded.</div> : <div className="item-list">{report.activeCriteria.map((criterion) => <div className="item" key={criterion.id}><div className="item-meta">{criterion.type}</div><div className="item-title">{criterion.text}</div></div>)}</div>}</section>
      <section className="card section-card full"><div className="section-heading"><h2>Current Full-text Criteria</h2><span className="count">active full-text protocol context</span></div>{report.activeFullTextCriteria.length === 0 ? <div className="empty">No active full-text criteria recorded.</div> : <div className="item-list">{report.activeFullTextCriteria.map((criterion) => <div className="item" key={criterion.id}><div className="item-title">{criterion.text}</div></div>)}</div>}</section>
      <section className="card section-card full"><div className="section-heading"><h2>Search Identification</h2><span className="count">reported results are not unique records</span></div><div className="item-list">{report.identification.metrics.map((item) => <div className="item" key={item.key}><Metric projectId={projectId} item={item} /></div>)}</div><p className="footer-note">Reported results are the totals recorded by searches. RetrievedRecords are the records actually entered.</p><div className="nested-support"><div className="item-meta">Cross-source overlap</div><Link className="item-row" href={`/projects/${projectId}/review-report?overlap=1`}><span>Papers linked through more than one SearchSource</span><strong>{report.identification.overlappingPaperCount}</strong></Link></div></section>
      <section className="card section-card full"><div className="section-heading"><h2>By SearchSource</h2><span className="count">grouped by stable SearchSource identity</span></div><div className="item-list">{report.identification.bySource.length === 0 ? <div className="empty">No SearchRuns recorded.</div> : report.identification.bySource.map((source) => { const historical = source.observedSnapshots[0] ?? { displayName: source.source.displayName, sourceKey: source.source.sourceKey }; return <article className="item" key={source.source.id}><div className="item-row"><div><div className="item-title">{historical.displayName}</div><div className="item-meta">{historical.sourceKey}{source.source.archivedAt ? " · archived configuration" : ""}</div></div><strong>{source.runCount} runs</strong></div><div className="item-meta">Historical labels: {source.observedSnapshots.map((snapshot) => `${snapshot.displayName} [${snapshot.sourceKey}]`).join("; ")}</div>{(source.source.displayName !== historical.displayName || source.source.sourceKey !== historical.sourceKey) && <div className="item-meta">Current SearchSource configuration: {source.source.displayName} [{source.source.sourceKey}]</div>}<div className="item-list" style={{ marginTop: 10 }}><Link className="item-row" href={`/projects/${projectId}/review-report?sourceId=${source.source.id}&sourceMetric=runs`}><span>Recorded search runs</span><strong>{source.runCount}</strong></Link><Link className="item-row" href={`/projects/${projectId}/review-report?sourceId=${source.source.id}&sourceMetric=reportedResults`}><span>Results reported by searches</span><strong>{source.reportedResults}</strong></Link><Link className="item-row" href={`/projects/${projectId}/review-report?sourceId=${source.source.id}&sourceMetric=retrievedRecords`}><span>RetrievedRecords entered</span><strong>{source.retrievedRecords}</strong></Link><Link className="item-row" href={`/projects/${projectId}/review-report?sourceId=${source.source.id}&sourceMetric=resolvedRecords`}><span>RetrievedRecords currently resolved</span><strong>{source.currentlyResolvedRecords}</strong></Link><Link className="item-row" href={`/projects/${projectId}/review-report?sourceId=${source.source.id}&sourceMetric=acquisitionPapers`}><span>Papers currently linked from this source <span className="hint">(non-additive)</span></span><strong>{source.acquisitionDerivedPapers}</strong></Link></div></article>; })}</div></section>
      <section className="card section-card full"><div className="section-heading"><h2>Deduplication and Paper Resolution</h2><span className="count">current derived state</span></div><div className="item-list">{report.deduplication.metrics.map((item) => <div className="item" key={item.key}><Metric projectId={projectId} item={item} /></div>)}</div></section>
      <section className="card section-card full"><div className="section-heading"><h2>Title/Abstract Screening</h2><span className="count">current state of canonical Papers</span></div><div className="item-list">{report.screening.metrics.map((item) => <div className="item" key={item.key}><Metric projectId={projectId} item={item} /></div>)}</div><div className="nested-support"><div className="item-meta">Current title/abstract exclusion reasons</div>{report.screening.exclusionReasons.length === 0 ? <div className="empty">No current exclusions.</div> : <div className="item-list">{report.screening.exclusionReasons.map((reason) => <Link className="item-row" key={reason.criterionId} href={`/projects/${projectId}/review-report?criterionId=${reason.criterionId}`}><span>{reason.text}{reason.archived ? " (criterion archived)" : ""}</span><strong>{reason.count}</strong></Link>)}</div>}</div></section>
      <section className="card section-card full"><div className="section-heading"><h2>Full-text Eligibility</h2><span className="count">stage-specific current projection</span></div><div className="item-list">{report.fullTextEligibility.metrics.map((item) => <div className="item" key={item.key}><Metric projectId={projectId} item={item} /></div>)}</div><div className="nested-support"><div className="item-meta">Current full-text exclusion reasons</div>{report.fullTextEligibility.exclusionReasons.length === 0 ? <div className="empty">No current full-text exclusions.</div> : <div className="item-list">{report.fullTextEligibility.exclusionReasons.map((reason) => <Link className="item-row" key={reason.criterionId} href={`/projects/${projectId}/review-report?fullTextCriterionId=${reason.criterionId}`}><span>{reason.text}{reason.archived ? " (criterion archived)" : ""}</span><strong>{reason.count}</strong></Link>)}</div>}</div></section>
      <section className="card section-card full"><div className="section-heading"><h2>Full-text Retrieval</h2><span className="count">current state plus separate historical facts</span></div><div className="item-list">{report.fullTextRetrieval.metrics.map((item) => <div className="item" key={item.key}><Metric projectId={projectId} item={item} /></div>)}</div><p className="footer-note">Ever retrieved remains true when a later attempt is unavailable. Current unavailable is not a claim that a Paper was never retrieved.</p></section>
      <section className="card section-card full"><div className="section-heading"><h2>Final eligibility</h2><span className="count">analytical write boundary</span></div><div className="item-list">{report.finalEligibility.metrics.map((item) => <div className="item" key={item.key}><Metric projectId={projectId} item={item} /></div>)}</div></section>
      <section className="card section-card full"><div className="section-heading"><h2>Reporting Support and Limitations</h2><span className="count">model-derived</span></div><div className="item-list">{report.supportMatrix.map((mapping) => <div className="item" key={mapping.key}><div className="item-row"><span>{mapping.label}</span><strong className={`status ${mapping.support === "unsupported" ? "unsupported" : mapping.support === "partially_supported" ? "maybe" : "supported"}`}>{mapping.support}</strong></div><div className="item-meta">{mapping.explanation}</div></div>)}{report.limitations.map((item) => <div className="item" key={item.code}><div className="item-meta">{item.message}</div></div>)}</div></section>
      <section className="card section-card full"><div className="section-heading"><h2>Immutable SearchRun Appendix</h2><span className="count">historical snapshots</span></div>{report.identification.runs.length === 0 ? <div className="empty">No SearchRuns recorded.</div> : <div className="item-list">{report.identification.runs.map((run) => <Link className="item" key={run.id} href={`/projects/${projectId}/protocol/runs/${run.id}`}><div className="item-row"><div className="item-title">Run {run.sequence} · {run.sourceDisplayNameSnapshot}</div><span className="status supported">{run.reportedResultCount} reported</span></div><div className="item-meta">{new Date(run.executedAt).toISOString()} · {run.enteredRecordCount} RetrievedRecords entered</div><div className="quote">{run.queryText}</div></Link>)}</div>}</section>
      {contributors && <section className="card section-card full"><div className="section-heading"><h2>Contributors</h2><span className="count">{contributors.total} contribution total</span></div>{contributors.items.length === 0 ? <div className="empty">No contributors.</div> : <div className="item-list">{contributors.items.map((item) => <div className="item" key={`${item.kind}-${item.id}`}><div className="item-row"><span>{item.label}</span><strong>{item.contribution}</strong></div><div className="item-meta">{item.kind}</div></div>)}</div>}</section>}
      <p className="footer-note">This report is derived on demand. It does not create report state, alter workflow history, or claim formal PRISMA compliance.</p>
    </div></main>;
}
