import { previewAiExtractionBatchAction, createAiExtractionBatchAction } from "@/app/actions";
import { aiExtractionProviderAvailable } from "@/app/server";

export default async function NewExtractionBatchPage({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams?: Promise<{ previewHash?: string; cells?: string; executable?: string; reusable?: string; error?: string }> }) {
  const { projectId } = await params;
  const query = searchParams ? await searchParams : {};
  return <div className="project-page">
    <div className="container workspace"><div className="workspace-header"><div><p className="eyebrow">Researcher confirmation</p><h1>Prepare an AI extraction batch</h1><p>The JSON selection is previewed and revalidated at creation. Provider calls do not occur here.</p></div></div>
      {query.error && <div className="error-banner" role="alert">{query.error}</div>}{query.cells && <div className="success-note" role="status">Preview: {query.cells} cells · {query.executable ?? "0"} executable · {query.reusable ?? "0"} reusable. Review the selection before creating.</div>}
      {!aiExtractionProviderAvailable && <div className="error-banner" role="status">The AI extraction provider is not configured. Existing batch history remains readable, but new batch creation is disabled.</div>}
      <section className="card section-card"><form action={previewAiExtractionBatchAction}><input type="hidden" name="projectId" value={projectId} /><div className="field"><label htmlFor="batch-items">Selected Paper × field cells (JSON)</label><textarea id="batch-items" name="itemsJson" required rows={12} disabled={!aiExtractionProviderAvailable} defaultValue={'[{"paperId":"00000000-0000-4000-8000-000000000000","fieldId":"00000000-0000-4000-8000-000000000001","idempotencyKey":"00000000-0000-4000-8000-000000000002"}]'} /><p className="hint">Each item may also include fullTextDocumentId and documentTextExtractionId. Use stable idempotencyKey values when moving from preview to creation.</p></div><label className="checkbox-row"><input type="checkbox" name="externalTransmissionAcknowledged" required disabled={!aiExtractionProviderAvailable} /> <span>I understand that eligible pinned page text may be transmitted to the configured OpenAI provider.</span></label><button className="button secondary" type="submit" disabled={!aiExtractionProviderAvailable}>Preview eligibility</button></form>
        <form action={createAiExtractionBatchAction} style={{ marginTop: 18 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="confirmationHash" value={query.previewHash ?? ""} /><div className="field"><label htmlFor="batch-items-confirm">Create from reviewed selection</label><textarea id="batch-items-confirm" name="itemsJson" required rows={8} disabled={!aiExtractionProviderAvailable} placeholder="Paste the same reviewed JSON selection here" /><p className="hint">Creation repeats the entire SERIALIZABLE preview and writes only the batch manifest and items. A prior preview confirmation is required.</p></div><label className="checkbox-row"><input type="checkbox" name="externalTransmissionAcknowledged" required disabled={!aiExtractionProviderAvailable} /> <span>I confirm this exact selection and transmission disclosure.</span></label><button className="button" type="submit" disabled={!aiExtractionProviderAvailable}>Create batch</button></form></section>
    </div></div>;
}
