import {
  integer,
  index,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  foreignKey,
  primaryKey,
  check,
  bigint,
  boolean,
  numeric,
  jsonb,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { projects, papers } from "./foundation";
import { screeningDecisions, fullTextScreeningDecisions } from "./screening";
import { fullTextDocuments, documentTextExtractions, documentTextExtractionPages, evidence } from "./documents-evidence";
import { extractionFields, extractionOptions, extractionValueRevisions } from "./extraction";

export const aiExtractionRequests = pgTable(
  "ai_extraction_requests",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    paperId: uuid("paper_id").notNull(),
    extractionFieldId: uuid("extraction_field_id").notNull(),
    fullTextDocumentId: uuid("full_text_document_id").notNull(),
    documentTextExtractionId: uuid("document_text_extraction_id").notNull(),
    baselineExtractionRevisionId: uuid("baseline_extraction_revision_id"),
    idempotencyKey: uuid("idempotency_key").notNull(),
    intentHash: text("intent_hash").notNull(),
    fieldNameSnapshot: text("field_name_snapshot").notNull(),
    fieldDescriptionSnapshot: text("field_description_snapshot"),
    fieldType: text("field_type").notNull(),
    optionSnapshot: jsonb("option_snapshot").notNull().default([]),
    provider: text("provider").notNull(),
    configuredModel: text("configured_model").notNull(),
    configuredReasoningEffort: text("configured_reasoning_effort").notNull(),
    promptVersion: text("prompt_version").notNull(),
    responseSchemaVersion: text("response_schema_version").notNull(),
    groundingResolverVersion: text("grounding_resolver_version").notNull(),
    contextSelectionVersion: text("context_selection_version").notNull(),
    sourceCharacterCount: integer("source_character_count").notNull(),
    sourceByteSize: integer("source_byte_size").notNull(),
    pageManifestHash: text("page_manifest_hash").notNull(),
    externalTransmissionAcknowledged: boolean("external_transmission_acknowledged").notNull(),
    disclosureVersion: text("disclosure_version").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_requests_project_id_id_unique").on(table.projectId, table.id),
    idempotency: unique("ai_extraction_requests_project_id_idempotency_key_unique").on(table.projectId, table.idempotencyKey),
    projectPaperFieldIdentity: unique("ai_extraction_requests_project_paper_field_id_unique").on(table.projectId, table.paperId, table.extractionFieldId, table.id),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "ai_extraction_requests_project_fk" }).onDelete("restrict"),
    paperOwnership: foreignKey({ columns: [table.projectId, table.paperId], foreignColumns: [papers.projectId, papers.id], name: "ai_extraction_requests_paper_fk" }).onDelete("restrict"),
    fieldOwnership: foreignKey({ columns: [table.projectId, table.extractionFieldId], foreignColumns: [extractionFields.projectId, extractionFields.id], name: "ai_extraction_requests_field_fk" }).onDelete("restrict"),
    documentOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.fullTextDocumentId], foreignColumns: [fullTextDocuments.projectId, fullTextDocuments.paperId, fullTextDocuments.id], name: "ai_extraction_requests_document_fk" }).onDelete("restrict"),
    extractionOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.documentTextExtractionId], foreignColumns: [documentTextExtractions.projectId, documentTextExtractions.paperId, documentTextExtractions.id], name: "ai_extraction_requests_extraction_fk" }).onDelete("restrict"),
    baselineRevisionOwnership: foreignKey({ columns: [table.projectId, table.baselineExtractionRevisionId], foreignColumns: [extractionValueRevisions.projectId, extractionValueRevisions.id], name: "ai_extraction_requests_baseline_revision_fk" }).onDelete("restrict"),
    fieldTypeValid: check("ai_extraction_requests_field_type_valid", sql`${table.fieldType} in ('short_text', 'long_text', 'number', 'boolean', 'single_select')`),
    providerNonblank: check("ai_extraction_requests_provider_nonblank", sql`btrim(${table.provider}) <> ''`),
    modelNonblank: check("ai_extraction_requests_model_nonblank", sql`btrim(${table.configuredModel}) <> ''`),
    versionShape: check("ai_extraction_requests_version_shape", sql`btrim(${table.promptVersion}) <> '' and btrim(${table.responseSchemaVersion}) <> '' and btrim(${table.groundingResolverVersion}) <> '' and btrim(${table.contextSelectionVersion}) <> ''`),
    hashShape: check("ai_extraction_requests_hash_shape", sql`${table.intentHash} ~ '^[0-9a-f]{64}$' and ${table.pageManifestHash} ~ '^[0-9a-f]{64}$'`),
    sourceBounds: check("ai_extraction_requests_source_bounds", sql`${table.sourceCharacterCount} >= 0 and ${table.sourceCharacterCount} <= 80000 and ${table.sourceByteSize} >= 0 and ${table.sourceByteSize} <= 327680`),
    acknowledged: check("ai_extraction_requests_transmission_acknowledged", sql`${table.externalTransmissionAcknowledged} = true`),
  }),
);

export const aiExtractionRequestPages = pgTable(
  "ai_extraction_request_pages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    pageId: uuid("page_id").notNull(),
    paperId: uuid("paper_id").notNull(),
    fullTextDocumentId: uuid("full_text_document_id").notNull(),
    documentTextExtractionId: uuid("document_text_extraction_id").notNull(),
    pageNumber: integer("page_number").notNull(),
    pageOrdinal: integer("page_ordinal").notNull(),
    textSha256: text("text_sha256").notNull(),
    characterCount: integer("character_count").notNull(),
    byteSize: integer("byte_size").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_request_pages_project_id_id_unique").on(table.projectId, table.id),
    requestPage: unique("ai_extraction_request_pages_request_page_unique").on(table.projectId, table.requestId, table.pageNumber),
    requestOrdinal: unique("ai_extraction_request_pages_request_ordinal_unique").on(table.projectId, table.requestId, table.pageOrdinal),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiExtractionRequests.projectId, aiExtractionRequests.id], name: "ai_extraction_request_pages_request_fk" }).onDelete("restrict"),
    sourcePageOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.documentTextExtractionId, table.pageNumber], foreignColumns: [documentTextExtractionPages.projectId, documentTextExtractionPages.paperId, documentTextExtractionPages.documentTextExtractionId, documentTextExtractionPages.pageNumber], name: "ai_extraction_request_pages_source_page_fk" }).onDelete("restrict"),
    sourcePageIdentity: foreignKey({ columns: [table.projectId, table.pageId], foreignColumns: [documentTextExtractionPages.projectId, documentTextExtractionPages.id], name: "ai_extraction_request_pages_source_page_id_fk" }).onDelete("restrict"),
    pageNumberValid: check("ai_extraction_request_pages_page_number_valid", sql`${table.pageNumber} > 0 and ${table.pageNumber} <= 2000`),
    ordinalValid: check("ai_extraction_request_pages_ordinal_valid", sql`${table.pageOrdinal} >= 0 and ${table.pageOrdinal} < 40`),
    hashShape: check("ai_extraction_request_pages_hash_shape", sql`${table.textSha256} ~ '^[0-9a-f]{64}$'`),
    countBounds: check("ai_extraction_request_pages_count_bounds", sql`${table.characterCount} > 0 and ${table.characterCount} <= 500000 and ${table.byteSize} > 0 and ${table.byteSize} <= 2000000`),
  }),
);

export const aiExtractionDispatches = pgTable(
  "ai_extraction_dispatches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    deadlineAt: timestamp("deadline_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_dispatches_project_id_id_unique").on(table.projectId, table.id),
    requestUnique: unique("ai_extraction_dispatches_project_request_unique").on(table.projectId, table.requestId),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiExtractionRequests.projectId, aiExtractionRequests.id], name: "ai_extraction_dispatches_request_fk" }).onDelete("restrict"),
    deadlineOrder: check("ai_extraction_dispatches_deadline_order", sql`${table.deadlineAt} > ${table.startedAt}`),
  }),
);

export const aiExtractionResults = pgTable(
  "ai_extraction_results",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    outcome: text("outcome").notNull(),
    providerDiagnostic: text("provider_diagnostic").notNull(),
    errorCode: text("error_code"),
    candidateState: text("candidate_state"),
    textValue: text("text_value"),
    numberValue: numeric("number_value", { precision: 30, scale: 10 }),
    booleanValue: boolean("boolean_value"),
    optionId: uuid("option_id"),
    explanation: text("explanation"),
    providerRequestId: text("provider_request_id"),
    configuredModel: text("configured_model").notNull(),
    returnedModel: text("returned_model"),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    durationMs: integer("duration_ms"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_results_project_id_id_unique").on(table.projectId, table.id),
    requestUnique: unique("ai_extraction_results_project_request_unique").on(table.projectId, table.requestId),
    requestIdentity: unique("ai_extraction_results_project_request_id_unique").on(table.projectId, table.requestId, table.id),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiExtractionRequests.projectId, aiExtractionRequests.id], name: "ai_extraction_results_request_fk" }).onDelete("restrict"),
    optionOwnership: foreignKey({ columns: [table.projectId, table.optionId], foreignColumns: [extractionOptions.projectId, extractionOptions.id], name: "ai_extraction_results_option_fk" }).onDelete("restrict"),
    outcomeValid: check("ai_extraction_results_outcome_valid", sql`${table.outcome} in ('succeeded', 'no_candidate', 'provider_unavailable', 'failed', 'invalid_output', 'unresolvable_grounding', 'outcome_unknown')`),
    diagnosticValid: check("ai_extraction_results_provider_diagnostic_valid", sql`${table.providerDiagnostic} in ('success', 'refusal', 'incomplete', 'schema_invalid', 'transport_error', 'api_error', 'unknown')`),
    candidateStateValid: check("ai_extraction_results_candidate_state_valid", sql`${table.candidateState} is null or ${table.candidateState} in ('present', 'not_reported', 'not_applicable')`),
    candidateValueShape: check("ai_extraction_results_candidate_value_shape", sql`(
      (${table.candidateState} is null and ${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is null)
      or (${table.candidateState} <> 'present' and ${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is null)
      or (${table.candidateState} = 'present' and (
        (${table.textValue} is not null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is null)
        or (${table.textValue} is null and ${table.numberValue} is not null and ${table.booleanValue} is null and ${table.optionId} is null)
        or (${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is not null and ${table.optionId} is null)
        or (${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is not null)
      ))
    )`),
    terminalShape: check("ai_extraction_results_terminal_shape", sql`${table.finalizedAt} is not null`),
    boundedText: check("ai_extraction_results_bounded_text", sql`${table.textValue} is null or char_length(${table.textValue}) <= 10000`),
    boundedExplanation: check("ai_extraction_results_bounded_explanation", sql`${table.explanation} is null or char_length(${table.explanation}) <= 10000`),
    boundedError: check("ai_extraction_results_bounded_error", sql`${table.errorCode} is null or (btrim(${table.errorCode}) <> '' and char_length(${table.errorCode}) <= 200)`),
     usageBounds: check("ai_extraction_results_usage_bounds", sql`(${table.inputTokens} is null or ${table.inputTokens} >= 0) and (${table.outputTokens} is null or ${table.outputTokens} >= 0) and (${table.durationMs} is null or ${table.durationMs} >= 0)`),
  }),
);

export const aiExtractionResultGroundings = pgTable(
  "ai_extraction_result_groundings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    resultId: uuid("result_id").notNull(),
    pageId: uuid("page_id").notNull(),
    pageNumber: integer("page_number").notNull(),
    startOffset: integer("start_offset").notNull(),
    endOffset: integer("end_offset").notNull(),
    locatorQuote: text("locator_quote").notNull(),
    locatorPrefix: text("locator_prefix"),
    locatorSuffix: text("locator_suffix"),
    sourceText: text("source_text").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_result_groundings_project_id_id_unique").on(table.projectId, table.id),
    resultIdentity: unique("ai_extraction_result_groundings_result_page_start_end_unique").on(table.projectId, table.resultId, table.pageNumber, table.startOffset, table.endOffset),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiExtractionRequests.projectId, aiExtractionRequests.id], name: "ai_extraction_result_groundings_request_fk" }).onDelete("restrict"),
    resultOwnership: foreignKey({ columns: [table.projectId, table.requestId, table.resultId], foreignColumns: [aiExtractionResults.projectId, aiExtractionResults.requestId, aiExtractionResults.id], name: "ai_extraction_result_groundings_result_fk" }).onDelete("restrict"),
    pageOwnership: foreignKey({ columns: [table.projectId, table.pageId], foreignColumns: [documentTextExtractionPages.projectId, documentTextExtractionPages.id], name: "ai_extraction_result_groundings_page_fk" }).onDelete("restrict"),
    pagePositive: check("ai_extraction_result_groundings_page_positive", sql`${table.pageNumber} > 0`),
    offsetShape: check("ai_extraction_result_groundings_offset_shape", sql`${table.startOffset} >= 0 and ${table.endOffset} > ${table.startOffset} and ${table.endOffset} - ${table.startOffset} <= 4000`),
    quoteNonblank: check("ai_extraction_result_groundings_quote_nonblank", sql`btrim(${table.locatorQuote}) <> '' and char_length(${table.locatorQuote}) <= 4000`),
    contextBounds: check("ai_extraction_result_groundings_context_bounds", sql`(${table.locatorPrefix} is null or char_length(${table.locatorPrefix}) <= 120) and (${table.locatorSuffix} is null or char_length(${table.locatorSuffix}) <= 120)`),
    sourceTextBound: check("ai_extraction_result_groundings_source_text_bound", sql`char_length(${table.sourceText}) <= 4000`),
  }),
);

export const aiExtractionDecisions = pgTable(
  "ai_extraction_decisions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    decision: text("decision").notNull(),
    acceptanceMode: text("acceptance_mode"),
    expectedCurrentExtractionRevisionId: uuid("expected_current_extraction_revision_id"),
    precedingExtractionRevisionId: uuid("preceding_extraction_revision_id"),
    resultingExtractionRevisionId: uuid("resulting_extraction_revision_id"),
    valueState: text("value_state"),
    textValue: text("text_value"),
    numberValue: numeric("number_value", { precision: 30, scale: 10 }),
    booleanValue: boolean("boolean_value"),
    optionId: uuid("option_id"),
    researcherNote: text("researcher_note"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_decisions_project_id_id_unique").on(table.projectId, table.id),
    requestUnique: unique("ai_extraction_decisions_project_request_unique").on(table.projectId, table.requestId),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiExtractionRequests.projectId, aiExtractionRequests.id], name: "ai_extraction_decisions_request_fk" }).onDelete("restrict"),
    expectedRevisionOwnership: foreignKey({ columns: [table.projectId, table.expectedCurrentExtractionRevisionId], foreignColumns: [extractionValueRevisions.projectId, extractionValueRevisions.id], name: "ai_extraction_decisions_expected_revision_fk" }).onDelete("restrict"),
    precedingRevisionOwnership: foreignKey({ columns: [table.projectId, table.precedingExtractionRevisionId], foreignColumns: [extractionValueRevisions.projectId, extractionValueRevisions.id], name: "ai_extraction_decisions_preceding_revision_fk" }).onDelete("restrict"),
    resultingRevisionOwnership: foreignKey({ columns: [table.projectId, table.resultingExtractionRevisionId], foreignColumns: [extractionValueRevisions.projectId, extractionValueRevisions.id], name: "ai_extraction_decisions_resulting_revision_fk" }).onDelete("restrict"),
    optionOwnership: foreignKey({ columns: [table.projectId, table.optionId], foreignColumns: [extractionOptions.projectId, extractionOptions.id], name: "ai_extraction_decisions_option_fk" }).onDelete("restrict"),
    decisionValid: check("ai_extraction_decisions_decision_valid", sql`${table.decision} in ('accepted', 'rejected')`),
    acceptanceModeValid: check("ai_extraction_decisions_acceptance_mode_valid", sql`${table.acceptanceMode} is null or ${table.acceptanceMode} in ('accept', 'edit_and_accept')`),
    stateValid: check("ai_extraction_decisions_state_valid", sql`${table.valueState} is null or ${table.valueState} in ('present', 'not_reported', 'not_applicable', 'cleared')`),
    decisionShape: check("ai_extraction_decisions_decision_shape", sql`(
      (${table.decision} = 'rejected' and ${table.acceptanceMode} is null and ${table.resultingExtractionRevisionId} is null and ${table.valueState} is null and ${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is null)
      or (${table.decision} = 'accepted' and ${table.acceptanceMode} is not null and ${table.resultingExtractionRevisionId} is not null and ${table.valueState} is not null)
    )`),
    noteBound: check("ai_extraction_decisions_note_bound", sql`${table.researcherNote} is null or (btrim(${table.researcherNote}) <> '' and char_length(${table.researcherNote}) <= 20000)`),
  }),
);

export const aiExtractionDecisionEvidence = pgTable(
  "ai_extraction_decision_evidence",
  {
    projectId: uuid("project_id").notNull(),
    decisionId: uuid("decision_id").notNull(),
    groundingId: uuid("grounding_id").notNull(),
    evidenceId: uuid("evidence_id").notNull(),
    evidenceMode: text("evidence_mode").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    identity: primaryKey({ columns: [table.projectId, table.decisionId, table.groundingId] }),
    evidenceIdentity: unique("ai_extraction_decision_evidence_project_decision_evidence_unique").on(table.projectId, table.decisionId, table.evidenceId),
    decisionOwnership: foreignKey({ columns: [table.projectId, table.decisionId], foreignColumns: [aiExtractionDecisions.projectId, aiExtractionDecisions.id], name: "ai_extraction_decision_evidence_decision_fk" }).onDelete("restrict"),
    groundingOwnership: foreignKey({ columns: [table.projectId, table.groundingId], foreignColumns: [aiExtractionResultGroundings.projectId, aiExtractionResultGroundings.id], name: "ai_extraction_decision_evidence_grounding_fk" }).onDelete("restrict"),
    evidenceOwnership: foreignKey({ columns: [table.projectId, table.evidenceId], foreignColumns: [evidence.projectId, evidence.id], name: "ai_extraction_decision_evidence_evidence_fk" }).onDelete("restrict"),
    modeValid: check("ai_extraction_decision_evidence_mode_valid", sql`${table.evidenceMode} in ('fresh', 'reused')`),
  }),
);

export const aiExtractionBatches = pgTable(
  "ai_extraction_batches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    provider: text("provider").notNull().default("openai"),
    configuredModel: text("configured_model").notNull(),
    configuredReasoningEffort: text("configured_reasoning_effort").notNull().default("low"),
    selectionPolicyVersion: text("selection_policy_version").notNull(),
    batchDisclosureVersion: text("batch_disclosure_version").notNull(),
    requestDisclosureVersion: text("request_disclosure_version").notNull(),
    externalTransmissionAcknowledged: boolean("external_transmission_acknowledged").notNull(),
    paperCount: integer("paper_count").notNull(),
    fieldCount: integer("field_count").notNull(),
    cellCount: integer("cell_count").notNull(),
    executableCount: integer("executable_count").notNull(),
    manifestAlgorithmVersion: text("manifest_algorithm_version").notNull(),
    manifestSha256: text("manifest_sha256").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_batches_project_id_id_unique").on(table.projectId, table.id),
    projectCreatedAt: index("ai_extraction_batches_project_created_at_idx").on(table.projectId, table.createdAt),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "ai_extraction_batches_project_fk" }).onDelete("restrict"),
    providerValid: check("ai_extraction_batches_provider_valid", sql`${table.provider} = 'openai'`),
    modelShape: check("ai_extraction_batches_model_shape", sql`btrim(${table.configuredModel}) <> '' and char_length(${table.configuredModel}) <= 200`),
    reasoningValid: check("ai_extraction_batches_reasoning_valid", sql`${table.configuredReasoningEffort} = 'low'`),
    versionShape: check("ai_extraction_batches_version_shape", sql`btrim(${table.selectionPolicyVersion}) <> '' and btrim(${table.batchDisclosureVersion}) <> '' and btrim(${table.requestDisclosureVersion}) <> '' and btrim(${table.manifestAlgorithmVersion}) <> ''`),
    acknowledgement: check("ai_extraction_batches_transmission_acknowledged", sql`${table.externalTransmissionAcknowledged} = true`),
    countBounds: check("ai_extraction_batches_count_bounds", sql`${table.paperCount} >= 1 and ${table.paperCount} <= 100 and ${table.fieldCount} >= 1 and ${table.fieldCount} <= 25 and ${table.cellCount} >= 1 and ${table.cellCount} <= 500 and ${table.executableCount} >= 0 and ${table.executableCount} <= ${table.cellCount}`),
    hashShape: check("ai_extraction_batches_manifest_hash_shape", sql`${table.manifestSha256} ~ '^[0-9a-f]{64}$'`),
  }),
);

export const aiExtractionBatchItems = pgTable(
  "ai_extraction_batch_items",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    batchId: uuid("batch_id").notNull(),
    itemOrdinal: integer("item_ordinal").notNull(),
    paperId: uuid("paper_id").notNull(),
    extractionFieldId: uuid("extraction_field_id").notNull(),
    expectedCurrentExtractionRevisionId: uuid("expected_current_extraction_revision_id"),
    titleAbstractDecisionId: uuid("title_abstract_decision_id"),
    fullTextDecisionId: uuid("full_text_decision_id"),
    fullTextDocumentId: uuid("full_text_document_id"),
    documentTextExtractionId: uuid("document_text_extraction_id"),
    initialDisposition: text("initial_disposition").notNull(),
    initialReasonCode: text("initial_reason_code").notNull(),
    idempotencyKey: uuid("idempotency_key").notNull(),
    expectedRequestIntentHash: text("expected_request_intent_hash"),
    fieldDefinitionHash: text("field_definition_hash").notNull(),
    optionSnapshotHash: text("option_snapshot_hash").notNull(),
    paperTitleSnapshot: text("paper_title_snapshot").notNull(),
    paperAbstractSnapshot: text("paper_abstract_snapshot"),
    fieldNameSnapshot: text("field_name_snapshot").notNull(),
    fieldDescriptionSnapshot: text("field_description_snapshot"),
    fieldTypeSnapshot: text("field_type_snapshot").notNull(),
    fieldRequiredSnapshot: boolean("field_required_snapshot").notNull(),
    fieldOptionSnapshot: jsonb("field_option_snapshot").notNull().default([]),
    documentFilenameSnapshot: text("document_filename_snapshot"),
    extractionSequenceSnapshot: bigint("extraction_sequence_snapshot", { mode: "number" }),
    extractionStatusSnapshot: text("extraction_status_snapshot"),
    pageManifest: jsonb("page_manifest").notNull().default([]),
    pageManifestHash: text("page_manifest_hash").notNull(),
    pageCount: integer("page_count").notNull(),
    sourceCharacterCount: integer("source_character_count").notNull(),
    sourceByteSize: integer("source_byte_size").notNull(),
    itemManifestHash: text("item_manifest_hash").notNull(),
    aiExtractionRequestId: uuid("ai_extraction_request_id"),
    requestRelationship: text("request_relationship"),
    orchestrationTerminalCode: text("orchestration_terminal_code"),
    orchestrationTerminalDetail: text("orchestration_terminal_detail"),
    orchestrationFinalizedAt: timestamp("orchestration_finalized_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_extraction_batch_items_project_id_id_unique").on(table.projectId, table.id),
    batchOrdinal: unique("ai_extraction_batch_items_project_batch_ordinal_unique").on(table.projectId, table.batchId, table.itemOrdinal),
    batchPaperField: unique("ai_extraction_batch_items_project_batch_paper_field_unique").on(table.projectId, table.batchId, table.paperId, table.extractionFieldId),
    batchIdempotency: unique("ai_extraction_batch_items_project_batch_idempotency_unique").on(table.projectId, table.batchId, table.idempotencyKey),
    batchOrder: index("ai_extraction_batch_items_project_batch_ordinal_idx").on(table.projectId, table.batchId, table.itemOrdinal),
    paperOrder: index("ai_extraction_batch_items_project_paper_idx").on(table.projectId, table.paperId, table.itemOrdinal),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "ai_extraction_batch_items_project_fk" }).onDelete("restrict"),
    batchOwnership: foreignKey({ columns: [table.projectId, table.batchId], foreignColumns: [aiExtractionBatches.projectId, aiExtractionBatches.id], name: "ai_extraction_batch_items_batch_fk" }).onDelete("restrict"),
    paperOwnership: foreignKey({ columns: [table.projectId, table.paperId], foreignColumns: [papers.projectId, papers.id], name: "ai_extraction_batch_items_paper_fk" }).onDelete("restrict"),
    fieldOwnership: foreignKey({ columns: [table.projectId, table.extractionFieldId], foreignColumns: [extractionFields.projectId, extractionFields.id], name: "ai_extraction_batch_items_field_fk" }).onDelete("restrict"),
    documentOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.fullTextDocumentId], foreignColumns: [fullTextDocuments.projectId, fullTextDocuments.paperId, fullTextDocuments.id], name: "ai_extraction_batch_items_document_fk" }).onDelete("restrict"),
    extractionOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.documentTextExtractionId], foreignColumns: [documentTextExtractions.projectId, documentTextExtractions.paperId, documentTextExtractions.id], name: "ai_extraction_batch_items_extraction_fk" }).onDelete("restrict"),
    baselineRevisionOwnership: foreignKey({ columns: [table.projectId, table.expectedCurrentExtractionRevisionId], foreignColumns: [extractionValueRevisions.projectId, extractionValueRevisions.id], name: "ai_extraction_batch_items_baseline_revision_fk" }).onDelete("restrict"),
    requestOwnership: foreignKey({ columns: [table.projectId, table.aiExtractionRequestId], foreignColumns: [aiExtractionRequests.projectId, aiExtractionRequests.id], name: "ai_extraction_batch_items_request_fk" }).onDelete("restrict"),
    ordinalValid: check("ai_extraction_batch_items_ordinal_valid", sql`${table.itemOrdinal} >= 0 and ${table.itemOrdinal} < 500`),
    dispositionValid: check("ai_extraction_batch_items_disposition_valid", sql`${table.initialDisposition} in ('executable', 'reusable', 'blocked', 'ineligible')`),
    reasonShape: check("ai_extraction_batch_items_reason_shape", sql`btrim(${table.initialReasonCode}) <> '' and char_length(${table.initialReasonCode}) <= 100`),
    fieldTypeValid: check("ai_extraction_batch_items_field_type_valid", sql`${table.fieldTypeSnapshot} in ('short_text', 'long_text', 'number', 'boolean', 'single_select')`),
    titleAbstractDecisionOwnership: foreignKey({ columns: [table.projectId, table.titleAbstractDecisionId], foreignColumns: [screeningDecisions.projectId, screeningDecisions.id], name: "ai_extraction_batch_items_title_abstract_decision_fk" }).onDelete("restrict"),
    fullTextDecisionOwnership: foreignKey({ columns: [table.projectId, table.fullTextDecisionId], foreignColumns: [fullTextScreeningDecisions.projectId, fullTextScreeningDecisions.id], name: "ai_extraction_batch_items_full_text_decision_fk" }).onDelete("restrict"),
    hashShape: check("ai_extraction_batch_items_hash_shape", sql`${table.fieldDefinitionHash} ~ '^[0-9a-f]{64}$' and ${table.optionSnapshotHash} ~ '^[0-9a-f]{64}$' and ${table.pageManifestHash} ~ '^[0-9a-f]{64}$' and ${table.itemManifestHash} ~ '^[0-9a-f]{64}$' and (${table.expectedRequestIntentHash} is null or ${table.expectedRequestIntentHash} ~ '^[0-9a-f]{64}$')`),
    manifestArray: check("ai_extraction_batch_items_page_manifest_array", sql`jsonb_typeof(${table.pageManifest}) = 'array'`),
    pageCountBounds: check("ai_extraction_batch_items_page_count_bounds", sql`${table.pageCount} >= 0 and ${table.pageCount} <= 40`),
    sourceCountBounds: check("ai_extraction_batch_items_source_count_bounds", sql`${table.sourceCharacterCount} >= 0 and ${table.sourceCharacterCount} <= 80000 and ${table.sourceByteSize} >= 0 and ${table.sourceByteSize} <= 327680`),
    sourceIdentityShape: check("ai_extraction_batch_items_source_identity_shape", sql`(
      (${table.initialDisposition} in ('executable', 'reusable') and ${table.fullTextDocumentId} is not null and ${table.documentTextExtractionId} is not null and ${table.extractionSequenceSnapshot} is not null and ${table.extractionStatusSnapshot} is not null and ${table.pageCount} > 0 and ${table.sourceCharacterCount} > 0 and ${table.sourceByteSize} > 0)
      or ${table.initialDisposition} in ('blocked', 'ineligible')
    )`),
    requestRelationshipValid: check("ai_extraction_batch_items_request_relationship_valid", sql`${table.requestRelationship} is null or ${table.requestRelationship} in ('authoritative', 'blocking')`),
    requestLinkShape: check("ai_extraction_batch_items_request_link_shape", sql`(${table.aiExtractionRequestId} is null and ${table.requestRelationship} is null) or (${table.aiExtractionRequestId} is not null and ${table.requestRelationship} is not null)`),
    terminalShape: check("ai_extraction_batch_items_terminal_shape", sql`(${table.orchestrationTerminalCode} is null and ${table.orchestrationFinalizedAt} is null) or (${table.orchestrationTerminalCode} is not null and ${table.orchestrationFinalizedAt} is not null)`),
  }),
);
