import {
  integer,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  foreignKey,
  primaryKey,
  check,
  boolean,
  numeric,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { projects, papers } from "./foundation";
import { evidence } from "./documents-evidence";
import { evidenceSets, evidenceSetMemberships, evidenceSetCompositionRevisions } from "./evidence-sets";
import { extractionFields, extractionOptions, extractionValues, extractionValueRevisions } from "./extraction";
import { synthesisStatements, synthesisRevisions, synthesisPreparations } from "./synthesis";

export const aiSynthesisRequests = pgTable(
  "ai_synthesis_requests",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    projectTitleSnapshot: text("project_title_snapshot").notNull(),
    preparationId: uuid("preparation_id").notNull(),
    evidenceSetId: uuid("evidence_set_id").notNull(),
    evidenceSetCompositionRevisionId: uuid("evidence_set_composition_revision_id").notNull(),
    extractionFieldId: uuid("extraction_field_id").notNull(),
    targetSynthesisStatementId: uuid("target_synthesis_statement_id"),
    targetBaselineSynthesisRevisionId: uuid("target_baseline_synthesis_revision_id"),
    targetTitleSnapshot: text("target_title_snapshot"),
    targetStatementTextSnapshot: text("target_statement_text_snapshot"),
    idempotencyKey: uuid("idempotency_key").notNull(),
    sourceStateHash: text("source_state_hash").notNull(),
    intentHash: text("intent_hash").notNull(),
    fieldNameSnapshot: text("field_name_snapshot").notNull(),
    fieldDescriptionSnapshot: text("field_description_snapshot"),
    fieldType: text("field_type").notNull(),
    provider: text("provider").notNull(),
    configuredModel: text("configured_model").notNull(),
    configuredReasoningEffort: text("configured_reasoning_effort").notNull(),
    promptVersion: text("prompt_version").notNull(),
    responseSchemaVersion: text("response_schema_version").notNull(),
    groundingResolverVersion: text("grounding_resolver_version").notNull(),
    contextSelectionVersion: text("context_selection_version").notNull(),
    sourceCoverageState: text("source_coverage_state").notNull().default("complete"),
    supportCount: integer("support_count").notNull(),
    sourceCount: integer("source_count").notNull(),
    sourceCharacterCount: integer("source_character_count").notNull(),
    sourceByteSize: integer("source_byte_size").notNull(),
    sourceManifestHash: text("source_manifest_hash").notNull(),
    externalTransmissionAcknowledged: boolean("external_transmission_acknowledged").notNull(),
    disclosureVersion: text("disclosure_version").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    undispatchedExpiresAt: timestamp("undispatched_expires_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_synthesis_requests_project_id_id_unique").on(table.projectId, table.id),
    projectIdempotency: unique("ai_synthesis_requests_project_idempotency_key_unique").on(table.projectId, table.idempotencyKey),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "ai_synthesis_requests_project_fk" }).onDelete("restrict"),
    preparationOwnership: foreignKey({ columns: [table.projectId, table.preparationId], foreignColumns: [synthesisPreparations.projectId, synthesisPreparations.id], name: "ai_synthesis_requests_preparation_fk" }).onDelete("restrict"),
    evidenceSetOwnership: foreignKey({ columns: [table.projectId, table.evidenceSetId], foreignColumns: [evidenceSets.projectId, evidenceSets.id], name: "ai_synthesis_requests_evidence_set_fk" }).onDelete("restrict"),
    compositionOwnership: foreignKey({ columns: [table.projectId, table.evidenceSetId, table.evidenceSetCompositionRevisionId], foreignColumns: [evidenceSetCompositionRevisions.projectId, evidenceSetCompositionRevisions.evidenceSetId, evidenceSetCompositionRevisions.id], name: "ai_synthesis_requests_composition_revision_fk" }).onDelete("restrict"),
    fieldOwnership: foreignKey({ columns: [table.projectId, table.extractionFieldId], foreignColumns: [extractionFields.projectId, extractionFields.id], name: "ai_synthesis_requests_field_fk" }).onDelete("restrict"),
    targetStatementOwnership: foreignKey({ columns: [table.projectId, table.targetSynthesisStatementId], foreignColumns: [synthesisStatements.projectId, synthesisStatements.id], name: "ai_synthesis_requests_target_statement_fk" }).onDelete("restrict"),
    targetBaselineOwnership: foreignKey({ columns: [table.projectId, table.targetSynthesisStatementId, table.targetBaselineSynthesisRevisionId], foreignColumns: [synthesisRevisions.projectId, synthesisRevisions.synthesisStatementId, synthesisRevisions.id], name: "ai_synthesis_requests_target_baseline_fk" }).onDelete("restrict"),
    fieldTypeValid: check("ai_synthesis_requests_field_type_valid", sql`${table.fieldType} in ('short_text', 'long_text', 'number', 'boolean', 'single_select')`),
    sourceCoverageValid: check("ai_synthesis_requests_source_coverage_valid", sql`${table.sourceCoverageState} = 'complete'`),
    countBounds: check("ai_synthesis_requests_count_bounds", sql`${table.supportCount} >= 1 and ${table.supportCount} <= 20 and ${table.sourceCount} >= 1 and ${table.sourceCount} <= 80`),
    sourceBounds: check("ai_synthesis_requests_source_bounds", sql`${table.sourceCharacterCount} >= 1 and ${table.sourceCharacterCount} <= 80000 and ${table.sourceByteSize} >= 1 and ${table.sourceByteSize} <= 327680`),
    hashShape: check("ai_synthesis_requests_hash_shape", sql`${table.sourceStateHash} ~ '^[0-9a-f]{64}$' and ${table.intentHash} ~ '^[0-9a-f]{64}$' and ${table.sourceManifestHash} ~ '^[0-9a-f]{64}$'`),
    textBounds: check("ai_synthesis_requests_text_bounds", sql`char_length(${table.projectTitleSnapshot}) between 1 and 500 and char_length(${table.fieldNameSnapshot}) between 1 and 500 and (${table.fieldDescriptionSnapshot} is null or char_length(${table.fieldDescriptionSnapshot}) <= 2000) and (${table.targetTitleSnapshot} is null or char_length(${table.targetTitleSnapshot}) <= 500) and (${table.targetStatementTextSnapshot} is null or char_length(${table.targetStatementTextSnapshot}) <= 10000)`),
    nonblankConfig: check("ai_synthesis_requests_config_nonblank", sql`btrim(${table.provider}) <> '' and char_length(${table.provider}) <= 100 and btrim(${table.configuredModel}) <> '' and char_length(${table.configuredModel}) <= 200 and btrim(${table.configuredReasoningEffort}) <> ''`),
    versionsShape: check("ai_synthesis_requests_versions_shape", sql`btrim(${table.promptVersion}) <> '' and char_length(${table.promptVersion}) <= 100 and btrim(${table.responseSchemaVersion}) <> '' and char_length(${table.responseSchemaVersion}) <= 100 and btrim(${table.groundingResolverVersion}) <> '' and char_length(${table.groundingResolverVersion}) <= 100 and btrim(${table.contextSelectionVersion}) <> '' and char_length(${table.contextSelectionVersion}) <= 100 and btrim(${table.disclosureVersion}) <> '' and char_length(${table.disclosureVersion}) <= 100`),
    acknowledged: check("ai_synthesis_requests_transmission_acknowledged", sql`${table.externalTransmissionAcknowledged} = true`),
    expiryFuture: check("ai_synthesis_requests_undispatched_expiry_order", sql`${table.undispatchedExpiresAt} >= ${table.createdAt}`),
  }),
);

export const aiSynthesisRequestSupports = pgTable(
  "ai_synthesis_request_supports",
  {
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    extractionRevisionId: uuid("extraction_revision_id").notNull(),
    supportOrdinal: integer("support_ordinal").notNull(),
    paperId: uuid("paper_id").notNull(),
    extractionFieldId: uuid("extraction_field_id").notNull(),
    extractionValueId: uuid("extraction_value_id").notNull(),
    fieldType: text("field_type").notNull(),
    valueState: text("value_state").notNull(),
    textValue: text("text_value"),
    numberValue: numeric("number_value", { precision: 30, scale: 10 }),
    booleanValue: boolean("boolean_value"),
    optionId: uuid("option_id"),
    optionLabelSnapshot: text("option_label_snapshot"),
    researcherNote: text("researcher_note"),
    paperTitleSnapshot: text("paper_title_snapshot").notNull(),
    paperPublicationYearSnapshot: integer("paper_publication_year_snapshot"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    identity: primaryKey({ columns: [table.projectId, table.requestId, table.extractionRevisionId] }),
    requestSupportIdentity: unique("ai_synthesis_request_supports_project_request_ordinal_unique").on(table.projectId, table.requestId, table.supportOrdinal),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiSynthesisRequests.projectId, aiSynthesisRequests.id], name: "ai_synthesis_request_supports_request_fk" }).onDelete("restrict"),
    revisionOwnership: foreignKey({ columns: [table.projectId, table.extractionRevisionId], foreignColumns: [extractionValueRevisions.projectId, extractionValueRevisions.id], name: "ai_synthesis_request_supports_revision_fk" }).onDelete("restrict"),
    paperOwnership: foreignKey({ columns: [table.projectId, table.paperId], foreignColumns: [papers.projectId, papers.id], name: "ai_synthesis_request_supports_paper_fk" }).onDelete("restrict"),
    fieldOwnership: foreignKey({ columns: [table.projectId, table.extractionFieldId], foreignColumns: [extractionFields.projectId, extractionFields.id], name: "ai_synthesis_request_supports_field_fk" }).onDelete("restrict"),
    valueOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.extractionValueId, table.extractionFieldId], foreignColumns: [extractionValues.projectId, extractionValues.paperId, extractionValues.id, extractionValues.fieldId], name: "ai_synthesis_request_supports_value_fk" }).onDelete("restrict"),
    optionOwnership: foreignKey({ columns: [table.projectId, table.extractionFieldId, table.optionId], foreignColumns: [extractionOptions.projectId, extractionOptions.fieldId, extractionOptions.id], name: "ai_synthesis_request_supports_option_fk" }).onDelete("restrict"),
    fieldTypeValid: check("ai_synthesis_request_supports_field_type_valid", sql`${table.fieldType} in ('short_text', 'long_text', 'number', 'boolean', 'single_select')`),
    stateValid: check("ai_synthesis_request_supports_value_state_valid", sql`${table.valueState} in ('present', 'not_reported', 'not_applicable', 'cleared')`),
    valueShape: check("ai_synthesis_request_supports_value_shape", sql`(
      (${table.valueState} <> 'present' and ${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is null and ${table.optionLabelSnapshot} is null)
      or (${table.valueState} = 'present' and (
        (${table.fieldType} in ('short_text', 'long_text') and ${table.textValue} is not null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is null and ${table.optionLabelSnapshot} is null)
        or (${table.fieldType} = 'number' and ${table.textValue} is null and ${table.numberValue} is not null and ${table.booleanValue} is null and ${table.optionId} is null and ${table.optionLabelSnapshot} is null)
        or (${table.fieldType} = 'boolean' and ${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is not null and ${table.optionId} is null and ${table.optionLabelSnapshot} is null)
        or (${table.fieldType} = 'single_select' and ${table.textValue} is null and ${table.numberValue} is null and ${table.booleanValue} is null and ${table.optionId} is not null and ${table.optionLabelSnapshot} is not null)
      ))
    )`),
    ordinalValid: check("ai_synthesis_request_supports_ordinal_valid", sql`${table.supportOrdinal} >= 0 and ${table.supportOrdinal} < 20`),
    noteBound: check("ai_synthesis_request_supports_note_bound", sql`${table.researcherNote} is null or char_length(${table.researcherNote}) <= 10000`),
    paperTitleBound: check("ai_synthesis_request_supports_paper_title_bound", sql`char_length(${table.paperTitleSnapshot}) between 1 and 1000`),
    publicationYearValid: check("ai_synthesis_request_supports_publication_year_valid", sql`${table.paperPublicationYearSnapshot} is null or (${table.paperPublicationYearSnapshot} between 1000 and 3000)`),
  }),
);

export const aiSynthesisRequestSources = pgTable(
  "ai_synthesis_request_sources",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    extractionRevisionId: uuid("extraction_revision_id").notNull(),
    evidenceId: uuid("evidence_id").notNull(),
    paperId: uuid("paper_id").notNull(),
    sourceOrdinal: integer("source_ordinal").notNull(),
    membershipId: uuid("membership_id").notNull(),
    membershipSortOrder: integer("membership_sort_order").notNull(),
    pageNumber: integer("page_number").notNull(),
    sourceText: text("source_text").notNull(),
    sourceTextSha256: text("source_text_sha256").notNull(),
    sourceCharacterCount: integer("source_character_count").notNull(),
    sourceByteSize: integer("source_byte_size").notNull(),
    evidenceReviewState: text("evidence_review_state").notNull(),
    evidenceNoteSnapshot: text("evidence_note_snapshot"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_synthesis_request_sources_project_id_id_unique").on(table.projectId, table.id),
    sourceIdentity: unique("ai_synthesis_request_sources_project_request_revision_evidence_unique").on(table.projectId, table.requestId, table.extractionRevisionId, table.evidenceId),
    sourceOrder: unique("ai_synthesis_request_sources_project_request_revision_ordinal_unique").on(table.projectId, table.requestId, table.extractionRevisionId, table.sourceOrdinal),
    requestSupportOwnership: foreignKey({ columns: [table.projectId, table.requestId, table.extractionRevisionId], foreignColumns: [aiSynthesisRequestSupports.projectId, aiSynthesisRequestSupports.requestId, aiSynthesisRequestSupports.extractionRevisionId], name: "ai_synthesis_request_sources_support_fk" }).onDelete("restrict"),
    evidenceOwnership: foreignKey({ columns: [table.projectId, table.paperId, table.evidenceId], foreignColumns: [evidence.projectId, evidence.paperId, evidence.id], name: "ai_synthesis_request_sources_evidence_fk" }).onDelete("restrict"),
    membershipOwnership: foreignKey({ columns: [table.projectId, table.membershipId], foreignColumns: [evidenceSetMemberships.projectId, evidenceSetMemberships.id], name: "ai_synthesis_request_sources_membership_fk" }).onDelete("restrict"),
    sourceOrdinalValid: check("ai_synthesis_request_sources_ordinal_valid", sql`${table.sourceOrdinal} >= 0 and ${table.sourceOrdinal} < 8`),
    membershipOrderValid: check("ai_synthesis_request_sources_membership_order_valid", sql`${table.membershipSortOrder} > 0`),
    pagePositive: check("ai_synthesis_request_sources_page_positive", sql`${table.pageNumber} > 0`),
    sourceTextBound: check("ai_synthesis_request_sources_text_bound", sql`btrim(${table.sourceText}) <> '' and char_length(${table.sourceText}) <= 4000`),
    sourceHashShape: check("ai_synthesis_request_sources_hash_shape", sql`${table.sourceTextSha256} ~ '^[0-9a-f]{64}$'`),
    sourceCountShape: check("ai_synthesis_request_sources_count_shape", sql`${table.sourceCharacterCount} = char_length(${table.sourceText}) and ${table.sourceCharacterCount} > 0 and ${table.sourceCharacterCount} <= 4000 and ${table.sourceByteSize} > 0 and ${table.sourceByteSize} <= 163840`),
    reviewStateValid: check("ai_synthesis_request_sources_review_state_valid", sql`${table.evidenceReviewState} in ('unreviewed', 'needs_review', 'accepted', 'rejected')`),
    noteBound: check("ai_synthesis_request_sources_note_bound", sql`${table.evidenceNoteSnapshot} is null or char_length(${table.evidenceNoteSnapshot}) <= 2000`),
  }),
);

export const aiSynthesisDispatches = pgTable(
  "ai_synthesis_dispatches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    deadlineAt: timestamp("deadline_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_synthesis_dispatches_project_id_id_unique").on(table.projectId, table.id),
    requestUnique: unique("ai_synthesis_dispatches_project_request_unique").on(table.projectId, table.requestId),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiSynthesisRequests.projectId, aiSynthesisRequests.id], name: "ai_synthesis_dispatches_request_fk" }).onDelete("restrict"),
    deadlineOrder: check("ai_synthesis_dispatches_deadline_order", sql`${table.deadlineAt} > ${table.startedAt}`),
  }),
);

export const aiSynthesisResults = pgTable(
  "ai_synthesis_results",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    outcome: text("outcome").notNull(),
    providerDiagnostic: text("provider_diagnostic").notNull(),
    errorCode: text("error_code"),
    candidateState: text("candidate_state"),
    proposedTitle: text("proposed_title"),
    proposedStatementText: text("proposed_statement_text"),
    explanation: text("explanation"),
    sourceCoverageState: text("source_coverage_state").notNull().default("complete"),
    coveredSupportCount: integer("covered_support_count").notNull().default(0),
    groundingCount: integer("grounding_count").notNull().default(0),
    providerRequestId: text("provider_request_id"),
    configuredModel: text("configured_model").notNull(),
    returnedModel: text("returned_model"),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    durationMs: integer("duration_ms"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_synthesis_results_project_id_id_unique").on(table.projectId, table.id),
    requestUnique: unique("ai_synthesis_results_project_request_unique").on(table.projectId, table.requestId),
    requestIdentity: unique("ai_synthesis_results_project_request_id_unique").on(table.projectId, table.requestId, table.id),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiSynthesisRequests.projectId, aiSynthesisRequests.id], name: "ai_synthesis_results_request_fk" }).onDelete("restrict"),
    outcomeValid: check("ai_synthesis_results_outcome_valid", sql`${table.outcome} in ('succeeded', 'no_candidate', 'provider_unavailable', 'failed', 'invalid_output', 'unresolvable_grounding', 'outcome_unknown')`),
    diagnosticValid: check("ai_synthesis_results_provider_diagnostic_valid", sql`${table.providerDiagnostic} in ('success', 'refusal', 'incomplete', 'schema_invalid', 'transport_error', 'api_error', 'unknown')`),
    candidateStateValid: check("ai_synthesis_results_candidate_state_valid", sql`${table.candidateState} is null or ${table.candidateState} in ('present', 'not_present')`),
    coverageValid: check("ai_synthesis_results_source_coverage_valid", sql`${table.sourceCoverageState} in ('complete', 'partial', 'not_applicable')`),
    resultShape: check("ai_synthesis_results_result_shape", sql`(
      (${table.outcome} = 'succeeded' and ${table.candidateState} = 'present' and ${table.proposedStatementText} is not null and btrim(${table.proposedStatementText}) <> '' and ${table.errorCode} is null)
      or (${table.outcome} = 'no_candidate' and ${table.candidateState} = 'not_present' and ${table.proposedTitle} is null and ${table.proposedStatementText} is null and ${table.groundingCount} = 0)
      or (${table.outcome} not in ('succeeded', 'no_candidate') and ${table.candidateState} is null and ${table.proposedTitle} is null and ${table.proposedStatementText} is null)
    )`),
    titleBound: check("ai_synthesis_results_title_bound", sql`${table.proposedTitle} is null or (btrim(${table.proposedTitle}) <> '' and char_length(${table.proposedTitle}) <= 500)`),
    statementBound: check("ai_synthesis_results_statement_bound", sql`${table.proposedStatementText} is null or char_length(${table.proposedStatementText}) <= 10000`),
    explanationBound: check("ai_synthesis_results_explanation_bound", sql`${table.explanation} is null or char_length(${table.explanation}) <= 2000`),
    errorBound: check("ai_synthesis_results_error_bound", sql`${table.errorCode} is null or (btrim(${table.errorCode}) <> '' and char_length(${table.errorCode}) <= 80)`),
    metadataBound: check("ai_synthesis_results_metadata_bound", sql`${table.providerRequestId} is null or (btrim(${table.providerRequestId}) <> '' and char_length(${table.providerRequestId}) <= 200)`),
    countsValid: check("ai_synthesis_results_counts_valid", sql`${table.coveredSupportCount} >= 0 and ${table.groundingCount} >= 0 and (${table.inputTokens} is null or ${table.inputTokens} >= 0) and (${table.outputTokens} is null or ${table.outputTokens} >= 0) and (${table.durationMs} is null or ${table.durationMs} >= 0)`),
  }),
);

export const aiSynthesisResultGroundings = pgTable(
  "ai_synthesis_result_groundings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    resultId: uuid("result_id").notNull(),
    extractionRevisionId: uuid("extraction_revision_id").notNull(),
    evidenceId: uuid("evidence_id").notNull(),
    pageNumber: integer("page_number").notNull(),
    startOffset: integer("start_offset").notNull(),
    endOffset: integer("end_offset").notNull(),
    locatorQuote: text("locator_quote").notNull(),
    locatorPrefix: text("locator_prefix"),
    locatorSuffix: text("locator_suffix"),
    sourceText: text("source_text").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_synthesis_result_groundings_project_id_id_unique").on(table.projectId, table.id),
    groundingIdentity: unique("ai_synthesis_result_groundings_result_source_offset_unique").on(table.projectId, table.resultId, table.extractionRevisionId, table.evidenceId, table.startOffset, table.endOffset),
    requestResultOwnership: foreignKey({ columns: [table.projectId, table.requestId, table.resultId], foreignColumns: [aiSynthesisResults.projectId, aiSynthesisResults.requestId, aiSynthesisResults.id], name: "ai_synthesis_result_groundings_result_fk" }).onDelete("restrict"),
    sourceOwnership: foreignKey({ columns: [table.projectId, table.requestId, table.extractionRevisionId, table.evidenceId], foreignColumns: [aiSynthesisRequestSources.projectId, aiSynthesisRequestSources.requestId, aiSynthesisRequestSources.extractionRevisionId, aiSynthesisRequestSources.evidenceId], name: "ai_synthesis_result_groundings_source_fk" }).onDelete("restrict"),
    pagePositive: check("ai_synthesis_result_groundings_page_positive", sql`${table.pageNumber} > 0`),
    offsetShape: check("ai_synthesis_result_groundings_offset_shape", sql`${table.startOffset} >= 0 and ${table.endOffset} > ${table.startOffset} and ${table.endOffset} - ${table.startOffset} <= 500`),
    quoteBound: check("ai_synthesis_result_groundings_quote_bound", sql`btrim(${table.locatorQuote}) <> '' and char_length(${table.locatorQuote}) <= 500`),
    contextBound: check("ai_synthesis_result_groundings_context_bound", sql`(${table.locatorPrefix} is null or char_length(${table.locatorPrefix}) <= 120) and (${table.locatorSuffix} is null or char_length(${table.locatorSuffix}) <= 120)`),
    sourceTextBound: check("ai_synthesis_result_groundings_source_text_bound", sql`char_length(${table.sourceText}) > 0 and char_length(${table.sourceText}) <= 4000`),
  }),
);

export const aiSynthesisDecisions = pgTable(
  "ai_synthesis_decisions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    decision: text("decision").notNull(),
    acceptanceMode: text("acceptance_mode"),
    expectedCurrentTargetRevisionId: uuid("expected_current_target_revision_id"),
    resultingSynthesisRevisionId: uuid("resulting_synthesis_revision_id"),
    title: text("title"),
    statementText: text("statement_text"),
    researcherNote: text("researcher_note"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("ai_synthesis_decisions_project_id_id_unique").on(table.projectId, table.id),
    requestUnique: unique("ai_synthesis_decisions_project_request_unique").on(table.projectId, table.requestId),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [aiSynthesisRequests.projectId, aiSynthesisRequests.id], name: "ai_synthesis_decisions_request_fk" }).onDelete("restrict"),
    expectedRevisionOwnership: foreignKey({ columns: [table.projectId, table.expectedCurrentTargetRevisionId], foreignColumns: [synthesisRevisions.projectId, synthesisRevisions.id], name: "ai_synthesis_decisions_expected_revision_fk" }).onDelete("restrict"),
    resultingRevisionOwnership: foreignKey({ columns: [table.projectId, table.resultingSynthesisRevisionId], foreignColumns: [synthesisRevisions.projectId, synthesisRevisions.id], name: "ai_synthesis_decisions_resulting_revision_fk" }).onDelete("restrict"),
    decisionValid: check("ai_synthesis_decisions_decision_valid", sql`${table.decision} in ('rejected', 'accepted')`),
    modeValid: check("ai_synthesis_decisions_acceptance_mode_valid", sql`${table.acceptanceMode} is null or ${table.acceptanceMode} in ('accept', 'edit_and_accept')`),
    decisionShape: check("ai_synthesis_decisions_decision_shape", sql`(
      (${table.decision} = 'rejected' and ${table.acceptanceMode} is null and ${table.resultingSynthesisRevisionId} is null and ${table.title} is null and ${table.statementText} is null and ${table.researcherNote} is null)
      or (${table.decision} = 'accepted' and ${table.acceptanceMode} is not null and ${table.resultingSynthesisRevisionId} is not null and ${table.statementText} is not null and btrim(${table.statementText}) <> '')
    )`),
    titleBound: check("ai_synthesis_decisions_title_bound", sql`${table.title} is null or (btrim(${table.title}) <> '' and char_length(${table.title}) <= 500)`),
    statementBound: check("ai_synthesis_decisions_statement_bound", sql`char_length(${table.statementText}) <= 10000`),
    noteBound: check("ai_synthesis_decisions_note_bound", sql`${table.researcherNote} is null or (btrim(${table.researcherNote}) <> '' and char_length(${table.researcherNote}) <= 10000)`),
  }),
);
