import {
  integer,
  index,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  foreignKey,
  check,
  bigint,
  jsonb,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { bytea } from "./shared";
import { projects, papers } from "./foundation";
import { fullTextDocuments } from "./documents-evidence";

export const bibliographicImports = pgTable(
  "bibliographic_imports",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    format: text("format").notNull(),
    filename: text("filename").notNull(),
    sourceBytes: bytea("source_bytes").notNull(),
    sourceSha256: text("source_sha256").notNull(),
    sourceByteSize: integer("source_byte_size").notNull(),
    parserVersion: text("parser_version").notNull(),
    adapterVersion: text("adapter_version").notNull(),
    mappingVersion: text("mapping_version").notNull(),
    status: text("status").notNull().default("pending"),
    expectedRecordCount: integer("expected_record_count").notNull(),
    diagnostics: jsonb("diagnostics").notNull().default([]),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }),
  },
  (table) => ({
    projectIdentity: unique("bibliographic_imports_project_id_id_unique").on(table.projectId, table.id),
    projectFormatHashIdentity: unique("bibliographic_imports_project_format_sha256_unique").on(table.projectId, table.format, table.sourceSha256),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "bibliographic_imports_project_fk" }).onDelete("restrict"),
    formatNonblank: check("bibliographic_imports_format_nonblank", sql`btrim(${table.format}) <> ''`),
    formatValid: check("bibliographic_imports_format_valid", sql`${table.format} in ('bibtex', 'ris')`),
    filenameNonblank: check("bibliographic_imports_filename_nonblank", sql`btrim(${table.filename}) <> ''`),
    filenameLength: check("bibliographic_imports_filename_length", sql`char_length(${table.filename}) <= 500`),
    sourceSizeBound: check("bibliographic_imports_source_size_bound", sql`octet_length(${table.sourceBytes}) > 0 and octet_length(${table.sourceBytes}) <= 2097152 and ${table.sourceByteSize} = octet_length(${table.sourceBytes})`),
    versionShape: check("bibliographic_imports_version_shape", sql`btrim(${table.parserVersion}) <> '' and btrim(${table.adapterVersion}) <> '' and btrim(${table.mappingVersion}) <> ''`),
    sha256Shape: check("bibliographic_imports_sha256_shape", sql`${table.sourceSha256} ~ '^[0-9a-f]{64}$'`),
    statusValid: check("bibliographic_imports_status_valid", sql`${table.status} in ('pending', 'parsing', 'complete', 'parsed', 'failed', 'finalized')`),
    recordCountValid: check("bibliographic_imports_record_count_valid", sql`${table.expectedRecordCount} >= 0 and ${table.expectedRecordCount} <= 1000`),
    errorShape: check("bibliographic_imports_error_shape", sql`((${table.status} = 'failed' and ${table.errorCode} is not null and btrim(${table.errorCode}) <> '') or (${table.status} <> 'failed' and ${table.errorCode} is null))`),
    errorMessageBound: check("bibliographic_imports_error_message_bound", sql`${table.errorMessage} is null or char_length(${table.errorMessage}) <= 2000`),
    finalizationShape: check("bibliographic_imports_finalization_shape", sql`((${table.status} in ('finalized', 'failed') and ${table.finalizedAt} is not null) or (${table.status} not in ('finalized', 'failed') and ${table.finalizedAt} is null))`),
    createdAtIndex: index("bibliographic_imports_project_created_at_idx").on(table.projectId, table.createdAt),
  }),
);

export const bibliographicImportRecords = pgTable(
  "bibliographic_import_records",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    importId: uuid("import_id").notNull(),
    ordinal: integer("ordinal").notNull(),
    sourceKey: text("source_key"),
    sourceType: text("source_type"),
    title: text("title"),
    authors: text("authors").array().notNull().default([]),
    abstract: text("abstract"),
    doi: text("doi"),
    url: text("url"),
    publicationYear: integer("publication_year"),
    venue: text("venue"),
    startByte: integer("start_byte").notNull(),
    endByte: integer("end_byte").notNull(),
    parseOutcome: text("parse_outcome").notNull().default("parsed"),
    fieldStates: jsonb("field_states").notNull().default({}),
    diagnostics: jsonb("diagnostics").notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }),
  },
  (table) => ({
    projectIdentity: unique("bibliographic_import_records_project_id_id_unique").on(table.projectId, table.id),
    importOrdinal: unique("bibliographic_import_records_project_import_ordinal_unique").on(table.projectId, table.importId, table.ordinal),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "bibliographic_import_records_project_fk" }).onDelete("restrict"),
    importOwnership: foreignKey({ columns: [table.projectId, table.importId], foreignColumns: [bibliographicImports.projectId, bibliographicImports.id], name: "bibliographic_import_records_import_fk" }).onDelete("restrict"),
    importOrdinalIndex: index("bibliographic_import_records_project_import_ordinal_idx").on(table.projectId, table.importId, table.ordinal),
    doiComparison: index("bibliographic_import_records_project_doi_comparison_idx").using("btree", table.projectId, sql`lower(regexp_replace(regexp_replace(btrim(${table.doi}), '^https?://(dx[.])?doi[.]org/', '', 'i'), '^doi:[[:space:]]*', '', 'i'))`).where(sql`${table.doi} is not null and btrim(${table.doi}) <> ''`),
    titleComparison: index("bibliographic_import_records_project_title_comparison_idx").using("btree", table.projectId, sql`lower(regexp_replace(btrim(${table.title}), '[[:space:]]+', ' ', 'g'))`, table.publicationYear),
    ordinalValid: check("bibliographic_import_records_ordinal_valid", sql`${table.ordinal} >= 0`),
    sourceKeyNonblank: check("bibliographic_import_records_source_key_nonblank", sql`${table.sourceKey} is null or btrim(${table.sourceKey}) <> ''`),
    sourceTypeNonblank: check("bibliographic_import_records_source_type_nonblank", sql`${table.sourceType} is null or btrim(${table.sourceType}) <> ''`),
    titleNonblank: check("bibliographic_import_records_title_nonblank", sql`((${table.title} is null and ${table.parseOutcome} in ('parsed_with_warnings', 'failed')) or (${table.title} is not null and btrim(${table.title}) <> ''))`),
    yearValid: check("bibliographic_import_records_year_valid", sql`${table.publicationYear} is null or (${table.publicationYear} >= 1000 and ${table.publicationYear} <= 3000)`),
    venueNonblank: check("bibliographic_import_records_venue_nonblank", sql`${table.venue} is null or btrim(${table.venue}) <> ''`),
    spanShape: check("bibliographic_import_records_span_shape", sql`${table.startByte} >= 0 and ${table.endByte} > ${table.startByte}`),
    parseOutcomeValid: check("bibliographic_import_records_parse_outcome_valid", sql`${table.parseOutcome} in ('parsed', 'parsed_with_warnings', 'failed')`),
    finalizationShape: check("bibliographic_import_records_finalization_shape", sql`${table.finalizedAt} is null or ${table.parseOutcome} <> 'failed'`),
  }),
);

export const bibliographicImportResolutions = pgTable(
  "bibliographic_import_resolutions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sequence: bigint("sequence", { mode: "number" }).generatedAlwaysAsIdentity().notNull(),
    projectId: uuid("project_id").notNull(),
    importId: uuid("import_id").notNull(),
    recordId: uuid("record_id").notNull(),
    eventType: text("event_type").notNull(),
    paperId: uuid("paper_id"),
    expectedPreviousResolutionId: uuid("expected_previous_resolution_id"),
    creationPayload: jsonb("creation_payload"),
    candidatePaperId: uuid("candidate_paper_id"),
    candidateRank: integer("candidate_rank"),
    candidateReason: text("candidate_reason"),
    candidateDoi: text("candidate_doi"),
    candidateTitle: text("candidate_title"),
    candidatePublicationYear: integer("candidate_publication_year"),
    candidateVenue: text("candidate_venue"),
    candidateContext: jsonb("candidate_context"),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("bibliographic_import_resolutions_project_id_id_unique").on(table.projectId, table.id),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "bibliographic_import_resolutions_project_fk" }).onDelete("restrict"),
    recordOwnership: foreignKey({ columns: [table.projectId, table.recordId], foreignColumns: [bibliographicImportRecords.projectId, bibliographicImportRecords.id], name: "bibliographic_import_resolutions_record_fk" }).onDelete("restrict"),
    importOwnership: foreignKey({ columns: [table.projectId, table.importId], foreignColumns: [bibliographicImports.projectId, bibliographicImports.id], name: "bibliographic_import_resolutions_import_fk" }).onDelete("restrict"),
    paperOwnership: foreignKey({ columns: [table.projectId, table.paperId], foreignColumns: [papers.projectId, papers.id], name: "bibliographic_import_resolutions_paper_fk" }).onDelete("restrict"),
    candidatePaperOwnership: foreignKey({ columns: [table.projectId, table.candidatePaperId], foreignColumns: [papers.projectId, papers.id], name: "bibliographic_import_resolutions_candidate_paper_fk" }).onDelete("restrict"),
    expectedPreviousOwnership: foreignKey({ columns: [table.projectId, table.expectedPreviousResolutionId], foreignColumns: [table.projectId, table.id], name: "bibliographic_import_resolutions_expected_previous_fk" }).onDelete("restrict"),
    recordSequence: index("bibliographic_import_resolutions_project_record_sequence_idx").on(table.projectId, table.recordId, table.sequence),
    importSequence: index("bibliographic_import_resolutions_project_import_sequence_idx").on(table.projectId, table.importId, table.sequence),
    eventTypeValid: check("bibliographic_import_resolutions_event_type_valid", sql`${table.eventType} in ('created_paper', 'matched_paper', 'cleared')`),
    paperShape: check("bibliographic_import_resolutions_paper_shape", sql`((${table.eventType} in ('created_paper', 'matched_paper') and ${table.paperId} is not null) or (${table.eventType} = 'cleared' and ${table.paperId} is null))`),
    creationPayloadShape: check("bibliographic_import_resolutions_creation_payload_shape", sql`((${table.eventType} = 'created_paper' and ${table.creationPayload} is not null) or (${table.eventType} <> 'created_paper' and ${table.creationPayload} is null))`),
    candidateRankValid: check("bibliographic_import_resolutions_candidate_rank_valid", sql`${table.candidateRank} is null or ${table.candidateRank} > 0`),
    candidateReasonShape: check("bibliographic_import_resolutions_candidate_reason_shape", sql`${table.candidateReason} is null or (btrim(${table.candidateReason}) <> '' and char_length(${table.candidateReason}) <= 1000)`),
    candidateYearValid: check("bibliographic_import_resolutions_candidate_year_valid", sql`${table.candidatePublicationYear} is null or (${table.candidatePublicationYear} >= 1000 and ${table.candidatePublicationYear} <= 3000)`),
    noteShape: check("bibliographic_import_resolutions_note_shape", sql`${table.note} is null or (btrim(${table.note}) <> '' and char_length(${table.note}) <= 2000)`),
  }),
);

export const pdfIntakes = pgTable(
  "pdf_intakes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    storageKey: text("storage_key").notNull(),
    originalFilename: text("original_filename").notNull(),
    mediaType: text("media_type").notNull(),
    byteSize: bigint("byte_size", { mode: "number" }).notNull(),
    sha256: text("sha256").notNull(),
    storageState: text("storage_state").$type<"pending" | "ready">().notNull(),
    stagedStorageKey: text("staged_storage_key"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("pdf_intakes_project_id_id_unique").on(table.projectId, table.id),
    projectSha256Identity: unique("pdf_intakes_project_sha256_unique").on(table.projectId, table.sha256),
    storageKeyUnique: unique("pdf_intakes_storage_key_unique").on(table.storageKey),
    stagedStorageKeyUnique: uniqueIndex("pdf_intakes_staged_storage_key_unique").on(table.stagedStorageKey).where(sql`${table.stagedStorageKey} is not null`),
    pendingStorageIndex: index("pdf_intakes_pending_storage_idx").on(table.createdAt, table.id).where(sql`${table.storageState} = 'pending'`),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "pdf_intakes_project_fk" }).onDelete("restrict"),
    storageKeyNonblank: check("pdf_intakes_storage_key_nonblank", sql`btrim(${table.storageKey}) <> ''`),
    storageKeyFormat: check("pdf_intakes_storage_key_format", sql`${table.storageKey} ~ '^projects/[0-9a-f-]{36}/pdf-intakes/[0-9a-f-]{36}/source\\.pdf$'`),
    filenameNonblank: check("pdf_intakes_filename_nonblank", sql`btrim(${table.originalFilename}) <> ''`),
    filenameLength: check("pdf_intakes_filename_length", sql`char_length(${table.originalFilename}) <= 500`),
    mediaTypePdf: check("pdf_intakes_media_type_pdf", sql`${table.mediaType} = 'application/pdf'`),
    byteSizeBound: check("pdf_intakes_byte_size_bound", sql`${table.byteSize} > 0 and ${table.byteSize} <= 52428800`),
    sha256Format: check("pdf_intakes_sha256_format", sql`${table.sha256} ~ '^[0-9a-f]{64}$'`),
    storageStateValid: check("pdf_intakes_storage_state_valid", sql`${table.storageState} in ('pending', 'ready')`),
    storageStateStageShape: check("pdf_intakes_storage_state_stage_shape", sql`((${table.storageState} = 'ready' and ${table.stagedStorageKey} is null) or (${table.storageState} = 'pending' and ${table.stagedStorageKey} ~ '^\\.pdf-intake/\\.tmp/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.upload$'))`),
    createdAtIndex: index("pdf_intakes_project_created_at_idx").on(table.projectId, table.createdAt),
  }),
);

export const pdfIntakeMetadataResults = pgTable(
  "pdf_intake_metadata_results",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sequenceNo: bigint("sequence_no", { mode: "number" }).notNull(),
    projectId: uuid("project_id").notNull(),
    intakeId: uuid("intake_id").notNull(),
    status: text("status").notNull(),
    extractorKey: text("extractor_key").notNull(),
    extractorVersion: text("extractor_version").notNull(),
    pdfjsVersion: text("pdfjs_version"),
    mappingVersion: text("mapping_version").notNull(),
    textScanVersion: text("text_scan_version").notNull(),
    doiAlgorithmVersion: text("doi_algorithm_version").notNull(),
    pageCount: integer("page_count"),
    attemptedPageCount: integer("attempted_page_count").notNull(),
    succeededPageCount: integer("succeeded_page_count").notNull(),
    scannedCodePoints: integer("scanned_code_points").notNull(),
    diagnostics: jsonb("diagnostics").notNull().default([]),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("pdf_intake_metadata_results_project_id_id_unique").on(table.projectId, table.id),
    intakeSequenceIdentity: unique("pdf_intake_metadata_results_project_intake_sequence_no_unique").on(table.projectId, table.intakeId, table.sequenceNo),
    intakeSequence: index("pdf_intake_metadata_results_project_intake_sequence_no_idx").on(table.projectId, table.intakeId, table.sequenceNo),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "pdf_intake_metadata_results_project_fk" }).onDelete("restrict"),
    intakeOwnership: foreignKey({ columns: [table.projectId, table.intakeId], foreignColumns: [pdfIntakes.projectId, pdfIntakes.id], name: "pdf_intake_metadata_results_intake_fk" }).onDelete("restrict"),
    statusValid: check("pdf_intake_metadata_results_status_valid", sql`${table.status} in ('succeeded', 'partial', 'failed')`),
    extractorKeyNonblank: check("pdf_intake_metadata_results_extractor_key_nonblank", sql`btrim(${table.extractorKey}) <> ''`),
    versionShape: check("pdf_intake_metadata_results_version_shape", sql`btrim(${table.extractorVersion}) <> '' and (${table.pdfjsVersion} is null or btrim(${table.pdfjsVersion}) <> '') and btrim(${table.mappingVersion}) <> '' and btrim(${table.textScanVersion}) <> '' and btrim(${table.doiAlgorithmVersion}) <> ''`),
    pageCountsValid: check("pdf_intake_metadata_results_page_counts_valid", sql`${table.pageCount} is null or (${table.pageCount} >= 0 and ${table.attemptedPageCount} >= 0 and ${table.succeededPageCount} >= 0 and ${table.succeededPageCount} <= ${table.attemptedPageCount} and ${table.attemptedPageCount} <= ${table.pageCount})`),
    scannedCodePointsValid: check("pdf_intake_metadata_results_scanned_code_points_valid", sql`${table.scannedCodePoints} >= 0 and ${table.scannedCodePoints} <= 250000`),
    errorShape: check("pdf_intake_metadata_results_error_shape", sql`((${table.status} = 'failed' and ${table.errorCode} is not null and btrim(${table.errorCode}) <> '') or (${table.status} <> 'failed' and ${table.errorCode} is null))`),
    errorMessageBound: check("pdf_intake_metadata_results_error_message_bound", sql`${table.errorMessage} is null or char_length(${table.errorMessage}) <= 2000`),
    createdAtIndex: index("pdf_intake_metadata_results_project_created_at_idx").on(table.projectId, table.createdAt),
  }),
);

export const pdfIntakeMetadataFields = pgTable(
  "pdf_intake_metadata_fields",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    intakeId: uuid("intake_id").notNull(),
    resultId: uuid("result_id").notNull(),
    paperField: text("paper_field").notNull(),
    candidateOrdinal: integer("candidate_ordinal").notNull(),
    valueJsonb: jsonb("value_jsonb"),
    sourceKind: text("source_kind"),
    sourceLocator: text("source_locator"),
    classification: text("classification").notNull(),
    diagnostic: text("diagnostic"),
    normalizedValue: text("normalized_value"),
    pageNumber: integer("page_number"),
    startOffset: integer("start_offset"),
    endOffset: integer("end_offset"),
    exactMatch: text("exact_match"),
    pageTextSha256: text("page_text_sha256"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("pdf_intake_metadata_fields_project_id_id_unique").on(table.projectId, table.id),
    resultCandidateIdentity: unique("pdf_intake_metadata_fields_project_intake_result_unique").on(table.projectId, table.intakeId, table.resultId, table.paperField, table.candidateOrdinal),
    resultOrder: index("pdf_intake_metadata_fields_project_result_order_idx").on(table.projectId, table.resultId, table.paperField, table.candidateOrdinal),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "pdf_intake_metadata_fields_project_fk" }).onDelete("restrict"),
    intakeOwnership: foreignKey({ columns: [table.projectId, table.intakeId], foreignColumns: [pdfIntakes.projectId, pdfIntakes.id], name: "pdf_intake_metadata_fields_intake_fk" }).onDelete("restrict"),
    resultOwnership: foreignKey({ columns: [table.projectId, table.resultId], foreignColumns: [pdfIntakeMetadataResults.projectId, pdfIntakeMetadataResults.id], name: "pdf_intake_metadata_fields_result_fk" }).onDelete("restrict"),
    paperFieldValid: check("pdf_intake_metadata_fields_paper_field_valid", sql`${table.paperField} in ('title', 'authors', 'publication_year', 'venue', 'doi', 'abstract')`),
    candidateOrdinalValid: check("pdf_intake_metadata_fields_candidate_ordinal_valid", sql`${table.candidateOrdinal} > 0`),
    sourceKindValid: check("pdf_intake_metadata_fields_source_kind_valid", sql`${table.sourceKind} is null or ${table.sourceKind} in ('pdf_info', 'xmp', 'page_text_match', 'unavailable')`),
    classificationValid: check("pdf_intake_metadata_fields_classification_valid", sql`${table.classification} in ('exact_embedded_metadata', 'exact_text_identifier', 'ambiguous', 'unavailable')`),
    sourceLocatorShape: check("pdf_intake_metadata_fields_source_locator_shape", sql`${table.sourceLocator} is null or btrim(${table.sourceLocator}) <> ''`),
    pageNumberValid: check("pdf_intake_metadata_fields_page_number_valid", sql`${table.pageNumber} is null or ${table.pageNumber} > 0`),
    offsetShape: check("pdf_intake_metadata_fields_offset_shape", sql`((${table.startOffset} is null and ${table.endOffset} is null) or (${table.startOffset} is not null and ${table.endOffset} is not null and ${table.startOffset} >= 0 and ${table.endOffset} > ${table.startOffset}))`),
    exactMatchShape: check("pdf_intake_metadata_fields_exact_match_shape", sql`${table.exactMatch} is null or btrim(${table.exactMatch}) <> ''`),
    pageTextSha256Format: check("pdf_intake_metadata_fields_page_text_sha256_format", sql`${table.pageTextSha256} is null or ${table.pageTextSha256} ~ '^[0-9a-f]{64}$'`),
    pageMatchProvenanceShape: check("pdf_intake_metadata_fields_page_match_provenance_shape", sql`${table.sourceKind} is distinct from 'page_text_match' or (${table.pageNumber} is not null and ${table.startOffset} is not null and ${table.endOffset} is not null and ${table.exactMatch} is not null and ${table.pageTextSha256} is not null)`),
    unavailableShape: check("pdf_intake_metadata_fields_unavailable_shape", sql`(${table.classification} <> 'unavailable' or (${table.valueJsonb} is null and ${table.normalizedValue} is null and ${table.pageNumber} is null and ${table.startOffset} is null and ${table.endOffset} is null and ${table.exactMatch} is null and ${table.pageTextSha256} is null))`),
  }),
);

export const pdfIntakeResolutions = pgTable(
  "pdf_intake_resolutions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sequenceNo: bigint("sequence_no", { mode: "number" }).generatedAlwaysAsIdentity().notNull(),
    projectId: uuid("project_id").notNull(),
    intakeId: uuid("intake_id").notNull(),
    metadataResultId: uuid("metadata_result_id").notNull(),
    resolutionKind: text("resolution_kind").notNull(),
    paperId: uuid("paper_id").notNull(),
    fullTextDocumentId: uuid("full_text_document_id").notNull(),
    materializationKind: text("materialization_kind").notNull(),
    creationPayload: jsonb("creation_payload"),
    candidateContext: jsonb("candidate_context").notNull().default({}),
    previewFingerprint: text("preview_fingerprint").notNull(),
    requestFingerprint: text("request_fingerprint").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("pdf_intake_resolutions_project_id_id_unique").on(table.projectId, table.id),
    intakeIdentity: unique("pdf_intake_resolutions_project_intake_unique").on(table.projectId, table.intakeId),
    projectSequence: index("pdf_intake_resolutions_project_sequence_no_idx").on(table.projectId, table.sequenceNo),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "pdf_intake_resolutions_project_fk" }).onDelete("restrict"),
    intakeOwnership: foreignKey({ columns: [table.projectId, table.intakeId], foreignColumns: [pdfIntakes.projectId, pdfIntakes.id], name: "pdf_intake_resolutions_intake_fk" }).onDelete("restrict"),
    metadataResultOwnership: foreignKey({ columns: [table.projectId, table.metadataResultId], foreignColumns: [pdfIntakeMetadataResults.projectId, pdfIntakeMetadataResults.id], name: "pdf_intake_resolutions_metadata_result_fk" }).onDelete("restrict"),
    paperOwnership: foreignKey({ columns: [table.projectId, table.paperId], foreignColumns: [papers.projectId, papers.id], name: "pdf_intake_resolutions_paper_fk" }).onDelete("restrict"),
    fullTextDocumentOwnership: foreignKey({ columns: [table.projectId, table.fullTextDocumentId], foreignColumns: [fullTextDocuments.projectId, fullTextDocuments.id], name: "pdf_intake_resolutions_full_text_document_fk" }).onDelete("restrict"),
    resolutionKindValid: check("pdf_intake_resolutions_resolution_kind_valid", sql`${table.resolutionKind} in ('create_paper', 'match_paper')`),
    materializationKindValid: check("pdf_intake_resolutions_materialization_kind_valid", sql`${table.materializationKind} in ('created_document', 'reused_document')`),
    creationPayloadShape: check("pdf_intake_resolutions_creation_payload_shape", sql`((${table.resolutionKind} = 'create_paper' and ${table.creationPayload} is not null) or (${table.resolutionKind} = 'match_paper' and ${table.creationPayload} is null))`),
    candidateContextShape: check("pdf_intake_resolutions_candidate_context_shape", sql`${table.candidateContext} is not null`),
    previewFingerprintShape: check("pdf_intake_resolutions_preview_fingerprint_shape", sql`${table.previewFingerprint} ~ '^[0-9a-f]{64}$'`),
    requestFingerprintShape: check("pdf_intake_resolutions_request_fingerprint_shape", sql`${table.requestFingerprint} ~ '^[0-9a-f]{64}$'`),
  }),
);

export const doiLookupRequests = pgTable(
  "doi_lookup_requests",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id").notNull(),
    submittedDoi: text("submitted_doi").notNull(),
    normalizedDoi: text("normalized_doi").notNull(),
    provider: text("provider").notNull(),
    providerContractVersion: text("provider_contract_version").notNull(),
    providerMappingVersion: text("provider_mapping_version").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("doi_lookup_requests_project_id_id_unique").on(table.projectId, table.id),
    projectIdempotency: unique("doi_lookup_requests_project_id_idempotency_key_unique").on(table.projectId, table.idempotencyKey),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "doi_lookup_requests_project_fk" }).onDelete("cascade"),
    projectCreatedAt: index("doi_lookup_requests_project_created_at_idx").on(table.projectId, table.createdAt),
    projectDoi: index("doi_lookup_requests_project_normalized_doi_idx").on(table.projectId, table.normalizedDoi),
    submittedDoiShape: check("doi_lookup_requests_submitted_doi_shape", sql`char_length(${table.submittedDoi}) <= 1000 and btrim(${table.submittedDoi}) <> '' and ${table.submittedDoi} !~ '[\\u0000-\\u001f\\u007f]'`),
    normalizedDoiShape: check("doi_lookup_requests_normalized_doi_shape", sql`char_length(${table.normalizedDoi}) <= 1000 and btrim(${table.normalizedDoi}) <> '' and ${table.normalizedDoi} !~ '[\\u0000-\\u001f\\u007f]'`),
    providerShape: check("doi_lookup_requests_provider_shape", sql`char_length(${table.provider}) <= 100 and btrim(${table.provider}) <> ''`),
    contractVersionShape: check("doi_lookup_requests_contract_version_shape", sql`char_length(${table.providerContractVersion}) <= 100 and btrim(${table.providerContractVersion}) <> ''`),
    mappingVersionShape: check("doi_lookup_requests_mapping_version_shape", sql`char_length(${table.providerMappingVersion}) <= 100 and btrim(${table.providerMappingVersion}) <> ''`),
    idempotencyKeyShape: check("doi_lookup_requests_idempotency_key_shape", sql`char_length(${table.idempotencyKey}) <= 200 and btrim(${table.idempotencyKey}) <> ''`),
  }),
);

export const bibliographicMetadataFetches = pgTable(
  "bibliographic_metadata_fetches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    provider: text("provider").notNull(),
    normalizedDoi: text("normalized_doi").notNull(),
    providerContractVersion: text("provider_contract_version").notNull(),
    providerMappingVersion: text("provider_mapping_version").notNull(),
    cacheKey: text("cache_key").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    deadlineAt: timestamp("deadline_at", { withTimezone: true }).notNull(),
    executionIdentity: text("execution_identity").notNull(),
    rateLimitPerSecond: integer("rate_limit_per_second").notNull(),
    concurrencyLimit: integer("concurrency_limit").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    cacheIdentity: index("bibliographic_metadata_fetches_cache_identity_idx").on(table.provider, table.normalizedDoi, table.providerContractVersion, table.providerMappingVersion),
    cacheKeyIndex: index("bibliographic_metadata_fetches_cache_key_idx").on(table.cacheKey),
    providerStartedAt: index("bibliographic_metadata_fetches_provider_started_at_idx").on(table.provider, table.startedAt),
    providerShape: check("bibliographic_metadata_fetches_provider_shape", sql`char_length(${table.provider}) <= 100 and btrim(${table.provider}) <> ''`),
    doiShape: check("bibliographic_metadata_fetches_doi_shape", sql`char_length(${table.normalizedDoi}) <= 1000 and btrim(${table.normalizedDoi}) <> '' and ${table.normalizedDoi} !~ '[\\u0000-\\u001f\\u007f]'`),
    contractShape: check("bibliographic_metadata_fetches_contract_shape", sql`char_length(${table.providerContractVersion}) <= 100 and btrim(${table.providerContractVersion}) <> ''`),
    mappingShape: check("bibliographic_metadata_fetches_mapping_shape", sql`char_length(${table.providerMappingVersion}) <= 100 and btrim(${table.providerMappingVersion}) <> ''`),
    cacheKeyShape: check("bibliographic_metadata_fetches_cache_key_shape", sql`char_length(${table.cacheKey}) <= 2500 and btrim(${table.cacheKey}) <> ''`),
    executionIdentityShape: check("bibliographic_metadata_fetches_execution_identity_shape", sql`char_length(${table.executionIdentity}) <= 200 and btrim(${table.executionIdentity}) <> ''`),
    deadlineShape: check("bibliographic_metadata_fetches_deadline_shape", sql`${table.deadlineAt} > ${table.startedAt}`),
    scheduleShape: check("bibliographic_metadata_fetches_schedule_shape", sql`${table.rateLimitPerSecond} > 0 and ${table.rateLimitPerSecond} <= 1000 and ${table.concurrencyLimit} > 0 and ${table.concurrencyLimit} <= 100`),
  }),
);

export const doiLookupDispatches = pgTable(
  "doi_lookup_dispatches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sequence: bigint("sequence", { mode: "number" }).generatedAlwaysAsIdentity().notNull(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    fetchId: uuid("fetch_id").notNull(),
    dispatchKind: text("dispatch_kind").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("doi_lookup_dispatches_project_id_id_unique").on(table.projectId, table.id),
    projectRequestSequence: index("doi_lookup_dispatches_project_request_sequence_idx").on(table.projectId, table.requestId, table.sequence),
    fetchSequence: index("doi_lookup_dispatches_fetch_sequence_idx").on(table.fetchId, table.sequence),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "doi_lookup_dispatches_project_fk" }).onDelete("cascade"),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [doiLookupRequests.projectId, doiLookupRequests.id], name: "doi_lookup_dispatches_request_fk" }).onDelete("cascade"),
    fetchOwnership: foreignKey({ columns: [table.fetchId], foreignColumns: [bibliographicMetadataFetches.id], name: "doi_lookup_dispatches_fetch_fk" }).onDelete("restrict"),
    kindValid: check("doi_lookup_dispatches_kind_valid", sql`${table.dispatchKind} in ('network_owner', 'network_shared', 'cache_reuse')`),
  }),
);

export const bibliographicMetadataFetchResults = pgTable(
  "bibliographic_metadata_fetch_results",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fetchId: uuid("fetch_id").notNull(),
    outcome: text("outcome").notNull(),
    httpAttemptCount: integer("http_attempt_count").notNull(),
    lastHttpStatus: integer("last_http_status"),
    responseContentType: text("response_content_type"),
    responseByteSize: integer("response_byte_size"),
    responseSha256: text("response_sha256"),
    sourceSnapshot: jsonb("source_snapshot"),
    providerDoi: text("provider_doi"),
    proposedTitle: text("proposed_title"),
    proposedPublicationYear: integer("proposed_publication_year"),
    proposedVenue: text("proposed_venue"),
    providerType: text("provider_type"),
    providerPublisher: text("provider_publisher"),
    providerUrl: text("provider_url"),
    authorsState: text("authors_state").notNull().default("absent"),
    reportedAuthorCount: integer("reported_author_count"),
    mappingWarnings: jsonb("mapping_warnings").notNull().default([]),
    diagnosticCode: text("diagnostic_code"),
    diagnosticMessage: text("diagnostic_message"),
    providerRequestId: text("provider_request_id"),
    observedRateLimitPerSecond: integer("observed_rate_limit_per_second"),
    observedConcurrencyLimit: integer("observed_concurrency_limit"),
    durationMs: integer("duration_ms"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    finalizedAt: timestamp("finalized_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    fetchIdentity: unique("bibliographic_metadata_fetch_results_fetch_id_unique").on(table.fetchId),
    finalizedAtId: index("bibliographic_metadata_fetch_results_finalized_at_id_idx").on(table.finalizedAt, table.id),
    outcomeFinalizedAt: index("bibliographic_metadata_fetch_results_outcome_finalized_at_idx").on(table.outcome, table.finalizedAt, table.id),
    fetchOwnership: foreignKey({ columns: [table.fetchId], foreignColumns: [bibliographicMetadataFetches.id], name: "bibliographic_metadata_fetch_results_fetch_fk" }).onDelete("restrict"),
    outcomeValid: check("bibliographic_metadata_fetch_results_outcome_valid", sql`${table.outcome} in ('succeeded', 'not_found', 'provider_unavailable', 'rate_limited', 'invalid_response', 'provider_mismatch', 'failed')`),
    attemptCountValid: check("bibliographic_metadata_fetch_results_attempt_count_valid", sql`${table.httpAttemptCount} >= 0 and ${table.httpAttemptCount} <= 3`),
    httpStatusValid: check("bibliographic_metadata_fetch_results_http_status_valid", sql`${table.lastHttpStatus} is null or (${table.lastHttpStatus} >= 100 and ${table.lastHttpStatus} <= 599)`),
    responseEvidenceShape: check("bibliographic_metadata_fetch_results_response_evidence_shape", sql`((${table.responseByteSize} is null and ${table.responseSha256} is null) or (${table.responseByteSize} > 0 and ${table.responseByteSize} <= 2097152 and ${table.responseSha256} ~ '^[0-9a-f]{64}$'))`),
    authorsStateValid: check("bibliographic_metadata_fetch_results_authors_state_valid", sql`${table.authorsState} in ('valid', 'invalid', 'absent')`),
    reportedAuthorCountValid: check("bibliographic_metadata_fetch_results_reported_author_count_valid", sql`${table.reportedAuthorCount} is null or (${table.reportedAuthorCount} >= 0 and ${table.reportedAuthorCount} <= 10000)`),
    yearValid: check("bibliographic_metadata_fetch_results_year_valid", sql`${table.proposedPublicationYear} is null or (${table.proposedPublicationYear} >= 1000 and ${table.proposedPublicationYear} <= 3000)`),
    titleShape: check("bibliographic_metadata_fetch_results_title_shape", sql`${table.proposedTitle} is null or (btrim(${table.proposedTitle}) <> '' and char_length(${table.proposedTitle}) <= 1000)`),
    venueShape: check("bibliographic_metadata_fetch_results_venue_shape", sql`${table.proposedVenue} is null or (btrim(${table.proposedVenue}) <> '' and char_length(${table.proposedVenue}) <= 1000)`),
    providerTypeShape: check("bibliographic_metadata_fetch_results_provider_type_shape", sql`${table.providerType} is null or (btrim(${table.providerType}) <> '' and char_length(${table.providerType}) <= 200)`),
    publisherShape: check("bibliographic_metadata_fetch_results_publisher_shape", sql`${table.providerPublisher} is null or (btrim(${table.providerPublisher}) <> '' and char_length(${table.providerPublisher}) <= 1000)`),
    providerUrlShape: check("bibliographic_metadata_fetch_results_provider_url_shape", sql`${table.providerUrl} is null or (char_length(${table.providerUrl}) <= 2048 and ${table.providerUrl} ~ '^https?://')`),
    diagnosticCodeShape: check("bibliographic_metadata_fetch_results_diagnostic_code_shape", sql`${table.diagnosticCode} is null or (btrim(${table.diagnosticCode}) <> '' and char_length(${table.diagnosticCode}) <= 80)`),
    diagnosticMessageShape: check("bibliographic_metadata_fetch_results_diagnostic_message_shape", sql`${table.diagnosticMessage} is null or char_length(${table.diagnosticMessage}) <= 2000`),
    providerRequestIdShape: check("bibliographic_metadata_fetch_results_provider_request_id_shape", sql`${table.providerRequestId} is null or (btrim(${table.providerRequestId}) <> '' and char_length(${table.providerRequestId}) <= 200)`),
    durationValid: check("bibliographic_metadata_fetch_results_duration_valid", sql`${table.durationMs} is null or (${table.durationMs} >= 0 and ${table.durationMs} <= 600000)`),
    finalizedShape: check("bibliographic_metadata_fetch_results_finalized_shape", sql`${table.finalizedAt} >= ${table.createdAt}`),
  }),
);

export const bibliographicMetadataResultAuthors = pgTable(
  "bibliographic_metadata_result_authors",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    resultId: uuid("result_id").notNull(),
    ordinal: integer("ordinal").notNull(),
    givenName: text("given_name"),
    familyName: text("family_name"),
    literalName: text("literal_name"),
    suffix: text("suffix"),
    orcid: text("orcid"),
    displayName: text("display_name").notNull(),
    providerSequence: text("provider_sequence"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    resultIdentity: unique("bibliographic_metadata_result_authors_result_id_id_unique").on(table.resultId, table.id),
    resultOrdinal: unique("bibliographic_metadata_result_authors_result_ordinal_unique").on(table.resultId, table.ordinal),
    resultOwnership: foreignKey({ columns: [table.resultId], foreignColumns: [bibliographicMetadataFetchResults.id], name: "bibliographic_metadata_result_authors_result_fk" }).onDelete("restrict"),
    ordinalValid: check("bibliographic_metadata_result_authors_ordinal_valid", sql`${table.ordinal} >= 1 and ${table.ordinal} <= 200`),
    givenNameShape: check("bibliographic_metadata_result_authors_given_name_shape", sql`${table.givenName} is null or (btrim(${table.givenName}) <> '' and char_length(${table.givenName}) <= 500)`),
    familyNameShape: check("bibliographic_metadata_result_authors_family_name_shape", sql`${table.familyName} is null or (btrim(${table.familyName}) <> '' and char_length(${table.familyName}) <= 500)`),
    literalNameShape: check("bibliographic_metadata_result_authors_literal_name_shape", sql`${table.literalName} is null or (btrim(${table.literalName}) <> '' and char_length(${table.literalName}) <= 500)`),
    suffixShape: check("bibliographic_metadata_result_authors_suffix_shape", sql`${table.suffix} is null or (btrim(${table.suffix}) <> '' and char_length(${table.suffix}) <= 500)`),
    orcidShape: check("bibliographic_metadata_result_authors_orcid_shape", sql`${table.orcid} is null or (btrim(${table.orcid}) <> '' and char_length(${table.orcid}) <= 200)`),
    displayNameShape: check("bibliographic_metadata_result_authors_display_name_shape", sql`btrim(${table.displayName}) <> '' and char_length(${table.displayName}) <= 500`),
    providerSequenceShape: check("bibliographic_metadata_result_authors_provider_sequence_shape", sql`${table.providerSequence} is null or (btrim(${table.providerSequence}) <> '' and char_length(${table.providerSequence}) <= 32)`),
    nameShape: check("bibliographic_metadata_result_authors_name_shape", sql`(${table.literalName} is not null and ${table.givenName} is null and ${table.familyName} is null) or (${table.literalName} is null and (${table.givenName} is not null or ${table.familyName} is not null))`),
  }),
);

export const doiLookupResolutions = pgTable(
  "doi_lookup_resolutions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sequence: bigint("sequence", { mode: "number" }).generatedAlwaysAsIdentity().notNull(),
    projectId: uuid("project_id").notNull(),
    requestId: uuid("request_id").notNull(),
    resultId: uuid("result_id").notNull(),
    resolutionKind: text("resolution_kind").notNull(),
    paperId: uuid("paper_id"),
    expectedPreviousResolutionId: uuid("expected_previous_resolution_id"),
    creationPayload: jsonb("creation_payload"),
    candidateContext: jsonb("candidate_context"),
    previewFingerprint: text("preview_fingerprint"),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    projectIdentity: unique("doi_lookup_resolutions_project_id_id_unique").on(table.projectId, table.id),
    projectRequestSequence: index("doi_lookup_resolutions_project_request_sequence_idx").on(table.projectId, table.requestId, table.sequence),
    projectOwnership: foreignKey({ columns: [table.projectId], foreignColumns: [projects.id], name: "doi_lookup_resolutions_project_fk" }).onDelete("cascade"),
    requestOwnership: foreignKey({ columns: [table.projectId, table.requestId], foreignColumns: [doiLookupRequests.projectId, doiLookupRequests.id], name: "doi_lookup_resolutions_request_fk" }).onDelete("cascade"),
    resultOwnership: foreignKey({ columns: [table.resultId], foreignColumns: [bibliographicMetadataFetchResults.id], name: "doi_lookup_resolutions_result_fk" }).onDelete("restrict"),
    paperOwnership: foreignKey({ columns: [table.projectId, table.paperId], foreignColumns: [papers.projectId, papers.id], name: "doi_lookup_resolutions_paper_fk" }).onDelete("restrict"),
    expectedPreviousOwnership: foreignKey({ columns: [table.projectId, table.expectedPreviousResolutionId], foreignColumns: [table.projectId, table.id], name: "doi_lookup_resolutions_expected_previous_fk" }).onDelete("restrict"),
    resolutionKindValid: check("doi_lookup_resolutions_kind_valid", sql`${table.resolutionKind} in ('created_paper', 'matched_paper', 'cleared')`),
    paperShape: check("doi_lookup_resolutions_paper_shape", sql`((${table.resolutionKind} in ('created_paper', 'matched_paper') and ${table.paperId} is not null) or (${table.resolutionKind} = 'cleared' and ${table.paperId} is null))`),
    creationPayloadShape: check("doi_lookup_resolutions_creation_payload_shape", sql`((${table.resolutionKind} = 'created_paper' and ${table.creationPayload} is not null) or (${table.resolutionKind} <> 'created_paper' and ${table.creationPayload} is null))`),
    previewFingerprintShape: check("doi_lookup_resolutions_preview_fingerprint_shape", sql`${table.previewFingerprint} is null or (${table.previewFingerprint} ~ '^[0-9a-f]{64}$' and char_length(${table.previewFingerprint}) = 64)`),
    noteShape: check("doi_lookup_resolutions_note_shape", sql`${table.note} is null or (btrim(${table.note}) <> '' and char_length(${table.note}) <= 2000)`),
  }),
);

export const bibliographicMetadataHttpAttempts = pgTable(
  "bibliographic_metadata_http_attempts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fetchId: uuid("fetch_id").notNull(),
    attemptOrdinal: integer("attempt_ordinal").notNull(),
    requestUrl: text("request_url").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    status: text("status").notNull().default("started"),
    httpStatus: integer("http_status"),
    outcomeCode: text("outcome_code"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    fetchAttempt: unique("bibliographic_metadata_http_attempts_fetch_attempt_unique").on(table.fetchId, table.attemptOrdinal),
    fetchStartedAt: index("bibliographic_metadata_http_attempts_fetch_started_at_idx").on(table.fetchId, table.startedAt),
    providerAccounting: index("bibliographic_metadata_http_attempts_started_at_status_idx").on(table.startedAt, table.status),
    fetchOwnership: foreignKey({ columns: [table.fetchId], foreignColumns: [bibliographicMetadataFetches.id], name: "bibliographic_metadata_http_attempts_fetch_fk" }).onDelete("restrict"),
    ordinalValid: check("bibliographic_metadata_http_attempts_ordinal_valid", sql`${table.attemptOrdinal} >= 1 and ${table.attemptOrdinal} <= 3`),
    urlShape: check("bibliographic_metadata_http_attempts_url_shape", sql`char_length(${table.requestUrl}) <= 4096 and ${table.requestUrl} ~ '^https://api\\.crossref\\.org/' and ${table.requestUrl} !~ '[?&]mailto='`),
    statusValid: check("bibliographic_metadata_http_attempts_status_valid", sql`${table.status} in ('started', 'succeeded', 'failed')`),
    httpStatusValid: check("bibliographic_metadata_http_attempts_http_status_valid", sql`${table.httpStatus} is null or (${table.httpStatus} >= 100 and ${table.httpStatus} <= 599)`),
    lifecycleShape: check("bibliographic_metadata_http_attempts_lifecycle_shape", sql`(${table.status} = 'started' and ${table.completedAt} is null) or (${table.status} in ('succeeded', 'failed') and ${table.completedAt} is not null)`),
    outcomeCodeShape: check("bibliographic_metadata_http_attempts_outcome_code_shape", sql`${table.outcomeCode} is null or (btrim(${table.outcomeCode}) <> '' and char_length(${table.outcomeCode}) <= 80)`),
  }),
);
