import Link from "next/link";
import { notFound } from "next/navigation";
import { displayAuthors, formatDate, loadDoiLookupDetail } from "../ui";
import { clearDoiLookupResolutionAction, createPaperFromDoiLookupAction, executeDoiLookupAction, matchDoiLookupAction } from "@/app/actions";

function value(value: string | number | null): string {
  return value == null || value === "" ? "Not reported" : String(value);
}

export default async function DoiIntakeDetailPage({ params, searchParams }: { params: Promise<{ projectId: string; requestId: string }>; searchParams?: Promise<{ error?: string; saved?: string }> }) {
  const { projectId, requestId } = await params;
  const query = searchParams ? await searchParams : {};
  const loaded = await loadDoiLookupDetail(projectId, requestId);
  if (loaded.configured && !loaded.detail) notFound();
  const detail = loaded.detail;
  const proposal = detail?.proposal;
  const diagnostics = detail?.diagnostics;
  const currentResolution = detail?.resolutions.at(-1) ?? null;

  return <div className="project-page"><div className="container workspace"><div className="workspace-header"><div><p className="eyebrow">DOI lookup detail</p><h1>{detail?.request.doi || requestId}</h1><p className="hint">Request {requestId} · {detail?.request.provider ?? "provider unavailable"} · {detail?.request.status ?? "not loaded"}</p></div><Link className="button ghost" href={`/projects/${projectId}`}>Paper collection</Link></div>
    {query.error && <div className="error-banner" role="alert">{query.error}</div>}
    {query.saved && <div className="success-note" role="status">Resolution recorded.</div>}
    {!loaded.configured && <div className="support-warning" role="status">The DOI lookup detail adapter is not exported by the shared server wiring in this worktree yet. This page is intentionally read-only until the expected interfaces are connected.</div>}
    {!detail && <section className="card section-card"><div className="empty">No persisted DOI lookup detail is available for this request ID.</div></section>}

    {detail && (detail.request.status === "pending" || detail.request.status === "in_progress") && <section className="card section-card"><h2>Run provider lookup</h2><p className="hint">The request is durable and has not completed. Executing it may reuse a global cache result or join an existing fetch.</p><form action={executeDoiLookupAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="requestId" value={requestId} /><button className="button" type="submit">Execute bounded lookup</button></form></section>}

    {detail && <>
      <section className="card section-card"><div className="section-heading"><h2>Bounded proposal</h2><span className="status">Researcher review</span></div><p className="hint">This is a proposal only. It is not canonical Paper metadata and does not include an abstract or raw provider response.</p>{proposal ? <div className="item"><div className="item-title">{value(proposal.title)}</div><div className="item-meta">Authors: {displayAuthors(proposal.authors)}</div><div className="item-meta">Publication year: {value(proposal.publicationYear)} · Venue: {value(proposal.venue)}</div><div className="item-meta">Publisher: {value(proposal.publisher)} · DOI: {value(proposal.doi)}</div>{proposal.url && <div className="item-meta">Provider URL: {proposal.url}</div>}{proposal.authorsState && <div className="item-meta">Author mapping: {proposal.authorsState}</div>}</div> : <div className="empty">No bounded proposal was persisted for this outcome.</div>}</section>

      <section className="card section-card"><div className="section-heading"><h2>Source snapshot diagnostics</h2><span className="count">Bounded evidence</span></div>{diagnostics ? <div className="item-list"><div className="item"><div className="item-meta">Outcome: <strong>{value(diagnostics.outcome)}</strong></div><div className="item-meta">Diagnostic: {value(diagnostics.diagnosticCode)}{diagnostics.diagnosticMessage ? ` · ${diagnostics.diagnosticMessage}` : ""}</div><div className="item-meta">Response: {value(diagnostics.responseContentType)} · {value(diagnostics.responseByteSize)} bytes · SHA-256 {value(diagnostics.responseSha256)}</div><div className="item-meta">Provider DOI: {value(diagnostics.providerDoi)} · duration {diagnostics.durationMs == null ? "not recorded" : `${diagnostics.durationMs} ms`}</div><div className="item-meta">Observed provider ceilings: {value(diagnostics.observedRateLimitPerSecond)}/s · concurrency {value(diagnostics.observedConcurrencyLimit)}</div></div></div> : <div className="empty">No source diagnostics were persisted.</div>}</section>

      <section className="card section-card"><div className="section-heading"><h2>Cache and network history</h2><span className="count">{detail.attempts.length} attempts · {detail.dispatches.length} dispatches</span></div>{detail.fetch && <div className="item"><div className="item-meta">Fetch {detail.fetch.id} · {detail.fetch.provider} · DOI {detail.fetch.normalizedDoi}</div><div className="item-meta">Started {formatDate(detail.fetch.startedAt)} · deadline {formatDate(detail.fetch.deadlineAt)}</div><div className="item-meta">Rate limit {value(detail.fetch.rateLimitPerSecond)}/s · concurrency {value(detail.fetch.concurrencyLimit)}{detail.fetch.executionIdentity ? ` · execution ${detail.fetch.executionIdentity}` : ""}</div></div>}{detail.dispatches.length > 0 && <div className="item-list" style={{ marginTop: 12 }}>{detail.dispatches.map((dispatch) => <div className="item" key={dispatch.id}><div className="item-meta">Dispatch {dispatch.sequence ?? dispatch.id} · {dispatch.kind} · {formatDate(dispatch.createdAt)}</div></div>)}</div>}{detail.attempts.length > 0 && <div className="item-list" style={{ marginTop: 12 }}>{detail.attempts.map((attempt) => <div className="item" key={attempt.id}><div className="item-meta">Attempt {attempt.ordinal ?? attempt.id} · {attempt.status} · HTTP {value(attempt.httpStatus)}{attempt.outcomeCode ? ` · ${attempt.outcomeCode}` : ""}</div><div className="item-meta">{attempt.requestUrl ?? "Endpoint not recorded"} · {formatDate(attempt.startedAt)} → {formatDate(attempt.completedAt)}</div></div>)}</div>}{!detail.fetch && detail.attempts.length === 0 && detail.dispatches.length === 0 && <div className="empty">No cache or network history was persisted.</div>}</section>

      <section className="card section-card"><div className="section-heading"><h2>Candidate Papers</h2><span className="count">{detail.candidates.length} candidates</span></div><p className="hint">Candidates are review signals only. Matching a Paper does not silently overwrite its canonical metadata.</p>{detail.candidates.length === 0 ? <div className="empty">No candidate Paper matches were reported.</div> : <div className="item-list">{detail.candidates.map((candidate) => <div className="item" key={candidate.id}><div className="item-title">{candidate.title}</div><div className="item-meta">{displayAuthors(candidate.authors)}{candidate.publicationYear ? ` · ${candidate.publicationYear}` : ""}{candidate.venue ? ` · ${candidate.venue}` : ""}</div><div className="item-meta">DOI: {value(candidate.doi)} · signal: {value(candidate.reason)} · Paper {candidate.id}</div></div>)}</div>}</section>

      <section className="card section-card"><div className="section-heading"><h2>Candidate decisions</h2><span className="count">{detail.resolutions.length} recorded</span></div>{detail.resolutions.length === 0 ? <div className="empty">No create, match, or clear decision has been recorded.</div> : <ol className="item-meta">{detail.resolutions.map((resolution) => <li key={resolution.id}>{resolution.kind}{resolution.paperId ? ` → Paper ${resolution.paperId}` : ""} · sequence {resolution.sequence ?? "not recorded"} · {formatDate(resolution.createdAt)}{resolution.note ? ` · ${resolution.note}` : ""}</li>)}</ol>}</section>

      {proposal && detail.result && <section className="card section-card"><h2>Researcher resolution</h2><p className="hint">Choose an explicit outcome after reviewing the bounded proposal and candidate Papers. Matching never mutates existing Paper metadata.</p>
        <form action={createPaperFromDoiLookupAction} style={{ marginBottom: 16 }}>
          <input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="requestId" value={requestId} /><input type="hidden" name="resultId" value={detail.result.id} /><input type="hidden" name="previewFingerprint" value={detail.resolutionPreview?.fingerprint ?? ""} /><input type="hidden" name="expectedPreviousResolutionId" value={detail.resolutionPreview?.expectedPreviousResolutionId ?? ""} />
          {detail.candidates.map((candidate) => <input key={candidate.id} type="hidden" name="candidatePaperIds" value={candidate.id} />)}
          <div className="field"><label htmlFor="doi-create-title">Canonical title</label><input id="doi-create-title" name="title" defaultValue={proposal.title ?? ""} required /></div>
          <div className="field"><label htmlFor="doi-create-authors">Authors</label><input id="doi-create-authors" name="authors" defaultValue={proposal.authors.join(", ")} /></div>
          <div className="field"><label htmlFor="doi-create-year">Publication year</label><input id="doi-create-year" name="publicationYear" type="number" min="1000" max="3000" defaultValue={proposal.publicationYear ?? ""} /></div>
          <div className="field"><label htmlFor="doi-create-venue">Venue</label><input id="doi-create-venue" name="venue" defaultValue={proposal.venue ?? ""} /></div>
          <div className="field"><label htmlFor="doi-create-doi">DOI</label><input id="doi-create-doi" name="doi" defaultValue={proposal.doi ?? detail.request.doi} required /></div>
          <button className="button" type="submit" disabled={!detail.resolutionPreview}>Create canonical Paper</button>
        </form>
        <form action={matchDoiLookupAction} style={{ marginBottom: 16 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="requestId" value={requestId} /><input type="hidden" name="resultId" value={detail.result.id} /><input type="hidden" name="expectedPreviousResolutionId" value={detail.resolutionPreview?.expectedPreviousResolutionId ?? ""} /><div className="field"><label htmlFor="doi-match-paper">Match existing Paper</label><select id="doi-match-paper" name="paperId" defaultValue="" required><option value="" disabled>Select a candidate Paper…</option>{detail.paperOptions.map((paper) => <option key={paper.id} value={paper.id}>{paper.title} · {paper.id}</option>)}</select></div><button className="button secondary" type="submit">Match existing Paper</button></form>
        <form action={clearDoiLookupResolutionAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="requestId" value={requestId} /><input type="hidden" name="resultId" value={detail.result.id} /><input type="hidden" name="expectedPreviousResolutionId" value={detail.resolutionPreview?.expectedPreviousResolutionId ?? ""} /><button className="button ghost" type="submit">Clear resolution</button></form>
        <div className="support-warning" style={{ marginTop: 12 }}>Current state: {currentResolution ? `latest decision is ${currentResolution.kind}` : "unresolved"}. A later decision appends an immutable resolution event and requires the exact current predecessor.</div></section>}
    </>}
  </div></div>;
}
