import Link from "next/link";
import { notFound } from "next/navigation";
import { recordFullTextRetrievalAttemptAction } from "@/app/actions";
import { reviewServices } from "@/app/server";
import { DomainError } from "@/domain/errors";

const methods = ["publisher", "bibliographic_database", "institutional_access", "library", "interlibrary_loan", "author_contact", "web", "manual", "other"];

export default async function FullTextRetrievalPaperPage({ params, searchParams }: { params: Promise<{ projectId: string; paperId: string }>; searchParams?: Promise<{ error?: string; saved?: string }> }) {
  const { projectId, paperId } = await params;
  const query = searchParams ? await searchParams : {};
  let retrieval;
  try { retrieval = await reviewServices.getPaperFullTextRetrieval(projectId, paperId); } catch (error) { if (error instanceof DomainError && ["PROJECT_NOT_FOUND", "CROSS_PROJECT_REFERENCE", "VALIDATION_ERROR"].includes(error.code)) notFound(); throw error; }
  const canAttempt = retrieval.reviewStatus.titleAbstractState === "included";
  return <main className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">T</span> Tracework</Link><span className="top-note">Evidence-first literature reviews</span></header>
    <div className="container workspace"><Link className="back-link" href={`/projects/${projectId}/screening/full-text/retrieval`}>← Retrieval queue</Link><div className="workspace-header"><div><p className="eyebrow">Full-text retrieval</p><h1>{retrieval.paper.title}</h1><p>{retrieval.paper.authors.join(", ") || "Author details not added"}</p></div><span className="status supported">{retrieval.currentState.replaceAll("_", " ")}</span></div>
      {query.error && <div className="error-banner" role="alert">{query.error}</div>}{query.saved && <div className="success-note" role="status">Retrieval attempt recorded.</div>}
      {!canAttempt && <div className="error-banner" role="status">New retrieval attempts require a current title/abstract include. Existing retrieval and full-text history remains readable.</div>}
      <div className="workspace-grid"><section className="card section-card"><div className="section-heading"><h2>Record retrieval attempt</h2></div><p className="hint">An attempt records whether sufficient material was obtained. It does not store documents or make an eligibility decision.</p><form action={recordFullTextRetrievalAttemptAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><div className="field"><label htmlFor="retrieval-outcome">Outcome</label><select id="retrieval-outcome" name="outcome" defaultValue="retrieved" disabled={!canAttempt}><option value="pending">Pending</option><option value="unavailable">Unavailable</option><option value="retrieved">Retrieved</option></select></div><div className="field"><label htmlFor="retrieval-method">Method <span className="hint">optional</span></label><select id="retrieval-method" name="method" defaultValue="" disabled={!canAttempt}><option value="">Not specified</option>{methods.map((method) => <option key={method} value={method}>{method.replaceAll("_", " ")}</option>)}</select></div><div className="field"><label htmlFor="retrieval-reference">Source reference <span className="hint">optional</span></label><input id="retrieval-reference" name="sourceReference" disabled={!canAttempt} /></div><div className="field"><label htmlFor="retrieval-attempted-at">Attempted at</label><input id="retrieval-attempted-at" type="datetime-local" name="attemptedAt" defaultValue={new Date().toISOString().slice(0, 16)} disabled={!canAttempt} required /></div><div className="field"><label htmlFor="retrieval-note">Note <span className="hint">optional</span></label><textarea id="retrieval-note" name="note" disabled={!canAttempt} /></div><button className="button" type="submit" disabled={!canAttempt}>Record attempt</button></form></section>
      <section className="card section-card"><div className="section-heading"><h2>Retrieval status</h2></div><div className="item-list"><div className="item-row"><span>Current state</span><strong>{retrieval.currentState.replaceAll("_", " ")}</strong></div><div className="item-row"><span>Ever retrieved</span><strong>{retrieval.everRetrieved ? "yes" : "no"}</strong></div><Link className="button ghost" href={`/projects/${projectId}/screening/full-text/${paperId}`}>Full-text screening →</Link></div></section></div>
      <section className="card section-card full"><div className="section-heading"><h2>Retrieval history</h2><span className="count">{retrieval.history.length} {retrieval.history.length === 1 ? "attempt" : "attempts"}</span></div>{retrieval.history.length === 0 ? <div className="empty">No retrieval attempt has been recorded.</div> : <div className="item-list">{retrieval.history.map((attempt) => <article className="item" key={attempt.id}><div className="item-row"><div className="item-title">{attempt.outcome.toUpperCase()}</div>{retrieval.currentAttempt?.id === attempt.id && <span className="status supported">current</span>}</div><div className="item-meta">Sequence {attempt.sequence} · {attempt.attemptedAt.toLocaleString()}{attempt.method ? ` · ${attempt.method.replaceAll("_", " ")}` : ""}</div>{attempt.sourceReference && <div className="item-meta">{attempt.sourceReference}</div>}{attempt.note && <div className="item-meta">{attempt.note}</div>}</article>)}</div>}</section>
    </div></main>;
}
