import Link from "next/link";
import { notFound } from "next/navigation";
import { recordFullTextScreeningDecisionAction } from "@/app/actions";
import { screeningHistoryReadServices } from "@/app/server";
import { DomainError } from "@/domain/errors";

export default async function FullTextScreeningPaperPage({ params, searchParams }: {
  params: Promise<{ projectId: string; paperId: string }>;
  searchParams?: Promise<{ error?: string; saved?: string }>;
}) {
  const { projectId, paperId } = await params;
  const query = searchParams ? await searchParams : {};
  let screening;
  try { screening = await screeningHistoryReadServices.getFullTextScreeningDetail(projectId, paperId); }
  catch (error) { if (error instanceof DomainError && ["PROJECT_NOT_FOUND", "CROSS_PROJECT_REFERENCE", "NOT_FOUND", "VALIDATION_ERROR"].includes(error.code)) notFound(); throw error; }
  const exclusionCriteria = screening.criteria.filter((criterion) => !criterion.archivedAt);
  const canDecide = screening.reviewStatus.titleAbstractState === "included" && screening.reviewStatus.fullTextRetrievalState === "retrieved";
  const decisionHistoryPath = `/projects/${projectId}/screening/full-text/${paperId}/history`;
  const retrievalHistoryPath = `/projects/${projectId}/screening/full-text/retrieval/${paperId}/history`;
  const decisionEventPath = (id: string) => `${decisionHistoryPath}/${id}`;
  const retrievalEventPath = (id: string) => `${retrievalHistoryPath}/${id}`;
  const currentDecisionOutsidePage = screening.currentEvent != null && !screening.history.items.some((item) => item.id === screening.currentEvent?.id);
  const currentRetrievalOutsidePage = screening.retrievalCurrent != null && !screening.retrievalHistory.items.some((item) => item.id === screening.retrievalCurrent?.id);
  return <div className="project-page">
    <div className="container workspace">
      <div className="workspace-header"><div><p className="eyebrow">Full-text screening</p><h1>{screening.paper.title}</h1><p>{screening.paper.authors.join(", ") || "Author details not added"}{screening.paper.publicationYear ? ` · ${screening.paper.publicationYear}` : ""}{screening.paper.venue ? ` · ${screening.paper.venue}` : ""}</p></div><span className={`status screening-${screening.reviewStatus.fullTextState}`}>{screening.reviewStatus.crossStageConflict ? "conflict" : screening.reviewStatus.fullTextState.replaceAll("_", " ")}</span></div>
      {query.error && <div className="error-banner" role="alert">{query.error}</div>}{query.saved && <div className="success-note" role="status">Full-text decision recorded in screening history.</div>}
      {!canDecide && <div className="error-banner" role="status">New full-text decisions require a current title/abstract include and a current retrieved retrieval attempt. This history remains readable, but this Paper is not currently eligible.</div>}
      <div className="workspace-grid">
        <section className="card section-card"><div className="section-heading"><h2>Paper abstract</h2></div>{screening.paper.abstract ? <p className="abstract-text">{screening.paper.abstract}</p> : <div className="empty">No abstract was added for this Paper.</div>}{screening.paper.doi && <p className="item-meta">DOI: {screening.paper.doi}</p>}<Link className="button ghost" href={`/projects/${projectId}/screening/${paperId}`}>Review title/abstract decision →</Link><Link className="button ghost" href={`/projects/${projectId}/screening/full-text/retrieval/${paperId}`}>Full-text retrieval →</Link></section>
        <section className="card section-card"><div className="section-heading"><h2>Record full-text decision</h2></div><p className="hint">Each action adds an immutable full-text history entry. Exclusions require an active full-text criterion.</p><form action={recordFullTextScreeningDecisionAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><input type="hidden" name="decision" value="include" /><div className="field"><label htmlFor="full-text-include-note">Include note <span className="hint">optional</span></label><textarea id="full-text-include-note" name="note" disabled={!canDecide} /></div><button className="button" type="submit" disabled={!canDecide}>Include</button></form><form action={recordFullTextScreeningDecisionAction} style={{ marginTop: 18 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><input type="hidden" name="decision" value="maybe" /><div className="field"><label htmlFor="full-text-maybe-note">Maybe note <span className="hint">optional</span></label><textarea id="full-text-maybe-note" name="note" disabled={!canDecide} /></div><button className="button secondary" type="submit" disabled={!canDecide}>Maybe / uncertain</button></form><form action={recordFullTextScreeningDecisionAction} style={{ marginTop: 18 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><input type="hidden" name="decision" value="exclude" /><div className="field"><label htmlFor="full-text-exclusion-criterion">Exclusion reason <span className="hint">required</span></label><select id="full-text-exclusion-criterion" name="exclusionCriterionId" required defaultValue="" disabled={!canDecide}><option value="" disabled>Select a full-text exclusion criterion</option>{exclusionCriteria.map((criterion) => <option key={criterion.id} value={criterion.id}>{criterion.text}</option>)}</select>{exclusionCriteria.length === 0 && <span className="hint">Create an active full-text criterion first.</span>}</div><div className="field"><label htmlFor="full-text-exclude-note">Exclusion note <span className="hint">optional</span></label><textarea id="full-text-exclude-note" name="note" disabled={!canDecide} /></div><button className="button danger" type="submit" disabled={!canDecide || exclusionCriteria.length === 0}>Confirm exclusion</button></form></section>
        <section className="card section-card full"><div className="section-heading"><h2>Full-text screening history</h2><span className="count">{screening.history.items.length} shown</span></div>{screening.history.items.length === 0 ? <div className="empty">No full-text decision has been recorded.</div> : <div className="item-list">{screening.history.items.map((decision) => <article className="item" key={decision.id}><div className="item-row"><div className="item-title">{decision.decision.toUpperCase()}</div>{decision.isCurrent && <span className="status supported">current</span>}</div>{decision.exclusionCriterion && <div className="item-meta">Reason: {decision.exclusionCriterion.text}{decision.criterionTextTruncated && " (preview shortened)"}{decision.exclusionCriterion.archivedAt && " (criterion archived)"}</div>}{decision.note && <div className="item-meta">{decision.note}{decision.noteTruncated && " (preview shortened)"}</div>}<div className="item-meta">{decision.createdAt.toLocaleString()}</div><Link href={decisionEventPath(decision.id)}>View full event →</Link></article>)}</div>}
          {currentDecisionOutsidePage && screening.currentEvent && <p className="item-meta">Current decision {screening.currentEvent.decision} is outside this page. <Link href={decisionEventPath(screening.currentEvent.id)}>View exact current event →</Link></p>}
          {screening.history.hasMore && screening.history.nextCursor && <p className="pagination"><Link className="button ghost" href={`${decisionHistoryPath}?cursor=${encodeURIComponent(screening.history.nextCursor)}`}>More history →</Link></p>}
          {!screening.history.hasMore && screening.history.items.length > 0 && <p className="item-meta"><Link href={decisionHistoryPath}>Open history view →</Link></p>}
        </section>
      </div>
      <section className="card section-card full"><div className="section-heading"><h2>Retrieval history</h2><span className="count">{screening.retrievalHistory.items.length} shown</span></div><div className="item-meta">Current retrieval state: {screening.reviewStatus.fullTextRetrievalState} · ever retrieved: {screening.reviewStatus.everRetrieved ? "yes" : "no"}</div>{screening.retrievalHistory.items.length === 0 ? <div className="empty">No retrieval attempt has been recorded.</div> : <div className="item-list">{screening.retrievalHistory.items.map((attempt) => <article className="item" key={attempt.id}><div className="item-row"><div className="item-title">{attempt.outcome.toUpperCase()}</div>{attempt.isCurrent && <span className="status supported">current</span>}</div><div className="item-meta">Sequence {attempt.sequence} · {attempt.attemptedAt.toLocaleString()}{attempt.method ? ` · ${attempt.method.replaceAll("_", " ")}` : ""}</div>{attempt.sourceReference && <div className="item-meta">{attempt.sourceReference}{attempt.sourceReferenceTruncated && " (preview shortened)"}</div>}{attempt.note && <div className="item-meta">{attempt.note}{attempt.noteTruncated && " (preview shortened)"}</div>}<Link href={retrievalEventPath(attempt.id)}>View full event →</Link></article>)}</div>}
        {currentRetrievalOutsidePage && screening.retrievalCurrent && <p className="item-meta">Current retrieval attempt {screening.retrievalCurrent.outcome} is outside this page. <Link href={retrievalEventPath(screening.retrievalCurrent.id)}>View exact current attempt →</Link></p>}
        {screening.retrievalHistory.hasMore && screening.retrievalHistory.nextCursor && <p className="pagination"><Link className="button ghost" href={`${retrievalHistoryPath}?cursor=${encodeURIComponent(screening.retrievalHistory.nextCursor)}`}>More retrieval history →</Link></p>}
        {!screening.retrievalHistory.hasMore && screening.retrievalHistory.items.length > 0 && <p className="item-meta"><Link href={retrievalHistoryPath}>Open retrieval history view →</Link></p>}
      </section>
      <p className="footer-note">Historical decisions remain readable even when title/abstract or retrieval state changes. They are then reported as historical/conflicting records, not current operational outcomes.</p>
    </div>
  </div>;
}
