import Link from "next/link";
import { notFound } from "next/navigation";
import { recordFullTextScreeningDecisionAction } from "@/app/actions";
import { reviewServices } from "@/app/server";
import { DomainError } from "@/domain/errors";

export default async function FullTextScreeningPaperPage({ params, searchParams }: {
  params: Promise<{ projectId: string; paperId: string }>;
  searchParams?: Promise<{ error?: string; saved?: string }>;
}) {
  const { projectId, paperId } = await params;
  const query = searchParams ? await searchParams : {};
  let screening;
  try { screening = await reviewServices.getPaperFullTextScreening(projectId, paperId); }
  catch (error) { if (error instanceof DomainError && ["PROJECT_NOT_FOUND", "CROSS_PROJECT_REFERENCE", "VALIDATION_ERROR"].includes(error.code)) notFound(); throw error; }
  const exclusionCriteria = screening.criteria.filter((criterion) => !criterion.archivedAt);
  const canDecide = screening.reviewStatus.titleAbstractState === "included" && screening.reviewStatus.fullTextRetrievalState === "retrieved";
  return <main className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">T</span> Tracework</Link><span className="top-note">Evidence-first literature reviews</span></header>
    <div className="container workspace"><Link className="back-link" href={`/projects/${projectId}/screening/full-text`}>← Full-text queue</Link><div className="workspace-header"><div><p className="eyebrow">Full-text screening</p><h1>{screening.paper.title}</h1><p>{screening.paper.authors.join(", ") || "Author details not added"}{screening.paper.publicationYear ? ` · ${screening.paper.publicationYear}` : ""}{screening.paper.venue ? ` · ${screening.paper.venue}` : ""}</p></div><span className={`status screening-${screening.currentState}`}>{screening.reviewStatus.crossStageConflict ? "conflict" : screening.currentState.replaceAll("_", " ")}</span></div>
      {query.error && <div className="error-banner" role="alert">{query.error}</div>}{query.saved && <div className="success-note" role="status">Full-text decision recorded in screening history.</div>}
      {!canDecide && <div className="error-banner" role="status">New full-text decisions require a current title/abstract include and a current retrieved retrieval attempt. This history remains readable, but this Paper is not currently eligible.</div>}
      <div className="workspace-grid"><section className="card section-card"><div className="section-heading"><h2>Paper abstract</h2></div>{screening.paper.abstract ? <p className="abstract-text">{screening.paper.abstract}</p> : <div className="empty">No abstract was added for this Paper.</div>}{screening.paper.doi && <p className="item-meta">DOI: {screening.paper.doi}</p>}<Link className="button ghost" href={`/projects/${projectId}/screening/${paperId}`}>Review title/abstract decision →</Link><Link className="button ghost" href={`/projects/${projectId}/screening/full-text/retrieval/${paperId}`}>Full-text retrieval →</Link></section>
      <section className="card section-card"><div className="section-heading"><h2>Record full-text decision</h2></div><p className="hint">Each action adds an immutable full-text history entry. Exclusions require an active full-text criterion.</p><form action={recordFullTextScreeningDecisionAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><input type="hidden" name="decision" value="include" /><div className="field"><label htmlFor="full-text-include-note">Include note <span className="hint">optional</span></label><textarea id="full-text-include-note" name="note" disabled={!canDecide} /></div><button className="button" type="submit" disabled={!canDecide}>Include</button></form><form action={recordFullTextScreeningDecisionAction} style={{ marginTop: 18 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><input type="hidden" name="decision" value="maybe" /><div className="field"><label htmlFor="full-text-maybe-note">Maybe note <span className="hint">optional</span></label><textarea id="full-text-maybe-note" name="note" disabled={!canDecide} /></div><button className="button secondary" type="submit" disabled={!canDecide}>Maybe / uncertain</button></form><form action={recordFullTextScreeningDecisionAction} style={{ marginTop: 18 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="paperId" value={paperId} /><input type="hidden" name="decision" value="exclude" /><div className="field"><label htmlFor="full-text-exclusion-criterion">Exclusion reason <span className="hint">required</span></label><select id="full-text-exclusion-criterion" name="exclusionCriterionId" required defaultValue="" disabled={!canDecide}><option value="" disabled>Select a full-text exclusion criterion</option>{exclusionCriteria.map((criterion) => <option key={criterion.id} value={criterion.id}>{criterion.text}</option>)}</select>{exclusionCriteria.length === 0 && <span className="hint">Create an active full-text criterion first.</span>}</div><div className="field"><label htmlFor="full-text-exclude-note">Exclusion note <span className="hint">optional</span></label><textarea id="full-text-exclude-note" name="note" disabled={!canDecide} /></div><button className="button danger" type="submit" disabled={!canDecide || exclusionCriteria.length === 0}>Confirm exclusion</button></form></section>
      <section className="card section-card full"><div className="section-heading"><h2>Full-text screening history</h2><span className="count">{screening.history.length} {screening.history.length === 1 ? "decision" : "decisions"}</span></div>{screening.history.length === 0 ? <div className="empty">No full-text decision has been recorded.</div> : <div className="item-list">{screening.history.map((decision) => <article className="item" key={decision.id}><div className="item-row"><div className="item-title">{decision.decision.toUpperCase()}</div>{screening.currentDecision?.id === decision.id && <span className="status supported">current</span>}</div>{decision.exclusionCriterion && <div className="item-meta">Reason: {decision.exclusionCriterion.text}{decision.exclusionCriterion.archivedAt ? " (criterion archived)" : ""}</div>}{decision.note && <div className="item-meta">{decision.note}</div>}<div className="item-meta">{decision.createdAt.toLocaleString()}</div></article>)}</div>}</section></div>
      <section className="card section-card full"><div className="section-heading"><h2>Retrieval history</h2><span className="count">{screening.retrievalHistory.length} {screening.retrievalHistory.length === 1 ? "attempt" : "attempts"}</span></div><div className="item-meta">Current retrieval state: {screening.reviewStatus.fullTextRetrievalState} · ever retrieved: {screening.reviewStatus.everRetrieved ? "yes" : "no"}</div>{screening.retrievalHistory.length === 0 ? <div className="empty">No retrieval attempt has been recorded.</div> : <div className="item-list">{screening.retrievalHistory.map((attempt) => <article className="item" key={attempt.id}><div className="item-row"><div className="item-title">{attempt.outcome.toUpperCase()}</div>{screening.retrievalCurrent?.id === attempt.id && <span className="status supported">current</span>}</div><div className="item-meta">Sequence {attempt.sequence} · {attempt.attemptedAt.toLocaleString()}{attempt.method ? ` · ${attempt.method.replaceAll("_", " ")}` : ""}</div>{attempt.sourceReference && <div className="item-meta">{attempt.sourceReference}</div>}{attempt.note && <div className="item-meta">{attempt.note}</div>}</article>)}</div>}</section>
      <p className="footer-note">Historical decisions remain readable even when title/abstract or retrieval state changes. They are then reported as historical/conflicting records, not current operational outcomes.</p>
    </div></main>;
}
