import Link from "next/link";
import { notFound } from "next/navigation";
import { inspectPdfIntakeAction, resolvePdfIntakeAction } from "@/app/actions";
import { DomainError } from "@/domain/errors";
import { reviewServices } from "@/app/server";

export default async function PdfIntakeDetailPage({ params, searchParams }: { params: Promise<{ projectId: string; intakeId: string }>; searchParams?: Promise<{ error?: string; saved?: string }> }) {
  const { projectId, intakeId } = await params;
  const query = searchParams ? await searchParams : {};
  let intake;
  try { intake = await reviewServices.getPdfIntake(projectId, intakeId); }
  catch (error) { if (error instanceof DomainError && ["NOT_FOUND", "PROJECT_NOT_FOUND", "VALIDATION_ERROR"].includes(error.code)) notFound(); throw error; }
  if (!intake) notFound();
  const papers = await reviewServices.listPapers(projectId);
  const proposal = intake.proposal;
  const lowInformationTitle = intake.fields.find((field) => field.field === "title" && field.diagnostic === "low_information_embedded_title");
  const hasSignals = intake.candidates.length > 0 || intake.exactDocumentMatches.length > 0;
  return <div className="project-page"><div className="container workspace"><div className="workspace-header"><div><p className="eyebrow">Staged source artifact</p><h1>{intake.originalFilename}</h1><p className="hint">{intake.byteSize} bytes · SHA-256 {intake.sha256}</p></div><span className="status">{intake.state}</span></div>
    {query.error && <div className="error-banner" role="alert">{query.error}</div>}{query.saved && <div className="success-note" role="status">{query.saved === "inspected" ? "Metadata inspection completed." : "Resolution recorded."}</div>}
    {!intake.metadataResult && <section className="card section-card"><h2>Metadata inspection pending</h2><p className="hint">The PDF bytes are durable. Inspection is a separate explicit action so a process crash cannot strand the intake.</p><form action={inspectPdfIntakeAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="intakeId" value={intakeId} /><button className="button" type="submit">Inspect metadata</button></form></section>}
    {intake.metadataResult && <section className="card section-card"><h2>Metadata proposal</h2><p className="hint">This is deterministic intake metadata, not canonical Paper metadata. Producer/parser failures remain reviewable.</p><div className="item-meta">Result {intake.metadataResult.sequenceNo} · {intake.metadataResult.status} · {intake.metadataResult.extractorKey} {intake.metadataResult.extractorVersion} · PDF.js {intake.metadataResult.pdfjsVersion ?? "unknown"}</div>{intake.metadataResult.errorMessage && <div className="error-banner" role="alert">{intake.metadataResult.errorCode ? `${intake.metadataResult.errorCode}: ` : ""}{intake.metadataResult.errorMessage}</div>}{intake.metadataResult.diagnostics.length > 0 && <ul className="item-meta">{intake.metadataResult.diagnostics.map((diagnostic, index) => <li key={`${diagnostic}-${index}`}>{diagnostic}</li>)}</ul>}<div className="item-list">{intake.fields.map((field, index) => <div className="item" key={`${field.field}-${index}`}><div className="item-row"><div><strong>{field.field}</strong><div className="item-meta">{field.value == null ? "Unavailable" : Array.isArray(field.value) ? field.value.join(" · ") : String(field.value)}</div><div className="item-meta">{field.classification}{field.sourceKind ? ` · ${field.sourceKind}` : ""}{field.sourceLocator ? ` · ${field.sourceLocator}` : ""}</div>{field.pageNumber != null && <div className="item-meta">Page {field.pageNumber}, code points [{field.startOffset}, {field.endOffset}) · algorithm {intake.metadataResult?.textScanVersion}</div>}{field.diagnostic && <div className="support-warning">{field.diagnostic}</div>}</div></div></div>)}</div></section>}
    {intake.metadataResult && <><section className="card section-card"><h2>Candidate Papers</h2>{intake.candidates.length === 0 ? <div className="empty">No exact DOI/title candidate was found.</div> : <div className="item-list">{intake.candidates.map((candidate) => <div className="item" key={candidate.id}><div className="item-title">{candidate.title}</div><div className="item-meta">{candidate.candidateReason} · Paper {candidate.id}</div><div className="item-meta">{candidate.authors.join(", ") || "Authors absent"}{candidate.publicationYear ? ` · ${candidate.publicationYear}` : ""}{candidate.venue ? ` · ${candidate.venue}` : ""}</div></div>)}</div>}{intake.exactDocumentMatches.length > 0 && <><h3>Exact-content document matches</h3><div className="item-list">{intake.exactDocumentMatches.map((document) => <div className="item" key={document.id}><div className="item-meta">Paper {document.paperId} · {document.paperTitle} · {document.active ? "active" : "archived"}</div><div className="item-meta">Document {document.id}</div></div>)}</div></>}</section>
      {intake.state === "resolved" ? <section className="card section-card"><h2>Resolved</h2><p className="hint">This intake has been materialized once and cannot be cleared or retargeted.</p>{intake.resolutionPaperId && <Link className="button" href={`/projects/${projectId}/papers/${intake.resolutionPaperId}/documents/${intake.resolutionDocumentId ?? ""}`}>Open canonical document</Link>}</section> : <><section className="card section-card"><h2>Create canonical Paper</h2><p className="hint">Edit the final payload below. The submitted values are validated by the ordinary Paper writer. Leave fields blank rather than guessing.</p><form action={resolvePdfIntakeAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="intakeId" value={intakeId} /><input type="hidden" name="resolutionKind" value="create_paper" /><div className="field"><label htmlFor="intake-title">Title</label>{lowInformationTitle && <p className="support-warning">Embedded title proposal &ldquo;{String(lowInformationTitle.value ?? "")}&rdquo; is low-information; enter the canonical title manually.</p>}<input id="intake-title" name="title" defaultValue={proposal.title} required /></div><div className="field"><label htmlFor="intake-authors">Authors <span className="hint">one per line</span></label><textarea id="intake-authors" name="authors" defaultValue={(proposal.authors ?? []).join("\n")} /></div><div className="field"><label htmlFor="intake-year">Publication year</label><input id="intake-year" name="publicationYear" type="number" min="1000" max="3000" defaultValue={proposal.publicationYear ?? ""} /></div><div className="field"><label htmlFor="intake-venue">Venue</label><input id="intake-venue" name="venue" defaultValue={proposal.venue ?? ""} /></div><div className="field"><label htmlFor="intake-doi">DOI</label><input id="intake-doi" name="doi" defaultValue={proposal.doi ?? ""} /></div><div className="field"><label htmlFor="intake-abstract">Abstract</label><textarea id="intake-abstract" name="abstract" defaultValue={proposal.abstract ?? ""} /></div>{hasSignals && <label className="checkbox"><input type="checkbox" name="distinctPaperAcknowledged" required /> I reviewed the candidate and exact-content signals and confirm this should be a distinct canonical Paper.</label>}<button className="button" type="submit">Create Paper and attach PDF</button></form></section>
      <section className="card section-card"><h2>Match an existing Paper</h2><p className="hint">Matching attaches the exact staged bytes and does not change the selected Paper’s metadata.</p><form action={resolvePdfIntakeAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="intakeId" value={intakeId} /><input type="hidden" name="resolutionKind" value="match_paper" /><div className="field"><label htmlFor="intake-paper">Paper</label><select id="intake-paper" name="paperId" required defaultValue=""><option value="" disabled>Select a Paper…</option>{papers.map((paper) => <option key={paper.id} value={paper.id}>{paper.title}{paper.publicationYear ? ` · ${paper.publicationYear}` : ""}</option>)}</select></div><button className="button secondary" type="submit">Attach to existing Paper</button></form></section></>}
    </>}
  </div></div>;
}
