import Link from "next/link";
import { notFound } from "next/navigation";
import { linkEvidenceAction, reactivateClaimAction, reviseClaimAction, unlinkEvidenceAction, withdrawClaimAction } from "@/app/actions";
import { DomainError } from "@/domain/errors";
import { reviewServices } from "@/app/server";
import { normalizeClaim, normalizeExtraction, normalizeHistory, normalizeSynthesis, type ClaimReadServices, type ClaimRevisionView, type ClaimSupportView, type EvidenceView, type PaperView } from "../model";

const services = reviewServices as unknown as ClaimReadServices;

async function currentClaim(projectId: string, claimId: string) {
  if (services.getCurrentClaim) return normalizeClaim(await services.getCurrentClaim(projectId, claimId));
  return normalizeClaim(await services.getClaimProvenance?.(projectId, claimId));
}

async function history(projectId: string, claimId: string, current: ClaimRevisionView) {
  if (services.getClaimHistory) return normalizeHistory(await services.getClaimHistory(projectId, claimId));
  return [current];
}

async function supportOptions(projectId: string) {
  if (services.listClaimSupportOptions) {
    const raw = await services.listClaimSupportOptions(projectId);
    const value = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
    return { evidence: Array.isArray(value.evidence) ? value.evidence : [], extraction: Array.isArray(value.extraction ?? value.extractions) ? (value.extraction ?? value.extractions) as unknown[] : [], synthesis: Array.isArray(value.synthesis ?? value.syntheses) ? (value.synthesis ?? value.syntheses) as unknown[] : [] };
  }
  const [evidence, extraction, synthesis] = await Promise.all([
    services.listEvidence?.(projectId) ?? Promise.resolve([]),
    services.listProjectExtractionRevisions?.(projectId) ?? Promise.resolve([]),
    services.listProjectSynthesisRevisions?.(projectId) ?? services.listProjectSynthesis?.(projectId) ?? Promise.resolve([]),
  ]);
  return { evidence: Array.isArray(evidence) ? evidence : [], extraction: Array.isArray(extraction) ? extraction : [], synthesis: Array.isArray(synthesis) ? synthesis : [] };
}

function evidenceOption(value: unknown, papers: Map<string, PaperView>): EvidenceView {
  const row = value && typeof value === "object" ? value as Record<string, unknown> : {};
  const paperValue = row.paper && typeof row.paper === "object" ? row.paper as Record<string, unknown> : {};
  const paperId = typeof row.paperId === "string" ? row.paperId : typeof paperValue.id === "string" ? paperValue.id : "";
  return { id: String(row.id ?? ""), sourceText: typeof row.sourceText === "string" ? row.sourceText : "", pageNumber: typeof row.pageNumber === "number" ? row.pageNumber : 0, note: typeof row.note === "string" ? row.note : null, paper: papers.get(paperId) };
}

function paperFrom(value: unknown): PaperView | undefined {
  const row = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return typeof row.id === "string" ? { id: row.id, title: typeof row.title === "string" ? row.title : "Untitled paper", doi: typeof row.doi === "string" ? row.doi : null } : undefined;
}

function supportIds(current: ClaimRevisionView) { return { evidence: new Set(current.supports.evidence.map((item) => item.id)), extraction: new Set(current.supports.extraction.map((item) => item.id)), synthesis: new Set(current.supports.synthesis.map((item) => item.id)) }; }

function freshnessLabel(support: ClaimSupportView) {
  if (support.kind === "extraction" && support.extraction && support.extraction.isCurrent === false) return <span className="status stale">Superseded extraction</span>;
  if (support.kind === "synthesis" && support.synthesis && support.synthesis.isCurrent === false) return <span className="status stale">Superseded synthesis</span>;
  return null;
}

function SupportEvidence({ support }: { support: ClaimSupportView }) {
  const item = support.evidence;
  if (!item) return null;
  return <article className="item support-item"><div className="support-kind">Supporting Evidence</div><p className="quote">“{item.sourceText}”</p><div className="item-meta"><span>Page {item.pageNumber}</span>{item.paper ? <> · <span className="paper-chip">{item.paper.title}</span></> : null}</div>{item.note && <div className="item-meta">Researcher note: {item.note}</div>}</article>;
}

function SupportExtraction({ support }: { support: ClaimSupportView }) {
  const item = support.extraction;
  if (!item) return null;
  return <article className="item support-item"><div className="item-row"><div className="support-kind">Supporting extracted observation</div><div style={{ display: "flex", gap: 6 }}>{freshnessLabel(support)}{item.paperScreeningState === "excluded" && <span className="status stale">Paper excluded</span>}</div></div><div className="item-title">{item.field?.name ?? "Extraction observation"} · {item.paper?.title ?? "Source paper"}</div><div className="extraction-value-display">{item.textValue ?? item.numberValue ?? (item.booleanValue === null || item.booleanValue === undefined ? item.optionId : item.booleanValue ? "Yes" : "No") ?? item.valueState ?? "No value"}</div><div className="item-meta">Extraction revision {item.sequence || "—"} · {item.evidence.length} source {item.evidence.length === 1 ? "passage" : "passages"}</div>{item.evidence.length > 0 && <div className="provenance-list">{item.evidence.map((evidence) => <div className="quote quote-inline" key={evidence.id}>“{evidence.sourceText}” <span className="item-meta">· Page {evidence.pageNumber}</span></div>)}</div>}{item.evidence.length === 0 && <div className="support-warning">Structural support only — no Evidence path reaches a citation.</div>}</article>;
}

function SupportSynthesis({ support }: { support: ClaimSupportView }) {
  const item = support.synthesis;
  if (!item) return null;
  return <article className="item support-item"><div className="item-row"><div className="support-kind">Supporting synthesis</div>{freshnessLabel(support)}</div><p className="synthesis-statement">{item.statementText ?? "Synthesis withdrawn"}</p><div className="item-meta">Synthesis revision {item.sequence || "—"} · {item.extractions.length} supporting observation{item.extractions.length === 1 ? "" : "s"}</div><div className="provenance-list">{item.extractions.map((extraction) => <div className="nested-support" key={extraction.id}><div className="item-title">{extraction.field?.name ?? "Observation"} · {extraction.paper?.title ?? "Source paper"}{extraction.isCurrent === false && <span className="status stale">Superseded extraction</span>}</div><div className="item-meta">{extraction.textValue ?? extraction.numberValue ?? extraction.valueState ?? "No value"} · {extraction.evidence.length} Evidence {extraction.evidence.length === 1 ? "passage" : "passages"}</div>{extraction.evidence.map((evidence) => <div className="quote quote-inline" key={evidence.id}>“{evidence.sourceText}” <span className="item-meta">· Page {evidence.pageNumber}</span></div>)}</div>)}{item.extractions.length === 0 && <div className="support-warning">No underlying observations are attached to this synthesis revision.</div>}</div></article>;
}

function SupportPicker({ current, options, papers, mode }: { current: ClaimRevisionView; options: Awaited<ReturnType<typeof supportOptions>>; papers: Map<string, PaperView>; mode: "revise" | "reactivate" }) {
  const selected = mode === "revise" ? supportIds(current) : { evidence: new Set<string>(), extraction: new Set<string>(), synthesis: new Set<string>() };
  const extractionOptions = options.extraction.map((value) => normalizeExtraction(value)).filter((item) => item.id);
  const synthesisOptions = options.synthesis.map((value) => normalizeSynthesis(value)).filter((item) => item.id);
  const evidenceOptions = options.evidence.map((value) => evidenceOption(value, papers)).filter((item) => item.id);
  return <div className="support-picker"><fieldset><legend>Supporting Evidence <span className="hint">optional</span></legend>{evidenceOptions.length === 0 ? <p className="hint">No Evidence records are available.</p> : evidenceOptions.map((item) => <label className="checkbox-row" key={item.id}><input type="checkbox" name="evidenceIds" value={item.id} defaultChecked={selected.evidence.has(item.id)} /><span>{item.paper?.title ?? "Source paper"} · page {item.pageNumber}<small>{item.sourceText.slice(0, 120)}{item.sourceText.length > 120 ? "…" : ""}</small></span></label>)}</fieldset><fieldset><legend>Supporting extracted observations <span className="hint">finalized revisions only</span></legend>{extractionOptions.length === 0 ? <p className="hint">No finalized ExtractionRevisions are available.</p> : extractionOptions.map((item) => <label className="checkbox-row" key={item.id}><input type="checkbox" name="extractionRevisionIds" value={item.id} defaultChecked={selected.extraction.has(item.id)} /><span>{item.field?.name ?? "Observation"} · {item.paper?.title ?? "Source paper"}<small>Revision {item.sequence || "—"} · {item.evidence.length} Evidence {item.isCurrent === false ? "· superseded" : ""}</small></span></label>)}</fieldset><fieldset><legend>Supporting syntheses <span className="hint">active finalized revisions only</span></legend>{synthesisOptions.length === 0 ? <p className="hint">No finalized synthesis revisions are available.</p> : synthesisOptions.map((item) => <label className="checkbox-row" key={item.id}><input type="checkbox" name="synthesisRevisionIds" value={item.id} defaultChecked={selected.synthesis.has(item.id)} /><span>{item.title ?? "Synthesis conclusion"}<small>Revision {item.sequence || "—"} · {item.extractions.length} observations · {item.evidence.length} Evidence {item.evidence.length === 1 ? "passage" : "passages"}</small></span></label>)}</fieldset></div>;
}

export default async function ClaimDetailPage({ params, searchParams }: { params: Promise<{ projectId: string; claimId: string }>; searchParams?: Promise<{ error?: string; saved?: string }> }) {
  const { projectId, claimId } = await params;
  const query = searchParams ? await searchParams : {};
  let project;
  let claim;
  try { [project, claim] = await Promise.all([reviewServices.getProject(projectId), currentClaim(projectId, claimId)]); } catch (error) { if (error instanceof DomainError && ["PROJECT_NOT_FOUND", "CROSS_PROJECT_REFERENCE", "VALIDATION_ERROR", "NOT_FOUND"].includes(error.code)) notFound(); throw error; }
  const [claimHistory, rawPapers, rawOptions] = await Promise.all([history(projectId, claimId, claim.currentRevision), services.listPapers?.(projectId) ?? Promise.resolve([]), supportOptions(projectId)]);
  const papers = new Map((Array.isArray(rawPapers) ? rawPapers : []).map((value) => { const row = paperFrom(value); return row ? [row.id, row] as const : null; }).filter((value): value is readonly [string, PaperView] => value !== null));
  const current = claim.currentRevision;
  const allSupports = [...current.supports.evidence, ...current.supports.extraction, ...current.supports.synthesis];
  const structuralPaperCount = current.distinctPaperCount || new Set(allSupports.map((item) => item.paper?.id ?? item.evidence?.paper?.id ?? item.extraction?.paper?.id).filter(Boolean)).size;
  const canEdit = current.state === "active";
  return <main className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">T</span> Tracework</Link><span className="top-note">Evidence-first literature reviews</span></header>
    <div className="container workspace"><Link className="back-link" href={`/projects/${projectId}/claims`}>← {project.title} Claims</Link>
      <div className="workspace-header"><div><p className="eyebrow">Claim history</p><h1>{current.claimText ?? "Claim withdrawn"}</h1><p>Revision {current.sequence} · exact support snapshot · {structuralPaperCount} reachable {structuralPaperCount === 1 ? "Paper" : "Papers"}</p></div><span className={`status ${current.state === "withdrawn" ? "withdrawn" : current.supportStatus}`}>{current.state === "withdrawn" ? "Withdrawn" : current.supportStatus === "supported" ? "● Supported" : "○ Unsupported"}<span className="visually-hidden">{current.state === "withdrawn" ? "withdrawn" : current.supportStatus}</span></span></div>
      {query.error && <div className="error-banner" role="alert">{query.error}</div>}{query.saved && <div className="success-note" role="status">{query.saved === "revised" ? "New Claim revision saved." : query.saved === "withdrawn" ? "Claim withdrawn. Historical support remains available." : query.saved === "reactivated" ? "Claim reactivated with an explicit support snapshot." : "Claim saved."}</div>}
      <div className="workspace-grid"><section className="card section-card full"><div className="section-heading"><h2>Claim assertion</h2><span className="count">Revision {current.sequence}</span></div><p className="claim-assertion">{current.claimText ?? "This Claim has been withdrawn."}</p>{current.researcherNote && <p className="item-meta">Researcher note: {current.researcherNote}</p>}<div className="support-summary"><span><strong>{allSupports.length}</strong> supports</span><span><strong>{current.supports.evidence.length}</strong> Evidence</span><span><strong>{current.supports.extraction.length}</strong> observations</span><span><strong>{current.supports.synthesis.length}</strong> syntheses</span><span><strong>{current.citationCandidateCount}</strong> citation candidates</span></div></section>
        <section className="card section-card full"><div className="section-heading"><h2>Exact support snapshot</h2><span className="count">{allSupports.length} supporting {allSupports.length === 1 ? "object" : "objects"}</span></div>{allSupports.length === 0 ? <div className="empty">This active Claim is unsupported. Add exact research support by creating a new revision.<p className="compatibility-copy">This claim has no supporting evidence yet.</p></div> : <div className="provenance-list support-sections">{current.supports.evidence.map((support) => <SupportEvidence key={support.id} support={support} />)}{current.supports.extraction.map((support) => <SupportExtraction key={support.id} support={support} />)}{current.supports.synthesis.map((support) => <SupportSynthesis key={support.id} support={support} />)}</div>}</section>
        {canEdit && <section className="card section-card full"><div className="section-heading"><h2>Direct Evidence link</h2><span className="count">Compatibility shortcut</span></div><form action={linkEvidenceAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="claimId" value={claimId} /><div className="field"><label htmlFor="link-evidence">Evidence passage</label><select id="link-evidence" name="evidenceId" required defaultValue=""><option value="" disabled>Select Evidence</option>{rawOptions.evidence.map((value) => { const item = evidenceOption(value, papers); return <option key={item.id} value={item.id}>{item.sourceText.slice(0, 100)} · page {item.pageNumber}</option>; })}</select></div><button className="button secondary" type="submit">Link evidence</button></form>{current.supports.evidence.map((support) => <form key={support.id} action={unlinkEvidenceAction} style={{ marginTop: 10 }}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="claimId" value={claimId} /><input type="hidden" name="evidenceId" value={support.id} /><button className="button ghost" type="submit">Unlink</button></form>)}</section>}
        <section className="card section-card"><div className="section-heading"><h2>Citation candidates</h2><span className="count">{current.citationCandidateCount} grounded</span></div><p className="hint">Only exact paths reaching Evidence produce candidates. Papers are deduplicated by Paper identity, not DOI.</p>{current.citationCandidates.length === 0 ? <div className="empty">No citation candidates yet. Structural support without Evidence remains visible above but does not create a citation.</div> : <div className="item-list">{current.citationCandidates.map((candidate) => <article className="item" key={candidate.paper.id}><div className="item-row"><div><div className="item-title">{candidate.paper.title}</div><div className="item-meta">{candidate.paper.authors?.join(", ") || "Author details not added"}{candidate.paper.publicationYear ? ` · ${candidate.paper.publicationYear}` : ""}{candidate.paper.venue ? ` · ${candidate.paper.venue}` : ""}</div>{candidate.paper.doi && <div className="item-meta">DOI: {candidate.paper.doi}</div>}</div><span className="status supported">{candidate.pathCount} {candidate.pathCount === 1 ? "support path" : "support paths"}</span></div>{candidate.paths && <div className="path-list">{candidate.paths.map((path, index) => <span key={index}>{typeof path === "string" ? path : path.label ?? path.kind ?? "Evidence path"}</span>)}</div>}</article>)}</div>}</section>
        <section className="card section-card"><div className="section-heading"><h2>{canEdit ? "Create a new revision" : "Reactivate Claim"}</h2><span className="count">Complete snapshot</span></div><p className="hint">{canEdit ? "Changing text, note, lifecycle, or support always creates an immutable revision. Existing support is preselected by exact target ID." : "Reactivation never restores support implicitly. Choose the text and every support target explicitly."}</p>{canEdit ? <form action={reviseClaimAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="claimId" value={claimId} /><input type="hidden" name="expectedCurrentRevisionId" value={current.id} /><div className="field"><label htmlFor="revision-claim-text">Claim text</label><textarea id="revision-claim-text" name="claimText" required defaultValue={current.claimText ?? ""} /></div><div className="field"><label htmlFor="revision-claim-note">Researcher note <span className="hint">optional</span></label><textarea id="revision-claim-note" name="researcherNote" defaultValue={current.researcherNote ?? ""} /></div><SupportPicker current={current} options={rawOptions} papers={papers} mode="revise" /><button className="button" type="submit">Save new Claim revision</button></form> : <form action={reactivateClaimAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="claimId" value={claimId} /><input type="hidden" name="expectedCurrentRevisionId" value={current.id} /><div className="field"><label htmlFor="reactivate-claim-text">Claim text</label><textarea id="reactivate-claim-text" name="claimText" required placeholder="Restate the active manuscript assertion" /></div><div className="field"><label htmlFor="reactivate-claim-note">Researcher note <span className="hint">optional</span></label><textarea id="reactivate-claim-note" name="researcherNote" /></div><SupportPicker current={current} options={rawOptions} papers={papers} mode="reactivate" /><button className="button" type="submit">Reactivate Claim</button></form>}</section>
        {canEdit && <section className="card section-card"><div className="section-heading"><h2>Withdraw Claim</h2><span className="count">Preserves history</span></div><p className="hint">Withdrawal creates an immutable revision with no active text or support. The historical assertion and citation provenance remain readable.</p><form action={withdrawClaimAction}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="claimId" value={claimId} /><input type="hidden" name="expectedCurrentRevisionId" value={current.id} /><div className="field"><label htmlFor="withdraw-claim-note">Withdrawal note <span className="hint">optional</span></label><textarea id="withdraw-claim-note" name="researcherNote" placeholder="Why is this Claim being withdrawn?" /></div><button className="button secondary" type="submit">Withdraw Claim</button></form></section>}
        <section className="card section-card full"><div className="section-heading"><h2>Complete Claim history</h2><span className="count">{claimHistory.length} revisions</span></div><div className="item-list">{claimHistory.slice().sort((a, b) => b.sequence - a.sequence).map((revision) => { const count = revision.supports.evidence.length + revision.supports.extraction.length + revision.supports.synthesis.length; return <article className="item history-item" key={revision.id}><div className="item-row"><div><div className="item-title">Revision {revision.sequence} · {revision.state === "withdrawn" ? "Withdrawn" : revision.supportStatus === "supported" ? "Supported" : "Unsupported"}</div><div className="item-meta">{revision.claimText ?? "Claim withdrawn"}</div></div><span className="status">{count} supports · {revision.citationCandidateCount} citations</span></div>{revision.researcherNote && <div className="item-meta">Note: {revision.researcherNote}</div>}<div className="item-meta">Exact targets are retained; later research revisions do not retarget this history.</div></article>; })}</div></section>
      </div><p className="footer-note">This audit trail remains exact: Claim → typed support → historical revision/Evidence → Paper.</p>
    </div></main>;
}
