/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { notFound } from "next/navigation";
import { DomainError } from "@/domain/errors";
import { reviewServices } from "@/app/server";

export default async function ManuscriptSnapshotPage({ params, searchParams }: { params: Promise<{ projectId: string; snapshotId: string }>; searchParams?: Promise<{ manuscriptId?: string }> }) {
  const { projectId, snapshotId } = await params; const query = searchParams ? await searchParams : {}; const manuscriptId = query.manuscriptId;
  if (!manuscriptId) notFound();
  try {
    const snapshot = await (reviewServices as any).getManuscriptSnapshot(projectId, manuscriptId, snapshotId);
    return <main className="shell"><div className="container workspace"><Link className="back-link" href={`/projects/${projectId}/manuscript/snapshots?manuscriptId=${manuscriptId}`}>← Snapshot history</Link><div className="workspace-header"><div><p className="eyebrow">Snapshot {snapshot.sequence}</p><h1>{snapshot.title}</h1><p>{snapshot.citationStyle} citations · captured {new Date(snapshot.capturedAt).toISOString()}</p></div><Link className="button" href={`/projects/${projectId}/manuscript/snapshots/${snapshotId}/export?manuscriptId=${manuscriptId}`}>Export Markdown</Link></div>{snapshot.warnings.length ? <div className="notice">{snapshot.warnings.length} warnings were captured with this milestone.</div> : null}<div>{snapshot.sections.map((section: any) => <section className="card section-card full" key={section.id}><div className="section-heading"><h2>{section.title}</h2><span className="count">{section.section_type} · Section {section.source_section_id}</span></div><div className="item-list">{snapshot.items.filter((item: any) => item.snapshot_section_id === section.id).map((item: any) => <div className="item" key={item.id}><div className="item-row"><div><div className="item-title">{item.item_type === "prose" ? item.prose_text : item.claim_text ?? ""}</div><div className="item-meta">SectionItem {item.source_section_item_id} · {item.item_type === "prose" ? `ProseBlock ${item.source_prose_block_id} · ProseRevision ${item.prose_revision_id}` : `Claim ${item.claim_id} · ClaimRevision ${item.claim_revision_id} · Placement ${item.placement_id}`}{item.rendered_citation_marker ? ` ${item.rendered_citation_marker}` : ""}</div></div></div></div>)}</div></section>)}</div>{snapshot.warnings.length ? <section className="card section-card full"><div className="section-heading"><h2>Captured warnings</h2><span className="count">Presentation facts at capture</span></div><div className="item-list">{snapshot.warnings.map((warning: any) => <div className="support-warning" key={warning.id}>{warning.code}: {warning.message}{warning.metadata_field ? ` · ${warning.metadata_field}` : ""}</div>)}</div></section> : null}<section className="card section-card full"><div className="section-heading"><h2>Frozen bibliography</h2></div><div className="item-list">{snapshot.bibliography.map((entry: any) => <div className="item" key={entry.id}><div className="item-row"><div><div className="item-title">{entry.title}</div><div className="item-meta">Paper {entry.paper_id} · {entry.rendered_reference}</div></div><span className="status supported">Citation {entry.citation_number} · display {entry.bibliography_position + 1}</span></div></div>)}</div></section></div></main>;
  } catch (error) { if (error instanceof DomainError && ["PROJECT_NOT_FOUND", "NOT_FOUND", "CROSS_PROJECT_REFERENCE"].includes(error.code)) notFound(); throw error; }
}
