/* eslint-disable @typescript-eslint/no-explicit-any */
import { and, eq, sql } from "drizzle-orm";
import { z } from "zod";
import type { Database } from "@/db/client";
import { papers, projects, retrievedRecords, researchQuestions, searchRuns, searchSources } from "@/db/schema";
import { DomainError, isConstraintError } from "@/domain/errors";
import { SEARCH_SOURCE_DEFINITIONS, normalizeDoiForComparison, normalizeTitleForComparison } from "@/domain/search-normalization";
import { createPaperSchema, createProjectSchema, idSchema } from "@/domain/validation";
import { ResearchQuestionRepository, RetrievedRecordRepository, SearchRunRepository, SearchSourceRepository, SearchStrategyRepository } from "./acquisition-repositories";

const sourceInput = z.object({ sourceKey: z.string().trim().min(1).max(200), displayName: z.string().trim().min(1).max(500), baseUrl: z.string().trim().min(1).max(2000).nullable().optional(), notes: z.string().trim().min(1).max(10000).nullable().optional() });
const sourceUpdate = sourceInput.partial();
const questionInput = z.object({ identifier: z.string().trim().min(1).max(100), label: z.string().trim().min(1).max(10000) });
const questionUpdate = questionInput.partial().extend({ sortOrder: z.number().int().min(0).optional() });
const strategyInput = z.object({ searchSourceId: idSchema, name: z.string().trim().min(1).max(500), queryText: z.string().refine((value) => value.trim().length > 0, "Query is required").max(10000), filtersText: z.string().max(10000).nullable().optional(), notes: z.string().trim().min(1).max(10000).nullable().optional() });
const strategyUpdate = strategyInput.partial();
const runInput = z.object({ searchSourceId: idSchema, sourceKeySnapshot: z.string().min(1).max(200), sourceDisplayNameSnapshot: z.string().min(1).max(500), strategyId: idSchema, queryText: z.string().min(1).max(10000), filtersTextSnapshot: z.string().max(10000).nullable().optional(), reportedResultCount: z.number().int().min(0), executedAt: z.coerce.date(), notes: z.string().trim().min(1).max(10000).nullable().optional() });
const recordInput = z.object({ searchRunId: idSchema, searchSourceId: idSchema, sourceRecordId: z.string().trim().min(1).max(2000).nullable().optional(), title: z.string().trim().min(1).max(1000), authors: z.array(z.string().trim().min(1).max(500)).default([]), abstract: z.string().trim().min(1).max(10000).nullable().optional(), doi: z.string().trim().min(1).max(1000).nullable().optional(), url: z.string().trim().min(1).max(4000).nullable().optional(), publicationYear: z.number().int().min(1000).max(3000).nullable().optional(), venue: z.string().trim().min(1).max(1000).nullable().optional(), retrievedAt: z.coerce.date(), rawCitation: z.string().trim().min(1).max(20000).nullable().optional() });

function parse<T>(schema: z.ZodType<T>, input: unknown): T { const result = schema.safeParse(input); if (!result.success) throw new DomainError("VALIDATION_ERROR", "Input failed validation", result.error.issues); return result.data; }
function id(idValue: string) { const result = idSchema.safeParse(idValue); if (!result.success) throw new DomainError("VALIDATION_ERROR", "Identifier must be a UUID", result.error.issues); return result.data; }
function mapQuestion(row: any) { return { id: String(row.id), projectId: String(row.projectId ?? row.project_id), identifier: String(row.identifier), label: String(row.label), sortOrder: Number(row.sortOrder ?? row.sort_order), createdAt: row.createdAt ?? row.created_at, updatedAt: row.updatedAt ?? row.updated_at, archivedAt: row.archivedAt ?? row.archived_at ?? null }; }
function mapSource(row: any) { return { id: String(row.id), projectId: String(row.projectId ?? row.project_id), sourceKey: String(row.sourceKey ?? row.source_key), displayName: String(row.displayName ?? row.display_name), baseUrl: row.baseUrl ?? row.base_url ?? null, notes: row.notes ?? null, createdAt: row.createdAt ?? row.created_at, updatedAt: row.updatedAt ?? row.updated_at, archivedAt: row.archivedAt ?? row.archived_at ?? null }; }
function mapStrategy(row: any) { return { id: String(row.id), projectId: String(row.projectId ?? row.project_id), searchSourceId: String(row.searchSourceId ?? row.search_source_id), name: String(row.name), queryText: String(row.queryText ?? row.query_text), filtersText: row.filtersText ?? row.filters_text ?? null, notes: row.notes ?? null, createdAt: row.createdAt ?? row.created_at, updatedAt: row.updatedAt ?? row.updated_at, archivedAt: row.archivedAt ?? row.archived_at ?? null }; }
function mapRun(row: any) { return { id: String(row.id), sequence: Number(row.sequence), projectId: String(row.projectId ?? row.project_id), searchSourceId: String(row.searchSourceId ?? row.search_source_id), sourceKeySnapshot: String(row.sourceKeySnapshot ?? row.source_key_snapshot), sourceDisplayNameSnapshot: String(row.sourceDisplayNameSnapshot ?? row.source_display_name_snapshot), strategyId: String(row.strategyId ?? row.strategy_id), queryText: String(row.queryText ?? row.query_text), filtersTextSnapshot: row.filtersTextSnapshot ?? row.filters_text_snapshot ?? null, reportedResultCount: Number(row.reportedResultCount ?? row.reported_result_count), executedAt: row.executedAt ?? row.executed_at, notes: row.notes ?? null, createdAt: row.createdAt ?? row.created_at }; }
function mapRecord(row: any) { return { id: String(row.id), projectId: String(row.projectId ?? row.project_id), searchRunId: String(row.searchRunId ?? row.search_run_id), searchSourceId: String(row.searchSourceId ?? row.search_source_id), sourceRecordId: row.sourceRecordId ?? row.source_record_id ?? null, title: String(row.title), authors: row.authors ?? [], abstract: row.abstract ?? null, doi: row.doi ?? null, url: row.url ?? null, publicationYear: row.publicationYear ?? row.publication_year ?? null, venue: row.venue ?? null, retrievedAt: row.retrievedAt ?? row.retrieved_at, rawCitation: row.rawCitation ?? row.raw_citation ?? null, createdAt: row.createdAt ?? row.created_at }; }
function mapPaper(row: any) { return { id: String(row.id), projectId: String(row.projectId ?? row.project_id), title: String(row.title), authors: row.authors ?? [], publicationYear: row.publicationYear ?? row.publication_year ?? null, venue: row.venue ?? null, doi: row.doi ?? null, abstract: row.abstract ?? null, bibliographicNote: row.bibliographicNote ?? row.bibliographic_note ?? null, createdAt: row.createdAt ?? row.created_at, updatedAt: row.updatedAt ?? row.updated_at }; }
function mapMatch(row: any) { return { id: String(row.id), sequence: Number(row.sequence), projectId: String(row.projectId ?? row.project_id), retrievedRecordId: String(row.retrievedRecordId ?? row.retrieved_record_id), paperId: String(row.paperId ?? row.paper_id), action: row.action as "linked" | "unlinked", createdAt: row.createdAt ?? row.created_at }; }

export function createAcquisitionServices(db: Database) {
  const questions = new ResearchQuestionRepository(db);
  const sources = new SearchSourceRepository(db);
  const strategies = new SearchStrategyRepository(db);
  const runs = new SearchRunRepository(db);
  const records = new RetrievedRecordRepository(db);

  async function requireProject(projectId: string, tx = db) { id(projectId); const [row] = await tx.select().from(projects).where(eq(projects.id, projectId)).limit(1); if (!row) throw new DomainError("PROJECT_NOT_FOUND", "Project was not found"); return row; }
  async function requireQuestion(projectId: string, questionId: string, tx = db) { await requireProject(projectId, tx); id(questionId); const row = await questions.findById(projectId, questionId, tx); if (!row) throw new DomainError("CROSS_PROJECT_REFERENCE", "Research question does not belong to this project"); return row; }
  async function requireSource(projectId: string, sourceId: string, active = false, tx = db) { await requireProject(projectId, tx); id(sourceId); const row = await sources.findById(projectId, sourceId, tx); if (!row) throw new DomainError("CROSS_PROJECT_REFERENCE", "Search source does not belong to this project"); if (active && row.archivedAt) throw new DomainError("VALIDATION_ERROR", "Archived search sources cannot be used"); return row; }
  async function requireStrategy(projectId: string, strategyId: string, active = false, tx = db) { await requireProject(projectId, tx); id(strategyId); const row = await strategies.findById(projectId, strategyId, tx); if (!row) throw new DomainError("CROSS_PROJECT_REFERENCE", "Search strategy does not belong to this project"); if (active && row.archivedAt) throw new DomainError("VALIDATION_ERROR", "Archived search strategies cannot be used"); return row; }
  async function requireRecord(projectId: string, recordId: string, tx = db) { await requireProject(projectId, tx); id(recordId); const row = await records.findById(projectId, recordId, tx); if (!row) throw new DomainError("CROSS_PROJECT_REFERENCE", "Retrieved record does not belong to this project"); return row; }
  async function requirePaper(projectId: string, paperId: string, tx = db) { await requireProject(projectId, tx); id(paperId); const [row] = await tx.select().from(papers).where(and(eq(papers.projectId, projectId), eq(papers.id, paperId))).limit(1); if (!row) throw new DomainError("CROSS_PROJECT_REFERENCE", "Paper does not belong to this project"); return row; }

  async function appendMatch(projectId: string, recordId: string, paperId: string, action: "linked" | "unlinked", tx: any) {
    try { return await records.insertMatch({ projectId, retrievedRecordId: recordId, paperId, action }, tx); }
    catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Retrieved record match is not valid in its current state"); throw error; }
  }

  const service = {
    async createProject(input: unknown) {
      const values: any = parse(createProjectSchema as any, input);
      const rawInput = (input ?? {}) as Record<string, unknown>;
      const initialQuestion = values.researchQuestion ?? values.initialResearchQuestion ?? rawInput.researchQuestion ?? rawInput.initialResearchQuestion ?? null;
      return db.transaction(async (tx) => {
        const [project] = await tx.insert(projects).values({ title: values.title, description: values.description ?? null }).returning();
        if (!project) throw new DomainError("DATABASE_CONSTRAINT", "Project could not be created");
        await tx.insert(searchSources).values(SEARCH_SOURCE_DEFINITIONS.map((source) => ({ projectId: project.id, sourceKey: source.sourceKey, displayName: source.displayName }))).onConflictDoNothing({ target: [searchSources.projectId, searchSources.sourceKey] });
        if (initialQuestion != null) await tx.insert(researchQuestions).values({ projectId: project.id, identifier: "RQ1", label: initialQuestion, sortOrder: 0 });
        return project;
      });
    },
    async listResearchQuestions(projectId: string, includeArchived = false) { await requireProject(projectId); return (await questions.list(projectId, includeArchived)).map(mapQuestion); },
    async getResearchQuestion(projectId: string, questionId: string) { return mapQuestion(await requireQuestion(projectId, questionId)); },
    async createResearchQuestion(projectId: string, input: unknown) { await requireProject(projectId); const values = parse(questionInput, input); try { return mapQuestion(await questions.create({ projectId, ...values })); } catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Research question identifier is already used in this project"); throw error; } },
    async updateResearchQuestion(projectId: string, questionId: string, input: unknown) { await requireQuestion(projectId, questionId); const values = parse(questionUpdate, input); if (!Object.keys(values).length) throw new DomainError("VALIDATION_ERROR", "Research question update cannot be empty"); try { const row = await questions.update(projectId, questionId, values); if (!row) throw new DomainError("NOT_FOUND", "Research question was not found"); return mapQuestion(row); } catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Research question identifier is already used in this project"); throw error; } },
    async reorderResearchQuestions(projectId: string, questionIds: string[]) { await requireProject(projectId); const ids = questionIds.map(id); return db.transaction(async (tx) => { const rows = await questions.list(projectId, false, tx); if (new Set(ids).size !== ids.length || ids.length !== rows.length || rows.some((row: any) => !ids.includes(row.id))) throw new DomainError("VALIDATION_ERROR", "Reorder must include every active research question exactly once"); await Promise.all(ids.map((questionId, index) => questions.update(projectId, questionId, { sortOrder: index }, tx))); return (await questions.list(projectId, false, tx)).map(mapQuestion); }); },
    async archiveResearchQuestion(projectId: string, questionId: string) { const row = await requireQuestion(projectId, questionId); if (row.archivedAt) return mapQuestion(row); return mapQuestion(await questions.archive(projectId, questionId)); },

    async listSearchSources(projectId: string, includeArchived = false) { await requireProject(projectId); return (await sources.list(projectId, includeArchived)).map(mapSource); },
    async getSearchSource(projectId: string, sourceId: string) { return mapSource(await requireSource(projectId, sourceId)); },
    async createSearchSource(projectId: string, input: unknown) { await requireProject(projectId); const values = parse(sourceInput, input); try { return mapSource(await sources.create({ projectId, ...values })); } catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Search source key is already used in this project"); throw error; } },
    async updateSearchSource(projectId: string, sourceId: string, input: unknown) { await requireSource(projectId, sourceId, true); const values = parse(sourceUpdate, input); if (!Object.keys(values).length) throw new DomainError("VALIDATION_ERROR", "Search source update cannot be empty"); try { return mapSource(await sources.update(projectId, sourceId, values)); } catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Search source key is already used in this project"); throw error; } },
    async archiveSearchSource(projectId: string, sourceId: string) { const row = await requireSource(projectId, sourceId); if (row.archivedAt) return mapSource(row); const activeStrategies = await db.execute(sql`select 1 from search_strategies where project_id=${projectId} and search_source_id=${sourceId} and archived_at is null limit 1`); if ((activeStrategies as unknown[]).length) throw new DomainError("PROTECTED_DELETE", "Search source cannot be archived while active strategies reference it"); return mapSource(await sources.archive(projectId, sourceId)); },

    async listSearchStrategies(projectId: string, includeArchived = false) { await requireProject(projectId); return (await strategies.list(projectId, includeArchived)).map(mapStrategy); },
    async getSearchStrategy(projectId: string, strategyId: string) { return mapStrategy(await requireStrategy(projectId, strategyId)); },
    async createSearchStrategy(projectId: string, input: unknown) { await requireProject(projectId); const values = parse(strategyInput, input); await requireSource(projectId, values.searchSourceId, true); try { return mapStrategy(await strategies.create({ projectId, ...values, filtersText: values.filtersText ?? null, notes: values.notes ?? null })); } catch (error) { if (isConstraintError(error)) throw new DomainError("CROSS_PROJECT_REFERENCE", "Search strategy source does not belong to this project"); throw error; } },
    async updateSearchStrategy(projectId: string, strategyId: string, input: unknown) { const current = await requireStrategy(projectId, strategyId); const values = parse(strategyUpdate, input); if (!Object.keys(values).length) throw new DomainError("VALIDATION_ERROR", "Search strategy update cannot be empty"); if (values.searchSourceId !== undefined) { await requireSource(projectId, values.searchSourceId, true); if (values.searchSourceId !== current.searchSourceId) throw new DomainError("VALIDATION_ERROR", "Search strategy source ownership is immutable; create a new strategy for another source"); } return mapStrategy(await strategies.update(projectId, strategyId, { ...values, searchSourceId: current.searchSourceId, filtersText: values.filtersText === undefined ? current.filtersText : values.filtersText, notes: values.notes === undefined ? current.notes : values.notes })); },
    async archiveSearchStrategy(projectId: string, strategyId: string) { const row = await requireStrategy(projectId, strategyId); if (row.archivedAt) return mapStrategy(row); return mapStrategy(await strategies.archive(projectId, strategyId)); },

    async createSearchRun(projectId: string, input: unknown) { await requireProject(projectId); const values = parse(runInput, input); const source = await requireSource(projectId, values.searchSourceId, true); const strategy = await requireStrategy(projectId, values.strategyId, true); if (strategy.searchSourceId !== source.id) throw new DomainError("VALIDATION_ERROR", "Search strategy must belong to the selected source"); if (values.sourceKeySnapshot !== source.sourceKey || values.sourceDisplayNameSnapshot !== source.displayName) throw new DomainError("VALIDATION_ERROR", "Search source snapshots do not match the source identity"); if (values.queryText !== strategy.queryText || (values.filtersTextSnapshot ?? null) !== (strategy.filtersText ?? null)) throw new DomainError("VALIDATION_ERROR", "Search run query and filter snapshots must match the selected strategy"); try { return mapRun(await runs.create({ projectId, ...values, filtersTextSnapshot: values.filtersTextSnapshot ?? null, notes: values.notes ?? null })); } catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Search run is not valid"); throw error; } },
    async getSearchRun(projectId: string, runId: string) { await requireProject(projectId); const checkedId = id(runId); const row = await runs.findById(projectId, checkedId); if (!row) { const [other] = await db.select({ id: searchRuns.id }).from(searchRuns).where(eq(searchRuns.id, checkedId)).limit(1); throw new DomainError(other ? "CROSS_PROJECT_REFERENCE" : "NOT_FOUND", "Search run was not found"); } return mapRun(row); },
    async listSearchRuns(projectId: string) { await requireProject(projectId); return (await runs.list(projectId)).map(mapRun); },

    async createRetrievedRecord(projectId: string, input: unknown) { await requireProject(projectId); const values = parse(recordInput, input); const run = await runs.findById(projectId, values.searchRunId); if (!run) throw new DomainError("CROSS_PROJECT_REFERENCE", "Search run does not belong to this project"); if (run.searchSourceId !== values.searchSourceId) throw new DomainError("VALIDATION_ERROR", "Retrieved record source must match its search run"); try { return mapRecord(await records.create({ projectId, ...values, sourceRecordId: values.sourceRecordId ?? null, abstract: values.abstract ?? null, doi: values.doi ?? null, url: values.url ?? null, publicationYear: values.publicationYear ?? null, venue: values.venue ?? null, rawCitation: values.rawCitation ?? null })); } catch (error) { if (isConstraintError(error)) throw new DomainError("VALIDATION_ERROR", "Retrieved record already exists for this run and source identifier"); throw error; } },
    async getRetrievedRecord(projectId: string, recordId: string) { await requireProject(projectId); const checkedId = id(recordId); const row = await records.findById(projectId, checkedId); if (!row) { const [other] = await db.select({ id: retrievedRecords.id }).from(retrievedRecords).where(eq(retrievedRecords.id, checkedId)).limit(1); throw new DomainError(other ? "CROSS_PROJECT_REFERENCE" : "NOT_FOUND", "Retrieved record was not found"); } return mapRecord(row); },
    async listRetrievedRecords(projectId: string, runId?: string) { await requireProject(projectId); if (runId !== undefined) id(runId); return (await records.list(projectId, runId)).map(mapRecord); },
    async getRetrievedRecordMatch(projectId: string, recordId: string) { await requireRecord(projectId, recordId); const current = await records.currentMatch(db, projectId, recordId); return current?.action === "linked" ? mapMatch(current) : null; },
    async listRetrievedRecordMatchHistory(projectId: string, recordId: string) { await requireRecord(projectId, recordId); return (await records.matchHistory(projectId, recordId)).map(mapMatch); },
    async listRetrievedRecordProjections(projectId: string, runId: string) {
      await requireProject(projectId); id(runId); if (!(await runs.findById(projectId, runId))) throw new DomainError("CROSS_PROJECT_REFERENCE", "Search run does not belong to this project");
      const [recordRows, currentRows, historyRows, duplicateRows] = await Promise.all([
        records.list(projectId, runId), records.currentMatchesForRun(projectId, runId), records.matchHistoryForRun(projectId, runId), records.duplicateCandidatesForRun(projectId, runId),
      ]);
      const currentByRecord = new Map<string, any>((currentRows as unknown as any[]).filter((row) => row.action === "linked").map((row) => [String(row.retrieved_record_id), mapMatch(row)]));
      const historyByRecord = new Map<string, any[]>();
      for (const row of historyRows as unknown as any[]) { const key = String(row.retrieved_record_id); historyByRecord.set(key, [...(historyByRecord.get(key) ?? []), mapMatch(row)]); }
      const duplicateByRecord = new Map<string, any[]>();
      for (const row of duplicateRows as unknown as any[]) { const key = String(row.retrieved_record_id); duplicateByRecord.set(key, [...(duplicateByRecord.get(key) ?? []), mapPaper(row)]); }
      return (recordRows as unknown as any[]).map((row) => { const record = mapRecord(row); return { record, match: currentByRecord.get(record.id) ?? null, history: historyByRecord.get(record.id) ?? [], duplicates: duplicateByRecord.get(record.id) ?? [] }; });
    },
    async linkRetrievedRecordToPaper(projectId: string, recordId: string, paperId: string) { id(recordId); id(paperId); await requirePaper(projectId, paperId); return db.transaction(async (tx) => { const record = await records.lockForUpdate(tx, projectId, recordId); if (!record) throw new DomainError("CROSS_PROJECT_REFERENCE", "Retrieved record does not belong to this project"); const current = await records.currentMatch(tx, projectId, recordId); if (current?.action === "linked") throw new DomainError("VALIDATION_ERROR", "Retrieved record is already linked to a Paper"); return mapMatch(await appendMatch(projectId, recordId, paperId, "linked", tx)); }); },
    async unlinkRetrievedRecordFromPaper(projectId: string, recordId: string, paperId: string) { id(recordId); id(paperId); await requirePaper(projectId, paperId); return db.transaction(async (tx) => { const record = await records.lockForUpdate(tx, projectId, recordId); if (!record) throw new DomainError("CROSS_PROJECT_REFERENCE", "Retrieved record does not belong to this project"); const current = await records.currentMatch(tx, projectId, recordId); if (!current || current.action !== "linked" || String(current.paper_id) !== paperId) throw new DomainError("VALIDATION_ERROR", "Retrieved record is not currently linked to this Paper"); return mapMatch(await appendMatch(projectId, recordId, paperId, "unlinked", tx)); }); },
    async relinkRetrievedRecord(projectId: string, recordId: string, fromPaperId: string, toPaperId: string) { id(recordId); id(fromPaperId); id(toPaperId); if (fromPaperId === toPaperId) throw new DomainError("VALIDATION_ERROR", "Relink target must differ from the current Paper"); await requirePaper(projectId, fromPaperId); await requirePaper(projectId, toPaperId); return db.transaction(async (tx) => { const record = await records.lockForUpdate(tx, projectId, recordId); if (!record) throw new DomainError("CROSS_PROJECT_REFERENCE", "Retrieved record does not belong to this project"); const current = await records.currentMatch(tx, projectId, recordId); if (!current || current.action !== "linked" || String(current.paper_id) !== fromPaperId) throw new DomainError("VALIDATION_ERROR", "Relink source Paper is not the current match"); const unlinked = await appendMatch(projectId, recordId, fromPaperId, "unlinked", tx); const linked = await appendMatch(projectId, recordId, toPaperId, "linked", tx); return { unlinked: mapMatch(unlinked), linked: mapMatch(linked) }; }); },
    async createPaperFromRetrievedRecord(projectId: string, recordId: string, overrides: Record<string, unknown> = {}) { const record = await requireRecord(projectId, recordId); const current = await records.currentMatch(db, projectId, recordId); if (current?.action === "linked") throw new DomainError("VALIDATION_ERROR", "Retrieved record is already linked to a Paper"); const parsedOverrides = parse(createPaperSchema.partial(), overrides); return db.transaction(async (tx) => { const locked = await records.lockForUpdate(tx, projectId, recordId); if (!locked) throw new DomainError("CROSS_PROJECT_REFERENCE", "Retrieved record does not belong to this project"); const latest = await records.currentMatch(tx, projectId, recordId); if (latest?.action === "linked") throw new DomainError("VALIDATION_ERROR", "Retrieved record is already linked to a Paper"); const [paper] = await tx.insert(papers).values({ projectId, title: parsedOverrides.title ?? record.title, authors: parsedOverrides.authors ?? record.authors, publicationYear: parsedOverrides.publicationYear ?? record.publicationYear, venue: parsedOverrides.venue ?? record.venue, doi: parsedOverrides.doi ?? record.doi, abstract: parsedOverrides.abstract ?? record.abstract, bibliographicNote: parsedOverrides.bibliographicNote ?? null }).returning(); if (!paper) throw new DomainError("DATABASE_CONSTRAINT", "Paper could not be created"); const linked = await appendMatch(projectId, recordId, paper.id, "linked", tx); return { paper: mapPaper(paper), match: mapMatch(linked) }; }); },
    async findPaperDuplicateCandidates(projectId: string, input: { doi?: string | null; title: string; publicationYear?: number | null }) { await requireProject(projectId); const doiValue = normalizeDoiForComparison(input.doi); const titleValue = normalizeTitleForComparison(input.title); if (!titleValue && !doiValue) return []; const rows = await db.execute(sql`select p.* from papers p where p.project_id=${projectId} and ((${doiValue}::text is not null and p.doi is not null and lower(regexp_replace(regexp_replace(btrim(p.doi), '^https?://(dx\\.)?doi\\.org/', '', 'i'), '^doi:[[:space:]]*', '', 'i'))=${doiValue}) or (${titleValue}::text is not null and ${input.publicationYear ?? null}::int is not null and lower(regexp_replace(btrim(p.title), '[[:space:]]+', ' ', 'g'))=${titleValue} and p.publication_year=${input.publicationYear ?? null})) order by p.created_at, p.id`); return (rows as unknown as any[]).map(mapPaper); },
    async findRetrievedRecordDuplicateCandidates(projectId: string, recordId: string) { const record = await requireRecord(projectId, recordId); const current = await records.currentMatch(db, projectId, recordId); const rows = await records.duplicateCandidates(projectId, { id: record.id, doi: record.doi, title: record.title, publicationYear: record.publicationYear, sourceRecordId: record.sourceRecordId }); return (rows as unknown as any[]).filter((row) => !current || String(row.id) !== String(current.paper_id)).map(mapPaper); },
    async getPaperRetrievalProvenance(projectId: string, paperId: string) {
      await requirePaper(projectId, paperId);
      const rows = await records.paperProvenance(projectId, paperId);
      return (rows as unknown as Record<string, unknown>[]).map((row) => ({
        retrievedRecordId: String(row.retrieved_record_id), searchRunId: String(row.search_run_id), searchSourceId: String(row.search_source_id),
        sourceRecordId: row.source_record_id == null ? null : String(row.source_record_id), title: String(row.title), authors: (row.authors as string[]) ?? [],
        abstract: row.abstract == null ? null : String(row.abstract), doi: row.doi == null ? null : String(row.doi), url: row.url == null ? null : String(row.url),
        publicationYear: row.publication_year == null ? null : Number(row.publication_year), venue: row.venue == null ? null : String(row.venue), rawCitation: row.raw_citation == null ? null : String(row.raw_citation),
        retrievedAt: row.retrieved_at as Date, executedAt: row.executed_at as Date, sourceKeySnapshot: String(row.source_key_snapshot), sourceDisplayNameSnapshot: String(row.source_display_name_snapshot),
        queryText: String(row.query_text), filtersTextSnapshot: row.filters_text_snapshot == null ? null : String(row.filters_text_snapshot), reportedResultCount: Number(row.reported_result_count), searchRunNotes: row.search_run_notes == null ? null : String(row.search_run_notes),
      }));
    },
  };
  return Object.assign(service, {
    createCustomSearchSource: service.createSearchSource,
    updateCustomSearchSource: service.updateSearchSource,
    archiveCustomSearchSource: service.archiveSearchSource,
    createPaperFromRecord: service.createPaperFromRetrievedRecord,
    linkRetrievedRecord: service.linkRetrievedRecordToPaper,
    unlinkRetrievedRecord: service.unlinkRetrievedRecordFromPaper,
    relinkRetrievedRecordMatch: service.relinkRetrievedRecord,
    getCurrentRetrievedRecordMatch: service.getRetrievedRecordMatch,
    listRetrievedRecordMatches: service.listRetrievedRecordMatchHistory,
    searchDuplicatePaperCandidates: service.findPaperDuplicateCandidates,
    getPaperAcquisitionProvenance: service.getPaperRetrievalProvenance,
  });
}

export type AcquisitionServices = ReturnType<typeof createAcquisitionServices>;
