import { sql } from "drizzle-orm";
import type { Database } from "@/db/client";
import { DomainError } from "@/domain/errors";
import { citationStyleSchema } from "@/domain/validation";
import { buildFormattedManuscript, type ManuscriptFormattingSource } from "@/application/manuscript-formatting";

type Executor = Pick<Database, "execute">;
type Row = Record<string, unknown>;
const uuid = (value: string) => { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new DomainError("VALIDATION_ERROR", "Identifier must be a UUID"); return value; };
const rows = (value: unknown) => value as unknown as Row[];
const idList = (ids: string[]) => sql.join(ids.map((id) => sql`${uuid(id)}::uuid`), sql`, `);
const date = (value: unknown) => value as Date;
const isDuplicatePlacementError = (error: unknown) => {
  if (typeof error !== "object" || error === null) return false;
  const value = error as { code?: unknown; constraint?: unknown; constraint_name?: unknown; detail?: unknown; cause?: { code?: unknown; constraint?: unknown; constraint_name?: unknown; detail?: unknown } };
  const code = String(value.code ?? value.cause?.code ?? "");
  const detail = `${String(value.constraint ?? value.constraint_name ?? value.cause?.constraint ?? value.cause?.constraint_name ?? "")} ${String(value.detail ?? value.cause?.detail ?? "")}`;
  return code === "23505" && /active.*revision|claim_revision.*unique|manuscript_claim_placements.*unique/i.test(detail);
};
const mapPaper = (r: Row) => ({ id: String(r.paper_id), projectId: String(r.project_id), title: String(r.paper_title), authors: (r.authors as string[]) ?? [], publicationYear: r.publication_year as number | null, venue: r.venue as string | null, doi: r.doi as string | null, abstract: r.abstract as string | null, bibliographicNote: r.bibliographic_note as string | null, createdAt: date(r.paper_created_at), updatedAt: date(r.paper_updated_at) });

export function createManuscriptServices(db: Database) {
  const mapManuscript = (r: Row) => ({ id: String(r.id), projectId: String(r.project_id), title: String(r.title), isDefault: Boolean(r.is_default), citationStyle: String(r.citation_style ?? "numeric") as "numeric" | "author_year", createdAt: date(r.created_at), updatedAt: date(r.updated_at) });
  const mapSection = (r: Row) => ({ id: String(r.id), projectId: String(r.project_id), manuscriptId: String(r.manuscript_id), title: String(r.title), sectionType: String(r.section_type), sortOrder: Number(r.sort_order), createdAt: date(r.created_at), updatedAt: date(r.updated_at), archivedAt: r.archived_at ? date(r.archived_at) : null });
  const mapPlacement = (r: Row) => ({ id: String(r.id), projectId: String(r.project_id), manuscriptId: String(r.manuscript_id), sectionId: String(r.section_id), claimId: String(r.claim_id), claimRevisionId: String(r.claim_revision_id), createdAt: date(r.created_at), removedAt: r.removed_at ? date(r.removed_at) : null });

  async function requireProject(projectId: string) { uuid(projectId); const found = rows(await db.execute(sql`select id, title from projects where id=${projectId} limit 1`))[0]; if (!found) throw new DomainError("PROJECT_NOT_FOUND", "Project was not found"); return found; }
  async function requireManuscript(projectId: string, manuscriptId: string) { await requireProject(projectId); uuid(manuscriptId); const found = rows(await db.execute(sql`select id, project_id, title, is_default, citation_style, created_at, updated_at from manuscripts where project_id=${projectId} and id=${manuscriptId} limit 1`))[0]; if (!found) throw new DomainError("CROSS_PROJECT_REFERENCE", "Manuscript does not belong to this project"); return found; }
  async function section(projectId: string, manuscriptId: string, sectionId: string, includeArchived = true) { await requireManuscript(projectId, manuscriptId); uuid(sectionId); const found = rows(await db.execute(sql`select id, project_id, manuscript_id, title, section_type, sort_order, created_at, updated_at, archived_at from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${sectionId} ${includeArchived ? sql`` : sql`and archived_at is null`} limit 1`))[0]; if (!found) throw new DomainError("CROSS_PROJECT_REFERENCE", "Section does not belong to this Manuscript"); return found; }

  async function getOrCreateDefaultManuscript(projectId: string) { await requireProject(projectId); const found = await db.transaction(async (tx) => { await tx.execute(sql`insert into manuscripts (project_id, title, is_default) values (${projectId}, 'Manuscript', true) on conflict (project_id) where is_default do nothing`); const row = rows(await tx.execute(sql`select id, project_id, title, is_default, citation_style, created_at, updated_at from manuscripts where project_id=${projectId} and is_default=true limit 1`))[0]; if (!row) throw new DomainError("DATABASE_CONSTRAINT", "Default Manuscript could not be created"); return row; }); return mapManuscript(found); }

  async function setManuscriptCitationStyle(projectId: string, manuscriptId: string, style: string) {
    await requireManuscript(projectId, manuscriptId);
    const parsed = citationStyleSchema.safeParse(style);
    if (!parsed.success) throw new DomainError("VALIDATION_ERROR", "Unsupported citation style");
    const result = rows(await db.execute(sql`update manuscripts set citation_style=${parsed.data}, updated_at=now() where project_id=${projectId} and id=${manuscriptId} returning id, project_id, title, is_default, citation_style, created_at, updated_at`))[0];
    if (!result) throw new DomainError("CROSS_PROJECT_REFERENCE", "Manuscript does not belong to this project");
    return mapManuscript(result);
  }
  async function createSection(projectId: string, manuscriptId: string, input: { title: string; sectionType?: string }) { await requireManuscript(projectId, manuscriptId); const title = input.title?.trim(); if (!title) throw new DomainError("VALIDATION_ERROR", "Section title is required"); const allowed = ["introduction", "methods", "results", "discussion", "limitations", "conclusion", "custom"]; const sectionType = input.sectionType ?? "custom"; if (!allowed.includes(sectionType)) throw new DomainError("VALIDATION_ERROR", "Invalid section type"); const max = rows(await db.execute(sql`select coalesce(max(sort_order), -1) as max_order from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and archived_at is null`))[0]; const result = rows(await db.execute(sql`insert into manuscript_sections (project_id, manuscript_id, title, section_type, sort_order) values (${projectId}, ${manuscriptId}, ${title}, ${sectionType}, ${Number(max?.max_order ?? -1) + 1}) returning id, project_id, manuscript_id, title, section_type, sort_order, created_at, updated_at, archived_at`))[0]; return mapSection(result); }
  async function renameSection(projectId: string, manuscriptId: string, sectionId: string, title: string) { await section(projectId, manuscriptId, sectionId, false); const value = title?.trim(); if (!value) throw new DomainError("VALIDATION_ERROR", "Section title is required"); const result = rows(await db.execute(sql`update manuscript_sections set title=${value}, updated_at=now() where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${sectionId} and archived_at is null returning id, project_id, manuscript_id, title, section_type, sort_order, created_at, updated_at, archived_at`))[0]; return mapSection(result); }
  async function reorderSections(projectId: string, manuscriptId: string, orderedSectionIds: string[]) { await requireManuscript(projectId, manuscriptId); orderedSectionIds.forEach(uuid); await db.transaction(async (tx) => { await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} for update`); const active = rows(await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and archived_at is null order by sort_order, id`)).map((r) => String(r.id)); if (active.length !== orderedSectionIds.length || new Set(orderedSectionIds).size !== active.length || active.some((id) => !orderedSectionIds.includes(id))) throw new DomainError("VALIDATION_ERROR", "Section reorder must include every active section exactly once"); for (let i = 0; i < orderedSectionIds.length; i += 1) await tx.execute(sql`update manuscript_sections set sort_order=${i}, updated_at=now() where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${orderedSectionIds[i]}`); }); return getManuscript(projectId, manuscriptId); }
  async function archiveSection(projectId: string, manuscriptId: string, sectionId: string) { await section(projectId, manuscriptId, sectionId, false); const active = rows(await db.execute(sql`select id from manuscript_section_items where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and removed_at is null limit 1`)); if (active.length) throw new DomainError("PROTECTED_DELETE", "Section cannot be archived while it contains active items"); const result = rows(await db.execute(sql`update manuscript_sections set archived_at=now(), updated_at=now() where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${sectionId} and archived_at is null returning id, project_id, manuscript_id, title, section_type, sort_order, created_at, updated_at, archived_at`))[0]; return mapSection(result); }

  async function validatePlacementTarget(executor: Executor, projectId: string, claimRevisionId: string, currentSequence?: number, claimId?: string) { uuid(claimRevisionId); const target = rows(await executor.execute(sql`select r.id as claim_revision_id, r.project_id, r.claim_id, r.sequence, r.state, r.finalized_at, (select current_r.state from claim_revisions current_r where current_r.project_id=r.project_id and current_r.claim_id=r.claim_id and current_r.finalized_at is not null order by current_r.sequence desc limit 1) as current_claim_state from claim_revisions r join claims c on c.project_id=r.project_id and c.id=r.claim_id where r.project_id=${projectId} and r.id=${claimRevisionId} ${claimId ? sql`and r.claim_id=${uuid(claimId)}` : sql``} limit 1`))[0]; if (!target) throw new DomainError("CROSS_PROJECT_REFERENCE", "ClaimRevision does not belong to this project or Claim"); if (target.finalized_at == null || String(target.state) !== "active") throw new DomainError("INELIGIBLE_REFERENCE", "Only finalized active ClaimRevisions may be placed"); if (String(target.current_claim_state) !== "active") throw new DomainError("INELIGIBLE_REFERENCE", "A withdrawn Claim cannot receive a new placement"); if (currentSequence !== undefined && Number(target.sequence) <= currentSequence) throw new DomainError("VALIDATION_ERROR", "Replacement must use a higher ClaimRevision sequence"); return target; }

  async function placeClaimRevision(projectId: string, manuscriptId: string, sectionId: string, claimRevisionId: string, position?: number) { await section(projectId, manuscriptId, sectionId, false); return db.transaction(async (tx) => { await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${sectionId} for update`); const active = rows(await tx.execute(sql`select id from manuscript_section_items where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and removed_at is null order by sort_order, id`)); const insertAt = position ?? active.length; if (!Number.isInteger(insertAt) || insertAt < 0 || insertAt > active.length) throw new DomainError("VALIDATION_ERROR", "Item position is outside the active Section range"); await validatePlacementTarget(tx, projectId, claimRevisionId); if (insertAt < active.length) await tx.execute(sql`update manuscript_section_items set sort_order=sort_order + 1 where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and removed_at is null and sort_order >= ${insertAt}`); try { const placement = rows(await tx.execute(sql`insert into manuscript_claim_placements (project_id, manuscript_id, section_id, claim_id, claim_revision_id) select ${projectId}, ${manuscriptId}, ${sectionId}, claim_id, ${claimRevisionId} from claim_revisions where project_id=${projectId} and id=${claimRevisionId} returning id, project_id, manuscript_id, section_id, claim_id, claim_revision_id, created_at, removed_at`))[0]; if (!placement) throw new DomainError("DATABASE_CONSTRAINT", "Claim placement could not be created"); await tx.execute(sql`insert into manuscript_section_items (id, project_id, manuscript_id, section_id, item_type, sort_order) values (${placement.id}, ${projectId}, ${manuscriptId}, ${sectionId}, 'claim', ${insertAt})`); await tx.execute(sql`insert into manuscript_section_item_claims (section_item_id, project_id, manuscript_id, section_id, item_type, placement_id) values (${placement.id}, ${projectId}, ${manuscriptId}, ${sectionId}, 'claim', ${placement.id})`); return mapPlacement(placement); } catch (error) { if (error instanceof DomainError) throw error; if (isDuplicatePlacementError(error)) throw new DomainError("DUPLICATE_LINK", "ClaimRevision is already placed in this section"); throw error; } }); }
  async function replacePlacedClaimRevision(projectId: string, manuscriptId: string, placementId: string, claimRevisionId: string, expectedClaimRevisionId?: string) { await requireManuscript(projectId, manuscriptId); uuid(placementId); return db.transaction(async (tx) => { const current = rows(await tx.execute(sql`select p.id, p.project_id, p.manuscript_id, p.section_id, p.claim_id, p.claim_revision_id, p.created_at, p.removed_at, sic.section_item_id from manuscript_claim_placements p join manuscript_section_item_claims sic on sic.project_id=p.project_id and sic.placement_id=p.id where p.project_id=${projectId} and p.manuscript_id=${manuscriptId} and p.id=${placementId} for update`))[0]; if (!current) throw new DomainError("NOT_FOUND", "Placement was not found"); await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${current.section_id} for update`); if (current.removed_at) throw new DomainError("VALIDATION_ERROR", "Removed placements cannot be replaced"); if (expectedClaimRevisionId && String(current.claim_revision_id) !== uuid(expectedClaimRevisionId)) throw new DomainError("VALIDATION_ERROR", "Placement changed while replacement was being prepared"); const oldRevision = rows(await tx.execute(sql`select sequence from claim_revisions where project_id=${projectId} and id=${current.claim_revision_id}`))[0]; await validatePlacementTarget(tx, projectId, claimRevisionId, Number(oldRevision.sequence), String(current.claim_id)); const result = rows(await tx.execute(sql`update manuscript_claim_placements set claim_revision_id=${claimRevisionId} where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${placementId} and removed_at is null returning id, project_id, manuscript_id, section_id, claim_id, claim_revision_id, created_at, removed_at`))[0]; return mapPlacement(result); }); }
  async function removeClaimPlacement(projectId: string, manuscriptId: string, placementId: string) { await requireManuscript(projectId, manuscriptId); uuid(placementId); return db.transaction(async (tx) => { const current = rows(await tx.execute(sql`select p.id, p.project_id, p.manuscript_id, p.section_id, p.claim_id, p.claim_revision_id, p.created_at, p.removed_at, sic.section_item_id, i.removed_at as item_removed_at from manuscript_claim_placements p join manuscript_section_item_claims sic on sic.project_id=p.project_id and sic.placement_id=p.id join manuscript_section_items i on i.project_id=sic.project_id and i.id=sic.section_item_id where p.project_id=${projectId} and p.manuscript_id=${manuscriptId} and p.id=${placementId} for update`))[0]; if (!current) throw new DomainError("NOT_FOUND", "Active placement was not found"); await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${current.section_id} for update`); if (current.removed_at || current.item_removed_at) throw new DomainError("NOT_FOUND", "Active placement was not found"); const removedAt = rows(await tx.execute(sql`select now() as removed_at`))[0].removed_at; const result = rows(await tx.execute(sql`update manuscript_claim_placements set removed_at=${removedAt} where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${placementId} and removed_at is null returning id, project_id, manuscript_id, section_id, claim_id, claim_revision_id, created_at, removed_at`))[0]; await tx.execute(sql`update manuscript_section_items set removed_at=${removedAt} where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${current.section_item_id} and removed_at is null`); return mapPlacement(result); }); }

  async function createProseBlock(projectId: string, manuscriptId: string, sectionId: string, input: string | { text: string; position?: number }, legacyPosition?: number) { const text = typeof input === "string" ? input : input?.text; const position = typeof input === "string" ? legacyPosition : input?.position; await section(projectId, manuscriptId, sectionId, false); if (!text || text.trim().length === 0) throw new DomainError("VALIDATION_ERROR", "Prose text is required"); if (text.length > 50000) throw new DomainError("VALIDATION_ERROR", "Prose text is too long"); return db.transaction(async (tx) => { await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${sectionId} for update`); const active = rows(await tx.execute(sql`select id from manuscript_section_items where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and removed_at is null order by sort_order, id`)); const insertAt = position ?? active.length; if (!Number.isInteger(insertAt) || insertAt < 0 || insertAt > active.length) throw new DomainError("VALIDATION_ERROR", "Item position is outside the active Section range"); if (insertAt < active.length) await tx.execute(sql`update manuscript_section_items set sort_order=sort_order + 1 where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and removed_at is null and sort_order >= ${insertAt}`); const item = rows(await tx.execute(sql`insert into manuscript_section_items (project_id, manuscript_id, section_id, item_type, sort_order) values (${projectId}, ${manuscriptId}, ${sectionId}, 'prose', ${insertAt}) returning id, project_id, manuscript_id, section_id, item_type, sort_order, created_at, removed_at`))[0]; const prose = rows(await tx.execute(sql`insert into manuscript_prose_blocks (id, project_id, manuscript_id, section_id, section_item_id, item_type, text) values (${item.id}, ${projectId}, ${manuscriptId}, ${sectionId}, ${item.id}, 'prose', ${text}) returning id, project_id, section_item_id, text, created_at, updated_at`))[0]; return { id: String(item.id), projectId, manuscriptId, sectionId, itemType: "prose" as const, sortOrder: Number(item.sort_order), text: String(prose.text), createdAt: date(prose.created_at), updatedAt: date(prose.updated_at), removedAt: null }; }); }
  async function updateProseBlock(projectId: string, manuscriptId: string, proseBlockId: string, input: string | { text: string }) { const text = typeof input === "string" ? input : input?.text; await requireManuscript(projectId, manuscriptId); uuid(proseBlockId); if (!text || text.trim().length === 0) throw new DomainError("VALIDATION_ERROR", "Prose text is required"); if (text.length > 50000) throw new DomainError("VALIDATION_ERROR", "Prose text is too long"); const result = rows(await db.execute(sql`update manuscript_prose_blocks p set text=${text}, updated_at=now() from manuscript_section_items i where p.project_id=${projectId} and p.id=${proseBlockId} and p.section_item_id=i.id and i.project_id=p.project_id and i.manuscript_id=${manuscriptId} and i.item_type='prose' and i.removed_at is null returning p.id, p.project_id, p.section_item_id, p.text, p.created_at, p.updated_at`))[0]; if (!result) throw new DomainError("NOT_FOUND", "Active prose block was not found"); return { id: String(result.id), projectId: String(result.project_id), sectionItemId: String(result.section_item_id), text: String(result.text), createdAt: date(result.created_at), updatedAt: date(result.updated_at) }; }
  async function removeProseBlock(projectId: string, manuscriptId: string, proseBlockId: string) { await requireManuscript(projectId, manuscriptId); uuid(proseBlockId); return db.transaction(async (tx) => { const current = rows(await tx.execute(sql`select p.id, p.project_id, p.section_item_id, p.text, p.created_at, p.updated_at, i.removed_at from manuscript_prose_blocks p join manuscript_section_items i on i.project_id=p.project_id and i.id=p.section_item_id where p.project_id=${projectId} and p.id=${proseBlockId} and i.manuscript_id=${manuscriptId} and i.item_type='prose' for update`))[0]; if (!current || current.removed_at) throw new DomainError("NOT_FOUND", "Active prose block was not found"); const removedAt = rows(await tx.execute(sql`select now() as removed_at`))[0].removed_at; await tx.execute(sql`update manuscript_section_items set removed_at=${removedAt} where project_id=${projectId} and id=${current.section_item_id} and removed_at is null`); return { id: String(current.id), projectId: String(current.project_id), sectionItemId: String(current.section_item_id), text: String(current.text), createdAt: date(current.created_at), updatedAt: date(current.updated_at), removedAt: date(removedAt) }; }); }
  async function reorderSectionItems(projectId: string, manuscriptId: string, sectionId: string, orderedItemIds: string[]) { await section(projectId, manuscriptId, sectionId, false); orderedItemIds.forEach(uuid); await db.transaction(async (tx) => { await tx.execute(sql`select id from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and id=${sectionId} for update`); const active = rows(await tx.execute(sql`select id from manuscript_section_items where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and removed_at is null order by sort_order, id`)).map((r) => String(r.id)); if (active.length !== orderedItemIds.length || new Set(orderedItemIds).size !== active.length || active.some((id) => !orderedItemIds.includes(id))) throw new DomainError("VALIDATION_ERROR", "Section item reorder must include every active item exactly once"); for (let i = 0; i < orderedItemIds.length; i += 1) await tx.execute(sql`update manuscript_section_items set sort_order=${i} where project_id=${projectId} and manuscript_id=${manuscriptId} and section_id=${sectionId} and id=${orderedItemIds[i]} and removed_at is null`); }); return getManuscript(projectId, manuscriptId); }

  async function getManuscriptPlacementHistory(projectId: string, manuscriptId: string, placementId: string) { await requireManuscript(projectId, manuscriptId); uuid(placementId); return rows(await db.execute(sql`select id, sequence, project_id, manuscript_id, section_id, placement_id, claim_id, event_type, from_claim_revision_id, to_claim_revision_id, occurred_at from manuscript_claim_placement_events where project_id=${projectId} and manuscript_id=${manuscriptId} and placement_id=${placementId} order by sequence`)).map((r) => ({ id: String(r.id), sequence: Number(r.sequence), projectId: String(r.project_id), manuscriptId: String(r.manuscript_id), sectionId: String(r.section_id), placementId: String(r.placement_id), claimId: String(r.claim_id), eventType: String(r.event_type), fromClaimRevisionId: r.from_claim_revision_id ? String(r.from_claim_revision_id) : null, toClaimRevisionId: r.to_claim_revision_id ? String(r.to_claim_revision_id) : null, occurredAt: date(r.occurred_at) })); }

  async function getManuscript(projectId: string, manuscriptId: string) {
    const manuscript = await requireManuscript(projectId, manuscriptId);
    const sectionRows = rows(await db.execute(sql`select id, project_id, manuscript_id, title, section_type, sort_order, created_at, updated_at, archived_at from manuscript_sections where project_id=${projectId} and manuscript_id=${manuscriptId} and archived_at is null order by sort_order, id`));
    const itemRows = rows(await db.execute(sql`select i.id, i.project_id, i.manuscript_id, i.section_id, i.item_type, i.sort_order, i.created_at, i.removed_at, pb.id as prose_id, pb.text as prose_text, pb.created_at as prose_created_at, pb.updated_at as prose_updated_at, p.id as placement_id, p.claim_id, p.claim_revision_id, p.created_at as placement_created_at, p.removed_at as placement_removed_at, c.created_at as claim_created_at, r.sequence, r.state, r.claim_text, r.researcher_note, r.created_at as revision_created_at, r.finalized_at, latest.id as latest_revision_id, latest.sequence as latest_revision_sequence, latest.state as latest_revision_state from manuscript_section_items i left join manuscript_prose_blocks pb on pb.project_id=i.project_id and pb.section_item_id=i.id and i.item_type='prose' left join manuscript_section_item_claims sic on sic.project_id=i.project_id and sic.section_item_id=i.id and i.item_type='claim' left join manuscript_claim_placements p on p.project_id=sic.project_id and p.id=sic.placement_id left join claims c on c.project_id=p.project_id and c.id=p.claim_id left join claim_revisions r on r.project_id=p.project_id and r.id=p.claim_revision_id left join lateral (select current_r.id, current_r.sequence, current_r.state from claim_revisions current_r where current_r.project_id=p.project_id and current_r.claim_id=p.claim_id and current_r.finalized_at is not null order by current_r.sequence desc limit 1) latest on true where i.project_id=${projectId} and i.manuscript_id=${manuscriptId} and i.removed_at is null and exists (select 1 from manuscript_sections s where s.project_id=i.project_id and s.manuscript_id=i.manuscript_id and s.id=i.section_id and s.archived_at is null) order by i.section_id, i.sort_order, i.id`));
    const claimRows = itemRows.filter((r) => String(r.item_type) === "claim"); if (claimRows.some((r) => !r.placement_id || !r.claim_revision_id)) throw new DomainError("DATABASE_CONSTRAINT", "Claim SectionItem is missing its placement subtype"); const revisionIds = claimRows.map((r) => String(r.claim_revision_id));
    const supportCounts = new Map<string, number>(); if (revisionIds.length) { const counts = rows(await db.execute(sql`select claim_revision_id, count(*)::int as count from (select project_id, claim_revision_id from claim_revision_evidence_supports where project_id=${projectId} and claim_revision_id in (${idList(revisionIds)}) union all select project_id, claim_revision_id from claim_revision_extraction_supports where project_id=${projectId} and claim_revision_id in (${idList(revisionIds)}) union all select project_id, claim_revision_id from claim_revision_synthesis_supports where project_id=${projectId} and claim_revision_id in (${idList(revisionIds)})) supports group by claim_revision_id`)); counts.forEach((r) => supportCounts.set(String(r.claim_revision_id), Number(r.count))); }
    const candidateRows = revisionIds.length ? rows(await db.execute(sql`select * from (select s.claim_revision_id, 1 as source_rank, s.created_at as support_created_at, e.created_at as provenance_created_at, s.evidence_id::text as target_id, e.paper_id, p.title as paper_title, p.authors, p.publication_year, p.venue, p.doi, p.abstract, p.bibliographic_note, p.created_at as paper_created_at, p.updated_at as paper_updated_at from claim_revision_evidence_supports s join evidence e on e.project_id=s.project_id and e.id=s.evidence_id join papers p on p.project_id=e.project_id and p.id=e.paper_id where s.project_id=${projectId} and s.claim_revision_id in (${idList(revisionIds)}) union all select s.claim_revision_id, 2, s.created_at, x.created_at, s.extraction_revision_id::text, e.paper_id, p.title, p.authors, p.publication_year, p.venue, p.doi, p.abstract, p.bibliographic_note, p.created_at, p.updated_at from claim_revision_extraction_supports s join extraction_revision_evidence x on x.project_id=s.project_id and x.revision_id=s.extraction_revision_id join evidence e on e.project_id=x.project_id and e.id=x.evidence_id join papers p on p.project_id=e.project_id and p.id=e.paper_id where s.project_id=${projectId} and s.claim_revision_id in (${idList(revisionIds)}) union all select s.claim_revision_id, 3, s.created_at, ss.created_at, s.synthesis_revision_id::text, e.paper_id, p.title, p.authors, p.publication_year, p.venue, p.doi, p.abstract, p.bibliographic_note, p.created_at, p.updated_at from claim_revision_synthesis_supports s join synthesis_revision_supports ss on ss.project_id=s.project_id and ss.synthesis_revision_id=s.synthesis_revision_id join extraction_revision_evidence x on x.project_id=ss.project_id and x.revision_id=ss.extraction_revision_id join evidence e on e.project_id=x.project_id and e.id=x.evidence_id join papers p on p.project_id=e.project_id and p.id=e.paper_id where s.project_id=${projectId} and s.claim_revision_id in (${idList(revisionIds)})) candidates order by claim_revision_id, source_rank, support_created_at, provenance_created_at, target_id, paper_id`)) : [];
    const candidateByRevision = new Map<string, Row[]>(); for (const r of candidateRows) { const key = String(r.claim_revision_id); const list = candidateByRevision.get(key) ?? []; if (!list.some((x) => String(x.paper_id) === String(r.paper_id))) list.push(r); candidateByRevision.set(key, list); }
    const claimItems = claimRows.map((r) => { const candidates = candidateByRevision.get(String(r.claim_revision_id)) ?? []; const supportStatus = (supportCounts.get(String(r.claim_revision_id)) ?? 0) > 0 ? "supported" as const : "unsupported" as const; const revision = { id: String(r.claim_revision_id), sequence: Number(r.sequence), projectId, claimId: String(r.claim_id), lifecycle: String(r.state) as "active" | "withdrawn", claimText: r.claim_text as string | null, researcherNote: r.researcher_note as string | null, createdAt: date(r.revision_created_at), finalizedAt: date(r.finalized_at) }; const mapped = candidates.map((x) => ({ paper: mapPaper(x), pathCount: 1, supportKinds: [Number(x.source_rank) === 1 ? "evidence" : Number(x.source_rank) === 2 ? "extractionRevision" : "synthesisRevision"] as ("evidence" | "extractionRevision" | "synthesisRevision")[], citationNumber: 0 })); const placement = { ...mapPlacement({ id: r.placement_id, project_id: r.project_id, manuscript_id: r.manuscript_id, section_id: r.section_id, claim_id: r.claim_id, claim_revision_id: r.claim_revision_id, created_at: r.placement_created_at, removed_at: r.placement_removed_at }), claim: { id: String(r.claim_id), projectId, createdAt: date(r.claim_created_at) }, claimRevision: revision, latestClaimRevisionId: String(r.latest_revision_id), claimLifecycle: String(r.latest_revision_state) as "active" | "withdrawn", supportStatus, isCurrentClaimRevision: String(r.latest_revision_id) === String(r.claim_revision_id), isSuperseded: Number(r.latest_revision_sequence) > Number(r.sequence), citationCandidates: mapped, citationNumbers: [] as number[] }; return { id: String(r.id), projectId, manuscriptId, sectionId: String(r.section_id), itemType: "claim" as const, sortOrder: Number(r.sort_order), createdAt: date(r.created_at), removedAt: null, placement, citationCandidates: mapped, citationNumbers: [] as number[] }; });
    const proseItems = itemRows.filter((r) => String(r.item_type) === "prose").map((r) => { if (!r.prose_id) throw new DomainError("DATABASE_CONSTRAINT", "Prose SectionItem is missing its prose subtype"); return { id: String(r.id), projectId, manuscriptId, sectionId: String(r.section_id), itemType: "prose" as const, sortOrder: Number(r.sort_order), createdAt: date(r.created_at), removedAt: null, text: String(r.prose_text), updatedAt: date(r.prose_updated_at) }; });
    const items = [...claimItems, ...proseItems].sort((a, b) => { const sa = sectionRows.findIndex((s) => String(s.id) === a.sectionId); const sb = sectionRows.findIndex((s) => String(s.id) === b.sectionId); return sa - sb || a.sortOrder - b.sortOrder || a.id.localeCompare(b.id); }); const bibliography = new Map<string, { candidate: Row; sectionId: string; sectionItemId: string; placementId: string; claimRevisionId: string; itemPosition: number; candidateRank: number }>();
    for (const item of items) if (item.itemType === "claim") for (const [candidateRank, candidate] of (candidateByRevision.get(item.placement.claimRevisionId) ?? []).entries()) { const key = String(candidate.paper_id); if (!bibliography.has(key)) bibliography.set(key, { candidate, sectionId: item.sectionId, sectionItemId: item.id, placementId: item.placement.id, claimRevisionId: item.placement.claimRevisionId, itemPosition: items.indexOf(item), candidateRank }); }
    const orderedBib = [...bibliography.values()].sort((a, b) => a.itemPosition - b.itemPosition || a.candidateRank - b.candidateRank || String(a.candidate.paper_id).localeCompare(String(b.candidate.paper_id))); const numbers = new Map<string, number>(); orderedBib.forEach((x, i) => numbers.set(String(x.candidate.paper_id), i + 1)); claimItems.forEach((item) => { item.citationNumbers = item.citationCandidates.map((x) => numbers.get(x.paper.id)).filter((n): n is number => n !== undefined).sort((a, b) => a - b); item.placement.citationNumbers = item.citationNumbers; item.citationCandidates.forEach((x) => { x.citationNumber = numbers.get(x.paper.id) ?? 0; }); });
    const warnings = claimItems.flatMap((item) => { const v = item.placement; return [ ...(v.supportStatus === "unsupported" ? [{ sectionId: item.sectionId, sectionItemId: item.id, placementId: v.id, claimRevisionId: v.claimRevisionId, code: "unsupported_claim_revision" as const, message: "This placed ClaimRevision has no typed support." }] : []), ...(v.citationCandidates.length === 0 ? [{ sectionId: item.sectionId, sectionItemId: item.id, placementId: v.id, claimRevisionId: v.claimRevisionId, code: "no_citation_candidates" as const, message: "No citation candidates are reachable from this exact ClaimRevision." }] : []), ...(v.isSuperseded ? [{ sectionId: item.sectionId, sectionItemId: item.id, placementId: v.id, claimRevisionId: v.claimRevisionId, code: "superseded_claim_revision" as const, message: "A newer ClaimRevision exists; this placement remains exact until replaced." }] : []), ...(v.claimLifecycle === "withdrawn" ? [{ sectionId: item.sectionId, sectionItemId: item.id, placementId: v.id, claimRevisionId: v.claimRevisionId, code: "withdrawn_parent_claim" as const, message: "The stable Claim is currently withdrawn; historical placement is retained." }] : []) ]; });
    return { manuscript: mapManuscript(manuscript), sections: sectionRows.map(mapSection).map((s) => ({ ...s, items: items.filter((item) => item.sectionId === s.id) })), bibliographyCandidates: orderedBib.map((x, i) => ({ paper: mapPaper(x.candidate), citationNumber: i + 1, firstOccurrence: { sectionId: x.sectionId, sectionItemId: x.sectionItemId, placementId: x.placementId, claimRevisionId: x.claimRevisionId } })), warnings, counts: { sectionCount: sectionRows.length, activeItemCount: items.length, proseBlockCount: proseItems.length, claimItemCount: claimItems.length, placedClaimCount: claimItems.length, unsupportedPlacedClaimCount: claimItems.filter((x) => x.placement.supportStatus === "unsupported").length, supersededPlacedClaimCount: claimItems.filter((x) => x.placement.isSuperseded).length, withdrawnParentClaimCount: claimItems.filter((x) => x.placement.claimLifecycle === "withdrawn").length, distinctCitationCandidatePaperCount: orderedBib.length } };
  }
  async function getFormattedManuscript(projectId: string, manuscriptId: string) {
    const view = await getManuscript(projectId, manuscriptId);
    return buildFormattedManuscript(view as unknown as ManuscriptFormattingSource);
  }
  async function listPlaceableClaimRevisions(projectId: string) { await requireProject(projectId); return rows(await db.execute(sql`select r.id, r.project_id, r.claim_id, r.sequence, r.state, r.claim_text, r.finalized_at, (select current_r.id from claim_revisions current_r where current_r.project_id=r.project_id and current_r.claim_id=r.claim_id and current_r.finalized_at is not null order by current_r.sequence desc limit 1) as latest_revision_id, (select current_r.state from claim_revisions current_r where current_r.project_id=r.project_id and current_r.claim_id=r.claim_id and current_r.finalized_at is not null order by current_r.sequence desc limit 1) as current_claim_state from claim_revisions r where r.project_id=${projectId} and r.finalized_at is not null and r.state='active' order by r.sequence desc, r.id`)).filter((r) => String(r.current_claim_state) === "active").map((r) => ({ id: String(r.id), claimId: String(r.claim_id), sequence: Number(r.sequence), claimText: String(r.claim_text), isCurrent: String(r.latest_revision_id) === String(r.id) })); }
  return { getOrCreateDefaultManuscript, setManuscriptCitationStyle, getManuscript, getFormattedManuscript, createSection, renameSection, reorderSections, archiveSection, placeClaimRevision, replacePlacedClaimRevision, removeClaimPlacement, createProseBlock, updateProseBlock, removeProseBlock, reorderSectionItems, getManuscriptPlacementHistory, listPlaceableClaimRevisions };
}
